export type City = "rome" | "florence";

export type PlaceCategory =
  | "stay"
  | "station"
  | "attraction"
  | "food"
  | "cafe"
  | "shopping"
  | "view"
  | "rest";

export type Priority = 1 | 2 | 3;

export type Place = {
  id: string;
  city: City;
  name: string;
  koName: string;
  category: PlaceCategory;
  area: string;
  lat: number;
  lng: number;
  priority: Priority;
  rank: number;
  durationMin: number;
  reservation: "필수" | "권장" | "불필요" | "확인";
  bestTime: string;
  price: "무료" | "낮음" | "중간" | "높음" | "확인";
  safety: "보통" | "주의" | "밤주의";
  photo: 1 | 2 | 3;
  girlsTripFit: 1 | 2 | 3;
  tags: string[];
  why: string;
  tips: string[];
  koreanTips?: string[];
  menuHints?: string[];
  watchOut?: string[];
  pairWith: string[];
  sourceIds: string[];
};

export type RouteStop = {
  placeId: string;
  time?: string;
  locked?: boolean;
  note?: string;
};

export type TripDay = {
  id: string;
  date: string;
  label: string;
  city: City;
  title: string;
  areaFocus: string;
  route: RouteStop[];
  fallback: string[];
  checklist: string[];
};

export type PhraseGroup = {
  title: string;
  lines: {
    ko: string;
    it: string;
    sound: string;
  }[];
};

export type Source = {
  id: string;
  label: string;
  url: string;
  note: string;
};

export const cityLabels: Record<City, string> = {
  rome: "로마",
  florence: "피렌체",
};

export const categoryLabels: Record<PlaceCategory, string> = {
  stay: "숙소",
  station: "역/이동",
  attraction: "명소",
  food: "맛집",
  cafe: "카페",
  shopping: "쇼핑",
  view: "전망",
  rest: "휴식",
};

export const places: Place[] = [
  {
    id: "rome-hotel",
    city: "rome",
    name: "Rome hotel placeholder",
    koName: "로마 숙소 위치 입력",
    category: "stay",
    area: "숙소",
    lat: 41.9024,
    lng: 12.4964,
    priority: 1,
    rank: 100,
    durationMin: 10,
    reservation: "확인",
    bestTime: "매일",
    price: "확인",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["숙소", "기준점", "수정필수"],
    why: "실제 숙소 주소로 교체하면 모든 루트가 바로 재계산된다.",
    tips: ["주소 확정 후 위도/경도를 바꾸기", "밤에는 숙소 복귀 버튼의 기준점으로 사용"],
    pairWith: ["roma-termini"],
    sourceIds: [],
  },
  {
    id: "roma-termini",
    city: "rome",
    name: "Roma Termini",
    koName: "로마 테르미니역",
    category: "station",
    area: "Termini",
    lat: 41.9009,
    lng: 12.5018,
    priority: 1,
    rank: 95,
    durationMin: 20,
    reservation: "확인",
    bestTime: "기차 이동일",
    price: "확인",
    safety: "주의",
    photo: 1,
    girlsTripFit: 2,
    tags: ["기차", "소매치기주의", "이동"],
    why: "로마에서 피렌체로 넘어갈 때 핵심 기준점.",
    tips: ["플랫폼 변경 확인", "캐리어와 휴대폰을 몸 앞쪽으로", "역 주변 늦은 밤 도보 이동은 줄이기"],
    pairWith: ["santa-maria-novella"],
    sourceIds: ["trenitalia", "italo", "state-italy"],
  },
  {
    id: "colosseum-forum",
    city: "rome",
    name: "Colosseum, Roman Forum and Palatine Hill",
    koName: "콜로세움 + 포로 로마노 + 팔라티노",
    category: "attraction",
    area: "고대 로마",
    lat: 41.8902,
    lng: 12.4922,
    priority: 1,
    rank: 99,
    durationMin: 180,
    reservation: "필수",
    bestTime: "오전",
    price: "높음",
    safety: "주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["must", "예약", "사진", "소매치기주의"],
    why: "로마 첫 방문에서 빼기 어려운 대표 코스. 한 권역으로 묶어 반나절을 잡는 게 효율적이다.",
    tips: ["예약 시간 20-30분 전 도착", "개선문 방향 외부 사진 먼저", "주변 팔찌/사진 호객 접근 무시"],
    pairWith: ["monti", "la-taverna-dei-fori-imperiali", "caffe-propaganda"],
    sourceIds: ["turismo-roma", "colosseum-official", "state-italy"],
  },
  {
    id: "pantheon",
    city: "rome",
    name: "Pantheon",
    koName: "판테온",
    category: "attraction",
    area: "중심부",
    lat: 41.8986,
    lng: 12.4769,
    priority: 1,
    rank: 96,
    durationMin: 40,
    reservation: "권장",
    bestTime: "오전 또는 해질녘 전",
    price: "중간",
    safety: "주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["must", "실내", "사진", "중심동선"],
    why: "나보나, 트레비, 스페인 계단을 잇는 중심부 루트의 축.",
    tips: ["광장 쪽은 붐비므로 휴대폰 주의", "비 오면 실내 대체 코스로 좋음", "근처 식당은 예약 후보 위주로"],
    pairWith: ["piazza-navona", "trevi-fountain", "armando-al-pantheon", "giolitti"],
    sourceIds: ["turismo-roma", "pantheon-official"],
  },
  {
    id: "trevi-fountain",
    city: "rome",
    name: "Trevi Fountain",
    koName: "트레비 분수",
    category: "attraction",
    area: "중심부",
    lat: 41.9009,
    lng: 12.4833,
    priority: 1,
    rank: 94,
    durationMin: 25,
    reservation: "확인",
    bestTime: "아침 일찍 또는 밤 초반",
    price: "무료",
    safety: "주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["must", "사진", "혼잡", "소매치기주의"],
    why: "짧게 들러도 만족도가 높지만 혼잡도가 높아 시간 선택이 중요하다.",
    tips: ["계단 주변 가방 앞으로", "사진 찍어준다는 접근 주의", "방문 전 출입 통제 여부 확인"],
    pairWith: ["spanish-steps", "pantheon", "sant-eustachio"],
    sourceIds: ["turismo-roma", "state-italy"],
  },
  {
    id: "spanish-steps",
    city: "rome",
    name: "Spanish Steps",
    koName: "스페인 계단",
    category: "attraction",
    area: "스페인 광장",
    lat: 41.9059,
    lng: 12.4823,
    priority: 2,
    rank: 82,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "오전 또는 저녁 산책",
    price: "무료",
    safety: "주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["사진", "쇼핑근처", "혼잡"],
    why: "중심부 산책과 쇼핑 동선을 이어주는 사진 스팟.",
    tips: ["계단 착석 금지 규정 주의", "쇼핑백 노출 줄이기", "트레비와 묶으면 도보 효율이 좋음"],
    pairWith: ["trevi-fountain", "via-del-corso", "villa-borghese"],
    sourceIds: ["turismo-roma"],
  },
  {
    id: "piazza-navona",
    city: "rome",
    name: "Piazza Navona",
    koName: "나보나 광장",
    category: "attraction",
    area: "중심부",
    lat: 41.8992,
    lng: 12.4731,
    priority: 1,
    rank: 90,
    durationMin: 35,
    reservation: "불필요",
    bestTime: "해질녘",
    price: "무료",
    safety: "주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["사진", "산책", "중심동선"],
    why: "판테온, 캄포 데 피오리, 트라스테베레로 이어지는 유연한 허브.",
    tips: ["광장 바로 앞 식당은 가격/후기 확인", "소매치기와 팔찌 호객 주의", "저녁 전 사진이 좋음"],
    pairWith: ["pantheon", "campo-de-fiori", "giolitti"],
    sourceIds: ["turismo-roma"],
  },
  {
    id: "vatican-museums",
    city: "rome",
    name: "Vatican Museums and Sistine Chapel",
    koName: "바티칸 박물관 + 시스티나 성당",
    category: "attraction",
    area: "바티칸/프라티",
    lat: 41.9065,
    lng: 12.4536,
    priority: 1,
    rank: 98,
    durationMin: 210,
    reservation: "필수",
    bestTime: "예약 시간 기준",
    price: "높음",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["must", "예약", "실내", "체력소모"],
    why: "시간 예약이 전체 하루를 결정하는 고정 일정.",
    tips: ["예약 링크와 QR 따로 저장", "성당 복장 기준에 맞추기", "박물관 후 바로 무리한 동선 줄이기"],
    pairWith: ["st-peters-basilica", "castel-sant-angelo", "old-bridge-gelateria"],
    sourceIds: ["vatican-museums", "state-italy"],
  },
  {
    id: "st-peters-basilica",
    city: "rome",
    name: "St. Peter's Basilica",
    koName: "성 베드로 대성당",
    category: "attraction",
    area: "바티칸/프라티",
    lat: 41.9022,
    lng: 12.4539,
    priority: 1,
    rank: 92,
    durationMin: 80,
    reservation: "확인",
    bestTime: "오전",
    price: "확인",
    safety: "주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["must", "복장", "줄", "사진"],
    why: "바티칸 일정의 자연스러운 두 번째 축.",
    tips: ["어깨/무릎 노출 주의", "입장 줄 긴 날은 과감히 외부 사진으로 전환", "성당 주변 호객 투어 주의"],
    pairWith: ["vatican-museums", "castel-sant-angelo"],
    sourceIds: ["vatican-official"],
  },
  {
    id: "castel-sant-angelo",
    city: "rome",
    name: "Castel Sant'Angelo",
    koName: "산탄젤로 성",
    category: "attraction",
    area: "바티칸/강변",
    lat: 41.9031,
    lng: 12.4663,
    priority: 2,
    rank: 78,
    durationMin: 80,
    reservation: "권장",
    bestTime: "해질녘",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["전망", "사진", "바티칸근처"],
    why: "바티칸 이후 강변 산책과 전망으로 이어지는 선택지.",
    tips: ["체력이 남을 때만 내부 입장", "다리 위 사진 좋음", "늦은 시간 강변 골목은 밝은 길 위주로"],
    pairWith: ["vatican-museums", "piazza-navona"],
    sourceIds: ["turismo-roma"],
  },
  {
    id: "trastevere",
    city: "rome",
    name: "Trastevere",
    koName: "트라스테베레",
    category: "attraction",
    area: "트라스테베레",
    lat: 41.8898,
    lng: 12.4707,
    priority: 1,
    rank: 86,
    durationMin: 120,
    reservation: "불필요",
    bestTime: "저녁 전후",
    price: "무료",
    safety: "밤주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["저녁", "골목", "사진", "맛집"],
    why: "로마 저녁 분위기를 가장 쉽게 만들 수 있는 권역.",
    tips: ["귀가 경로를 식사 전에 정하기", "늦은 시간 외진 골목 줄이기", "예약 식당 기준으로 걷기"],
    pairWith: ["da-enzo", "trapizzino-trastevere"],
    sourceIds: ["turismo-roma", "state-italy"],
  },
  {
    id: "villa-borghese",
    city: "rome",
    name: "Villa Borghese and Pincio Terrace",
    koName: "보르게세 공원 + 핀초 언덕",
    category: "view",
    area: "보르게세",
    lat: 41.9126,
    lng: 12.4853,
    priority: 2,
    rank: 74,
    durationMin: 75,
    reservation: "불필요",
    bestTime: "해질녘",
    price: "무료",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["전망", "사진", "휴식"],
    why: "스페인 계단 이후 체력 회복과 전망을 동시에 잡는 루트.",
    tips: ["어두워지면 큰 길 위주", "여유 있는 날에 배치", "카페 휴식과 묶기"],
    pairWith: ["spanish-steps", "via-del-corso"],
    sourceIds: ["turismo-roma"],
  },
  {
    id: "campo-de-fiori",
    city: "rome",
    name: "Campo de' Fiori",
    koName: "캄포 데 피오리",
    category: "attraction",
    area: "중심부",
    lat: 41.8956,
    lng: 12.4722,
    priority: 2,
    rank: 70,
    durationMin: 35,
    reservation: "불필요",
    bestTime: "오전 시장 또는 저녁 전",
    price: "무료",
    safety: "주의",
    photo: 2,
    girlsTripFit: 2,
    tags: ["시장", "중심동선", "후보"],
    why: "나보나와 트라스테베레 사이를 메우는 짧은 선택지.",
    tips: ["시장 상품 가격 확인", "밤 늦게는 분위기 보고 이동", "식사는 검증된 후보 위주"],
    pairWith: ["piazza-navona", "trastevere"],
    sourceIds: ["turismo-roma"],
  },
  {
    id: "via-del-corso",
    city: "rome",
    name: "Via del Corso",
    koName: "비아 델 코르소",
    category: "shopping",
    area: "중심부",
    lat: 41.9039,
    lng: 12.4806,
    priority: 2,
    rank: 68,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "오후",
    price: "확인",
    safety: "주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["쇼핑", "비상구매", "혼잡"],
    why: "중심부 산책 중 쇼핑과 비상 구매를 해결하기 좋다.",
    tips: ["쇼핑백은 한쪽에 몰지 않기", "붐비는 횡단보도에서 휴대폰 주의", "스페인 계단과 묶기"],
    pairWith: ["spanish-steps", "trevi-fountain"],
    sourceIds: ["turismo-roma", "state-italy"],
  },
  {
    id: "armando-al-pantheon",
    city: "rome",
    name: "Armando al Pantheon",
    koName: "아르만도 알 판테온",
    category: "food",
    area: "중심부",
    lat: 41.8983,
    lng: 12.4774,
    priority: 1,
    rank: 91,
    durationMin: 90,
    reservation: "필수",
    bestTime: "점심 또는 이른 저녁",
    price: "높음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["예약", "로마음식", "중심부"],
    why: "판테온 바로 옆에서 동선 효율과 식사 만족도를 같이 노리는 후보.",
    tips: ["예약 가능 여부 먼저 확인", "식사 전후 판테온/나보나 연결", "메뉴 가격 확인"],
    pairWith: ["pantheon", "piazza-navona"],
    sourceIds: ["restaurant-official"],
  },
  {
    id: "roscioli",
    city: "rome",
    name: "Roscioli Salumeria con Cucina",
    koName: "로쇼리",
    category: "food",
    area: "중심부",
    lat: 41.8947,
    lng: 12.4747,
    priority: 1,
    rank: 89,
    durationMin: 90,
    reservation: "필수",
    bestTime: "점심 또는 저녁",
    price: "높음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["예약", "파스타", "중심부"],
    why: "로마 음식 후보 중 여행 만족도가 높은 편이고 중심부 동선에 끼우기 좋다.",
    tips: ["예약 실패 시 근처 대안 준비", "무거운 일정 뒤에는 여유 있게", "와인 주문은 예산 확인"],
    pairWith: ["campo-de-fiori", "piazza-navona"],
    sourceIds: ["restaurant-official"],
  },
  {
    id: "da-enzo",
    city: "rome",
    name: "Da Enzo al 29",
    koName: "다 엔초 알 29",
    category: "food",
    area: "트라스테베레",
    lat: 41.8894,
    lng: 12.4719,
    priority: 1,
    rank: 87,
    durationMin: 90,
    reservation: "권장",
    bestTime: "이른 저녁",
    price: "중간",
    safety: "밤주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["저녁", "트라스테베레", "웨이팅"],
    why: "트라스테베레 저녁 루트의 대표 후보.",
    tips: ["웨이팅 플랜 준비", "식사 후 숙소 복귀 경로 먼저 열기", "늦어지면 택시 검토"],
    pairWith: ["trastevere", "trapizzino-trastevere"],
    sourceIds: ["restaurant-official", "state-italy"],
  },
  {
    id: "felice-testaccio",
    city: "rome",
    name: "Felice a Testaccio",
    koName: "펠리체 아 테스타치오",
    category: "food",
    area: "Testaccio",
    lat: 41.8789,
    lng: 12.4756,
    priority: 2,
    rank: 78,
    durationMin: 100,
    reservation: "필수",
    bestTime: "저녁",
    price: "중간",
    safety: "밤주의",
    photo: 1,
    girlsTripFit: 2,
    tags: ["카초에페페", "예약", "택시검토"],
    why: "맛은 강한 후보지만 중심 동선에서 살짝 벗어나 일정 여유가 있을 때 적합.",
    tips: ["왕복 이동시간 확인", "저녁 늦으면 택시", "테스타치오 일정이 없으면 무리하지 않기"],
    pairWith: ["trastevere"],
    sourceIds: ["restaurant-official"],
  },
  {
    id: "giolitti",
    city: "rome",
    name: "Giolitti",
    koName: "졸리티 젤라또",
    category: "cafe",
    area: "중심부",
    lat: 41.9004,
    lng: 12.4783,
    priority: 2,
    rank: 80,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "오후",
    price: "낮음",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["젤라또", "휴식", "중심부"],
    why: "판테온/트레비 사이에서 짧게 쉬기 좋은 후보.",
    tips: ["주문 방식 확인", "가방은 몸 앞으로", "혼잡하면 포장 후 광장 이동"],
    pairWith: ["pantheon", "trevi-fountain"],
    sourceIds: ["turismo-roma"],
  },
  {
    id: "sant-eustachio",
    city: "rome",
    name: "Sant'Eustachio Il Caffe",
    koName: "산테우스타키오 일 카페",
    category: "cafe",
    area: "중심부",
    lat: 41.8987,
    lng: 12.4749,
    priority: 2,
    rank: 76,
    durationMin: 20,
    reservation: "불필요",
    bestTime: "오전 또는 오후",
    price: "낮음",
    safety: "주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["커피", "휴식", "중심부"],
    why: "나보나와 판테온 사이의 짧은 카페 브레이크.",
    tips: ["서서 마시면 빠름", "좌석 비용 확인", "붐비면 테이크아웃"],
    pairWith: ["pantheon", "piazza-navona"],
    sourceIds: ["turismo-roma"],
  },
  {
    id: "caffe-propaganda",
    city: "rome",
    name: "Caffe Propaganda",
    koName: "카페 프로파간다",
    category: "cafe",
    area: "고대 로마",
    lat: 41.8896,
    lng: 12.4947,
    priority: 2,
    rank: 71,
    durationMin: 45,
    reservation: "권장",
    bestTime: "콜로세움 전후",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["휴식", "브런치", "콜로세움근처"],
    why: "콜로세움 권역에서 체력 회복용으로 넣기 좋다.",
    tips: ["혼잡 시간 예약 확인", "콜로세움 입장 전후 여유 시간 확보", "가벼운 식사 대체 가능"],
    pairWith: ["colosseum-forum"],
    sourceIds: ["restaurant-official"],
  },
  {
    id: "trapizzino-trastevere",
    city: "rome",
    name: "Trapizzino Trastevere",
    koName: "트라피치노 트라스테베레",
    category: "food",
    area: "트라스테베레",
    lat: 41.8902,
    lng: 12.4708,
    priority: 2,
    rank: 69,
    durationMin: 35,
    reservation: "불필요",
    bestTime: "간식 또는 가벼운 저녁",
    price: "낮음",
    safety: "밤주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["간식", "저녁대체", "트라스테베레"],
    why: "웨이팅이 길거나 피곤할 때 식사 플랜을 가볍게 바꾸기 좋다.",
    tips: ["서서 먹는 플랜 가능", "늦은 밤에는 귀가 경로 우선", "Da Enzo 실패 대안"],
    pairWith: ["trastevere", "da-enzo"],
    sourceIds: ["restaurant-official"],
  },
  {
    id: "florence-hotel",
    city: "florence",
    name: "Florence hotel placeholder",
    koName: "피렌체 숙소 위치 입력",
    category: "stay",
    area: "숙소",
    lat: 43.7744,
    lng: 11.2492,
    priority: 1,
    rank: 100,
    durationMin: 10,
    reservation: "확인",
    bestTime: "매일",
    price: "확인",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["숙소", "기준점", "수정필수"],
    why: "실제 숙소 주소로 교체하면 피렌체 도보 루트가 정확해진다.",
    tips: ["주소 확정 후 위도/경도를 바꾸기", "역과 숙소 사이 캐리어 이동 시간 확인"],
    pairWith: ["santa-maria-novella"],
    sourceIds: [],
  },
  {
    id: "santa-maria-novella",
    city: "florence",
    name: "Firenze Santa Maria Novella",
    koName: "피렌체 산타 마리아 노벨라역",
    category: "station",
    area: "SMN/역",
    lat: 43.7767,
    lng: 11.2482,
    priority: 1,
    rank: 96,
    durationMin: 20,
    reservation: "확인",
    bestTime: "기차 이동일",
    price: "확인",
    safety: "주의",
    photo: 1,
    girlsTripFit: 2,
    tags: ["기차", "소매치기주의", "이동"],
    why: "로마에서 도착하는 기준점이자 숙소 이동의 시작점.",
    tips: ["캐리어 이동 동선 확인", "역 안팎 휴대폰 주의", "숙소 체크인 전 짐 보관 여부 확인"],
    pairWith: ["florence-hotel", "mercato-centrale"],
    sourceIds: ["trenitalia", "italo", "state-italy"],
  },
  {
    id: "duomo-florence",
    city: "florence",
    name: "Cathedral of Santa Maria del Fiore",
    koName: "피렌체 두오모",
    category: "attraction",
    area: "두오모",
    lat: 43.7731,
    lng: 11.2560,
    priority: 1,
    rank: 99,
    durationMin: 120,
    reservation: "필수",
    bestTime: "오전",
    price: "높음",
    safety: "주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["must", "예약", "사진", "복장"],
    why: "피렌체 첫 방문의 중심. 쿠폴라/종탑 예약 여부가 하루 구조를 결정한다.",
    tips: ["쿠폴라 등반은 체력 소모 큼", "성당 복장 주의", "광장 혼잡 시 휴대폰 주의"],
    pairWith: ["accademia", "mercato-centrale", "caffe-gilli"],
    sourceIds: ["feelflorence", "duomo-official"],
  },
  {
    id: "uffizi",
    city: "florence",
    name: "Uffizi Galleries",
    koName: "우피치 미술관",
    category: "attraction",
    area: "시뇨리아/아르노",
    lat: 43.7687,
    lng: 11.2550,
    priority: 1,
    rank: 98,
    durationMin: 180,
    reservation: "필수",
    bestTime: "예약 시간 기준",
    price: "높음",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["must", "예약", "실내", "체력소모"],
    why: "피렌체 핵심 미술관. 예약 시간 중심으로 오전/오후 루트를 짜야 한다.",
    tips: ["입장 전후 휴식 카페 확보", "대표 작품 위주로 볼 목록 정하기", "가방 규정 확인"],
    pairWith: ["piazza-signoria", "ponte-vecchio", "gelateria-dei-neri"],
    sourceIds: ["uffizi-official", "feelflorence"],
  },
  {
    id: "accademia",
    city: "florence",
    name: "Galleria dell'Accademia",
    koName: "아카데미아 미술관",
    category: "attraction",
    area: "두오모/산마르코",
    lat: 43.7768,
    lng: 11.2588,
    priority: 1,
    rank: 92,
    durationMin: 80,
    reservation: "필수",
    bestTime: "오전 또는 늦은 오후",
    price: "중간",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["예약", "실내", "다비드"],
    why: "다비드상 하나만으로도 만족도가 높은 짧고 강한 코스.",
    tips: ["두오모 권역과 묶기", "예약 시간이 애매하면 과감히 다음날로", "입구 주변 혼잡 주의"],
    pairWith: ["duomo-florence", "mercato-centrale"],
    sourceIds: ["accademia-official", "feelflorence"],
  },
  {
    id: "ponte-vecchio",
    city: "florence",
    name: "Ponte Vecchio",
    koName: "베키오 다리",
    category: "attraction",
    area: "아르노",
    lat: 43.7680,
    lng: 11.2531,
    priority: 1,
    rank: 90,
    durationMin: 35,
    reservation: "불필요",
    bestTime: "해질녘 전후",
    price: "무료",
    safety: "주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["사진", "산책", "혼잡"],
    why: "우피치와 올트라르노를 잇는 필수 산책 포인트.",
    tips: ["다리 위 혼잡 시 가방 앞으로", "사진은 강변에서 찍는 것도 좋음", "해질녘 루트에 배치"],
    pairWith: ["uffizi", "piazzale-michelangelo", "pitti-boboli"],
    sourceIds: ["feelflorence", "state-italy"],
  },
  {
    id: "piazza-signoria",
    city: "florence",
    name: "Piazza della Signoria and Palazzo Vecchio",
    koName: "시뇨리아 광장 + 베키오 궁전",
    category: "attraction",
    area: "시뇨리아/아르노",
    lat: 43.7696,
    lng: 11.2558,
    priority: 1,
    rank: 87,
    durationMin: 50,
    reservation: "권장",
    bestTime: "우피치 전후",
    price: "확인",
    safety: "주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["광장", "사진", "우피치근처"],
    why: "우피치 전후 남는 시간에 자연스럽게 들어가는 핵심 광장.",
    tips: ["광장 카페 가격 확인", "혼잡 시간 소지품 주의", "내부 입장은 여유 있을 때만"],
    pairWith: ["uffizi", "ponte-vecchio", "gelateria-dei-neri"],
    sourceIds: ["feelflorence"],
  },
  {
    id: "piazzale-michelangelo",
    city: "florence",
    name: "Piazzale Michelangelo",
    koName: "미켈란젤로 광장",
    category: "view",
    area: "전망/올트라르노",
    lat: 43.7629,
    lng: 11.2652,
    priority: 1,
    rank: 88,
    durationMin: 70,
    reservation: "불필요",
    bestTime: "해질녘",
    price: "무료",
    safety: "밤주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["전망", "사진", "해질녘", "택시검토"],
    why: "피렌체 전경 사진의 만족도가 가장 높은 편. 단, 오르막과 귀가를 고려해야 한다.",
    tips: ["해진 뒤 복귀 경로 미리 열기", "피곤하면 버스/택시", "비 오면 다른 실내 코스로 교체"],
    pairWith: ["ponte-vecchio", "pitti-boboli", "osteria-santo-spirito"],
    sourceIds: ["feelflorence", "state-italy"],
  },
  {
    id: "pitti-boboli",
    city: "florence",
    name: "Pitti Palace and Boboli Gardens",
    koName: "피티 궁전 + 보볼리 정원",
    category: "attraction",
    area: "올트라르노",
    lat: 43.7652,
    lng: 11.2500,
    priority: 2,
    rank: 79,
    durationMin: 150,
    reservation: "권장",
    bestTime: "오전 또는 늦은 오후",
    price: "높음",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["정원", "사진", "여유코스"],
    why: "올트라르노 하루를 풍성하게 만들지만 체력과 날씨를 탄다.",
    tips: ["더운 날 한낮은 피하기", "우피치와 같은 날이면 과하지 않게", "편한 신발 필수"],
    pairWith: ["ponte-vecchio", "osteria-santo-spirito", "piazzale-michelangelo"],
    sourceIds: ["uffizi-official", "feelflorence"],
  },
  {
    id: "santa-croce",
    city: "florence",
    name: "Basilica di Santa Croce",
    koName: "산타 크로체 성당",
    category: "attraction",
    area: "산타 크로체",
    lat: 43.7687,
    lng: 11.2620,
    priority: 2,
    rank: 76,
    durationMin: 70,
    reservation: "권장",
    bestTime: "오전 또는 오후",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["성당", "실내", "복장"],
    why: "우피치 권역에서 동쪽으로 확장할 때 좋은 실내 후보.",
    tips: ["복장 주의", "우피치 뒤 체력 남을 때", "근처 젤라또와 묶기"],
    pairWith: ["gelateria-dei-neri", "uffizi"],
    sourceIds: ["feelflorence"],
  },
  {
    id: "mercato-centrale",
    city: "florence",
    name: "Mercato Centrale",
    koName: "메르카토 첸트랄레",
    category: "food",
    area: "SMN/산 로렌초",
    lat: 43.7767,
    lng: 11.2533,
    priority: 2,
    rank: 77,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "점심 또는 간단한 저녁",
    price: "중간",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["푸드홀", "역근처", "비상식사"],
    why: "예약이 꼬였을 때 실패 확률 낮은 식사 대안.",
    tips: ["자리 확보 먼저", "귀중품 의자 뒤에 걸지 않기", "역 이동 전후로 좋음"],
    pairWith: ["santa-maria-novella", "duomo-florence", "accademia"],
    sourceIds: ["feelflorence", "state-italy"],
  },
  {
    id: "all-antico-vinaio",
    city: "florence",
    name: "All'Antico Vinaio",
    koName: "알 안티코 비나이오",
    category: "food",
    area: "시뇨리아/산타 크로체",
    lat: 43.7693,
    lng: 11.2581,
    priority: 2,
    rank: 82,
    durationMin: 40,
    reservation: "불필요",
    bestTime: "애매한 식사 시간",
    price: "낮음",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["샌드위치", "웨이팅", "간단식사"],
    why: "간단하고 유명하지만 줄이 길면 무리하지 않는 후보.",
    tips: ["혼잡하면 패스", "먹을 장소 생각하기", "우피치/산타 크로체 사이에 배치"],
    pairWith: ["uffizi", "santa-croce", "gelateria-dei-neri"],
    sourceIds: ["restaurant-official"],
  },
  {
    id: "la-giostra",
    city: "florence",
    name: "La Giostra",
    koName: "라 조스트라",
    category: "food",
    area: "산타 크로체",
    lat: 43.7711,
    lng: 11.2606,
    priority: 1,
    rank: 83,
    durationMin: 100,
    reservation: "필수",
    bestTime: "저녁",
    price: "높음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["예약", "저녁", "분위기"],
    why: "여자 2명 여행에서 분위기 있는 저녁 한 번을 맡기 좋은 후보.",
    tips: ["예산 확인", "예약 시간 후 귀가 경로 확인", "산타 크로체 권역과 묶기"],
    pairWith: ["santa-croce", "gelateria-dei-neri"],
    sourceIds: ["restaurant-official"],
  },
  {
    id: "osteria-santo-spirito",
    city: "florence",
    name: "Osteria Santo Spirito",
    koName: "오스테리아 산토 스피리토",
    category: "food",
    area: "올트라르노",
    lat: 43.7667,
    lng: 11.2473,
    priority: 1,
    rank: 82,
    durationMin: 90,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "밤주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["저녁", "올트라르노", "예약권장"],
    why: "올트라르노 저녁 동선에서 분위기와 접근성이 좋은 후보.",
    tips: ["해진 뒤 숙소 복귀 경로 확인", "피티/미켈란젤로 광장 후 배치", "예약 확인"],
    pairWith: ["pitti-boboli", "piazzale-michelangelo"],
    sourceIds: ["restaurant-official"],
  },
  {
    id: "gelateria-dei-neri",
    city: "florence",
    name: "Gelateria dei Neri",
    koName: "젤라테리아 데이 네리",
    category: "cafe",
    area: "산타 크로체",
    lat: 43.7684,
    lng: 11.2591,
    priority: 2,
    rank: 73,
    durationMin: 20,
    reservation: "불필요",
    bestTime: "오후",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["젤라또", "휴식", "우피치근처"],
    why: "우피치와 산타 크로체 사이 짧은 휴식 후보.",
    tips: ["혼잡하면 들고 이동", "현금/카드 확인", "식사 전이면 작은 사이즈"],
    pairWith: ["uffizi", "santa-croce", "all-antico-vinaio"],
    sourceIds: ["feelflorence"],
  },
  {
    id: "caffe-gilli",
    city: "florence",
    name: "Caffe Gilli",
    koName: "카페 질리",
    category: "cafe",
    area: "두오모/레푸블리카",
    lat: 43.7716,
    lng: 11.2537,
    priority: 2,
    rank: 70,
    durationMin: 35,
    reservation: "불필요",
    bestTime: "오전 또는 오후",
    price: "중간",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["카페", "휴식", "중심부"],
    why: "두오모 주변에서 앉아 쉬고 싶을 때 쓰는 클래식 카페 후보.",
    tips: ["테이블 가격 확인", "붐비면 서서 커피", "쇼핑/두오모 사이 휴식"],
    pairWith: ["duomo-florence", "piazza-signoria"],
    sourceIds: ["feelflorence"],
  },
  {
    id: "officina-profumo",
    city: "florence",
    name: "Officina Profumo-Farmaceutica di Santa Maria Novella",
    koName: "산타 마리아 노벨라 약국",
    category: "shopping",
    area: "SMN/역",
    lat: 43.7738,
    lng: 11.2491,
    priority: 2,
    rank: 75,
    durationMin: 45,
    reservation: "불필요",
    bestTime: "오후",
    price: "확인",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["쇼핑", "선물", "사진"],
    why: "쇼핑과 공간 경험을 동시에 잡는 피렌체다운 후보.",
    tips: ["구매 품목 미리 정하기", "역/숙소 동선과 묶기", "혼잡하면 사진만 짧게"],
    pairWith: ["santa-maria-novella", "florence-hotel"],
    sourceIds: ["feelflorence"],
  },
];

export const tripDays: TripDay[] = [
  {
    id: "2026-06-19",
    date: "2026-06-19",
    label: "6/19 금",
    city: "rome",
    title: "도착 + 중심부 가볍게",
    areaFocus: "숙소 주변, 판테온, 나보나",
    route: [
      { placeId: "rome-hotel", time: "체크인", locked: true },
      { placeId: "pantheon", note: "도착 체력에 따라 내부 또는 외부만" },
      { placeId: "piazza-navona" },
      { placeId: "sant-eustachio", note: "짧은 카페 브레이크" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["비행 지연이면 판테온/나보나 중 하나만", "저녁은 숙소 근처 검증 식당으로 축소"],
    checklist: ["숙소 주소 실제 위치로 교체", "유심/eSIM 확인", "첫날 밤 도보 복귀 거리 확인"],
  },
  {
    id: "2026-06-20",
    date: "2026-06-20",
    label: "6/20 토",
    city: "rome",
    title: "고대 로마 + 중심부",
    areaFocus: "콜로세움, 포로 로마노, 몬티",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "colosseum-forum", time: "오전", locked: true },
      { placeId: "caffe-propaganda", note: "체력 회복" },
      { placeId: "trevi-fountain" },
      { placeId: "spanish-steps" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["콜로세움 뒤 피곤하면 트레비만", "스페인 계단은 다른 중심부 날로 이동 가능"],
    checklist: ["콜로세움 예약 QR", "편한 신발", "물과 선크림"],
  },
  {
    id: "2026-06-21",
    date: "2026-06-21",
    label: "6/21 일",
    city: "rome",
    title: "바티칸 + 트라스테베레",
    areaFocus: "바티칸, 산탄젤로, 트라스테베레",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "vatican-museums", time: "예약", locked: true },
      { placeId: "st-peters-basilica" },
      { placeId: "castel-sant-angelo" },
      { placeId: "trastevere", time: "저녁" },
      { placeId: "da-enzo", note: "예약/웨이팅에 따라 Trapizzino 대체" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["바티칸 후 지치면 산탄젤로는 외부만", "트라스테베레 귀가가 부담되면 프라티 저녁으로 교체"],
    checklist: ["바티칸 예약", "성당 복장", "저녁 후 귀가 루트"],
  },
  {
    id: "2026-06-22",
    date: "2026-06-22",
    label: "6/22 월",
    city: "rome",
    title: "중심부 사진 + 맛집",
    areaFocus: "나보나, 판테온, 트레비, 쇼핑",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "piazza-navona" },
      { placeId: "pantheon" },
      { placeId: "armando-al-pantheon", time: "점심", locked: true },
      { placeId: "giolitti" },
      { placeId: "via-del-corso" },
      { placeId: "villa-borghese", time: "해질녘" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["맛집 예약 실패 시 Roscioli/근처 후보로 교체", "더우면 쇼핑 대신 카페 휴식"],
    checklist: ["점심 예약 확인", "쇼핑 예산", "소매치기 많은 중심부 대비"],
  },
  {
    id: "2026-06-23",
    date: "2026-06-23",
    label: "6/23 화",
    city: "rome",
    title: "로마 여유일 + 못 간 곳 회수",
    areaFocus: "트라스테베레, 중심부, 테스타치오 선택",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "campo-de-fiori" },
      { placeId: "roscioli", time: "점심", locked: true },
      { placeId: "trevi-fountain", note: "아침이나 밤 사진 보충" },
      { placeId: "trastevere", time: "저녁 전" },
      { placeId: "trapizzino-trastevere", note: "가볍게 대체 가능" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["체력 아끼기 모드면 중심부 카페와 쇼핑만", "테스타치오 저녁은 이동 부담이 작을 때만"],
    checklist: ["다음날 기차 시간", "짐 정리", "피렌체 숙소 체크인 시간"],
  },
  {
    id: "2026-06-24",
    date: "2026-06-24",
    label: "6/24 수",
    city: "florence",
    title: "로마에서 피렌체 이동",
    areaFocus: "테르미니, SMN, 아르노 강변",
    route: [
      { placeId: "rome-hotel", time: "체크아웃", locked: true },
      { placeId: "roma-termini", time: "기차", locked: true },
      { placeId: "santa-maria-novella", time: "도착", locked: true },
      { placeId: "florence-hotel", time: "체크인", locked: true },
      { placeId: "ponte-vecchio", time: "해질녘" },
      { placeId: "piazzale-michelangelo", note: "체력과 날씨 보고" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["도착이 늦으면 베키오 다리만", "캐리어 피로가 크면 미켈란젤로 광장은 다른 날"],
    checklist: ["기차 QR", "플랫폼 확인", "피렌체 숙소 위치 교체"],
  },
  {
    id: "2026-06-25",
    date: "2026-06-25",
    label: "6/25 목",
    city: "florence",
    title: "두오모 + 아카데미아",
    areaFocus: "두오모, 산 로렌초, 레푸블리카",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "duomo-florence", time: "오전", locked: true },
      { placeId: "accademia", time: "예약", locked: true },
      { placeId: "mercato-centrale", time: "점심" },
      { placeId: "caffe-gilli" },
      { placeId: "officina-profumo" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["두오모 등반이 힘들면 외부/성당 중심", "아카데미아 예약이 안 맞으면 다음날로 이동"],
    checklist: ["두오모 예약", "아카데미아 예약", "성당 복장"],
  },
  {
    id: "2026-06-26",
    date: "2026-06-26",
    label: "6/26 금",
    city: "florence",
    title: "우피치 + 강변",
    areaFocus: "시뇨리아, 우피치, 베키오 다리",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "piazza-signoria" },
      { placeId: "uffizi", time: "예약", locked: true },
      { placeId: "gelateria-dei-neri" },
      { placeId: "ponte-vecchio" },
      { placeId: "la-giostra", time: "저녁", locked: true },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["우피치 후 지치면 산타 크로체 제외", "저녁 예약 실패 시 Santo Spirito 권역으로 전환"],
    checklist: ["우피치 예약", "미술관 볼 작품 목록", "저녁 예약"],
  },
  {
    id: "2026-06-27",
    date: "2026-06-27",
    label: "6/27 토",
    city: "florence",
    title: "올트라르노 + 전망",
    areaFocus: "피티, 보볼리, 산토 스피리토, 미켈란젤로 광장",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "pitti-boboli" },
      { placeId: "osteria-santo-spirito", time: "점심 또는 저녁" },
      { placeId: "piazzale-michelangelo", time: "해질녘" },
      { placeId: "ponte-vecchio", note: "야경 산책" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["더우면 피티/보볼리 대신 실내와 카페", "비 오면 미켈란젤로 광장 제외"],
    checklist: ["일몰 시간 확인", "귀가 교통", "편한 신발"],
  },
  {
    id: "2026-06-28",
    date: "2026-06-28",
    label: "6/28 일",
    city: "florence",
    title: "출국/이동 전 버퍼",
    areaFocus: "숙소 주변, 역, 못 간 곳 회수",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "officina-profumo", note: "선물 회수" },
      { placeId: "mercato-centrale", note: "가벼운 식사" },
      { placeId: "santa-maria-novella", time: "이동", locked: true },
    ],
    fallback: ["출발 시간이 빠르면 숙소-역만", "시간이 남으면 두오모 외부 사진 보충"],
    checklist: ["체크아웃 시간", "짐 보관", "공항/다음 도시 이동 루트"],
  },
];

export const phraseGroups: PhraseGroup[] = [
  {
    title: "식당",
    lines: [
      { ko: "예약했어요.", it: "Abbiamo una prenotazione.", sound: "아비아모 우나 프레노타치오네" },
      { ko: "두 명이에요.", it: "Siamo in due.", sound: "시아모 인 두에" },
      { ko: "추천 메뉴가 뭐예요?", it: "Che cosa ci consiglia?", sound: "케 코자 치 콘실리아" },
      { ko: "계산서 주세요.", it: "Il conto, per favore.", sound: "일 콘토, 페르 파보레" },
      { ko: "물은 탄산 없는 걸로 주세요.", it: "Acqua naturale, per favore.", sound: "아쿠아 나투랄레, 페르 파보레" },
    ],
  },
  {
    title: "길찾기",
    lines: [
      { ko: "여기까지 걸어갈 수 있나요?", it: "Possiamo andarci a piedi?", sound: "포시아모 안다르치 아 피에디" },
      { ko: "이 주소로 가 주세요.", it: "A questo indirizzo, per favore.", sound: "아 퀘스토 인디리초, 페르 파보레" },
      { ko: "택시 정류장이 어디예요?", it: "Dov'e la fermata dei taxi?", sound: "도베 라 페르마타 데이 탁시" },
      { ko: "역이 어디예요?", it: "Dov'e la stazione?", sound: "도베 라 스타치오네" },
    ],
  },
  {
    title: "쇼핑/카페",
    lines: [
      { ko: "이거 얼마예요?", it: "Quanto costa?", sound: "콴토 코스타" },
      { ko: "카드 결제 되나요?", it: "Posso pagare con carta?", sound: "포소 파가레 콘 카르타" },
      { ko: "영수증 주세요.", it: "Lo scontrino, per favore.", sound: "로 스콘트리노, 페르 파보레" },
      { ko: "포장해 주세요.", it: "Da portare via, per favore.", sound: "다 포르타레 비아, 페르 파보레" },
    ],
  },
  {
    title: "긴급",
    lines: [
      { ko: "도와주세요.", it: "Mi aiuti, per favore.", sound: "미 아이우티, 페르 파보레" },
      { ko: "경찰을 불러 주세요.", it: "Chiami la polizia, per favore.", sound: "키아미 라 폴리치아, 페르 파보레" },
      { ko: "약국이 필요해요.", it: "Ho bisogno di una farmacia.", sound: "오 비조뇨 디 우나 파르마치아" },
      { ko: "가방을 잃어버렸어요.", it: "Ho perso la borsa.", sound: "오 페르소 라 보르사" },
    ],
  },
];

export const safetyNotes = [
  {
    title: "소매치기 밀도 높은 구간",
    detail: "역, 지하철, 주요 광장, 분수 앞, 박물관 줄, 붐비는 다리에서는 휴대폰과 가방을 몸 앞쪽으로 둔다.",
    severity: "높음",
  },
  {
    title: "밤 이동 기준",
    detail: "밤에는 외진 골목 산책보다 밝은 큰 길, 검증된 택시, 숙소 복귀 버튼을 우선한다.",
    severity: "높음",
  },
  {
    title: "호객/팔찌/사진 접근",
    detail: "무료처럼 접근해도 응대하지 않고 손을 내밀지 않는다. 사진 찍어준다는 제안도 피한다.",
    severity: "중간",
  },
  {
    title: "성당 복장",
    detail: "어깨와 무릎 노출을 줄이고, 얇은 셔츠나 스카프를 챙긴다.",
    severity: "중간",
  },
  {
    title: "식당 체크",
    detail: "광장 바로 앞 식당은 후기, 메뉴판 가격, coperto 포함 여부를 확인한다.",
    severity: "중간",
  },
];

export const packingChecklist = [
  "여권/카드 분산 보관",
  "eSIM 또는 로밍",
  "보조배터리",
  "편한 신발",
  "얇은 셔츠/스카프",
  "지퍼 있는 크로스백",
  "기차/미술관 QR 오프라인 저장",
  "숙소 주소 이탈리아어 캡처",
  "상비약/생리용품",
  "물병과 선크림",
];

export const sources: Source[] = [
  {
    id: "turismo-roma",
    label: "Turismo Roma",
    url: "https://www.turismoroma.it/en",
    note: "로마 공식 관광 정보와 권역/명소 확인용.",
  },
  {
    id: "colosseum-official",
    label: "Parco archeologico del Colosseo",
    url: "https://colosseo.it/en/",
    note: "콜로세움, 포로 로마노, 팔라티노 공식 예약 확인용.",
  },
  {
    id: "pantheon-official",
    label: "Pantheon Roma",
    url: "https://www.pantheonroma.com/",
    note: "판테온 입장/예약 확인용.",
  },
  {
    id: "vatican-museums",
    label: "Vatican Museums",
    url: "https://www.museivaticani.va/content/museivaticani/en.html",
    note: "바티칸 박물관 공식 예약 확인용.",
  },
  {
    id: "vatican-official",
    label: "Vatican Basilica",
    url: "https://www.basilicasanpietro.va/en.html",
    note: "성 베드로 대성당 공식 정보 확인용.",
  },
  {
    id: "feelflorence",
    label: "Feel Florence",
    url: "https://www.feelflorence.it/en",
    note: "피렌체 공식 관광 정보 확인용.",
  },
  {
    id: "duomo-official",
    label: "Opera di Santa Maria del Fiore",
    url: "https://duomo.firenze.it/en/home",
    note: "피렌체 두오모 예약/입장 확인용.",
  },
  {
    id: "uffizi-official",
    label: "Uffizi Galleries",
    url: "https://www.uffizi.it/en",
    note: "우피치, 피티, 보볼리 공식 예약 확인용.",
  },
  {
    id: "accademia-official",
    label: "Galleria dell'Accademia di Firenze",
    url: "https://www.galleriaaccademiafirenze.it/en/",
    note: "아카데미아 공식 정보 확인용.",
  },
  {
    id: "state-italy",
    label: "U.S. State Department Italy Travel",
    url: "https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Italy.html",
    note: "관광지 절도와 안전 경보 확인용.",
  },
  {
    id: "canada-italy",
    label: "Government of Canada Italy Travel Advice",
    url: "https://travel.gc.ca/destinations/italy",
    note: "소매치기, 역/대중교통 주의사항 교차 확인용.",
  },
  {
    id: "trenitalia",
    label: "Trenitalia",
    url: "https://www.trenitalia.com/en.html",
    note: "로마-피렌체 기차 시간/표 확인용.",
  },
  {
    id: "italo",
    label: "Italo",
    url: "https://www.italotreno.com/en",
    note: "로마-피렌체 기차 대안 확인용.",
  },
  {
    id: "restaurant-official",
    label: "Restaurant official channels",
    url: "https://www.google.com/maps",
    note: "식당 영업시간과 예약은 공식 웹사이트/Google Maps에서 최종 확인.",
  },
];
