import type { Place, Source } from "./data";

export const extraPlaces: Place[] = [
  {
    id: "borghese-gallery",
    city: "rome",
    name: "Borghese Gallery",
    koName: "보르게세 미술관",
    category: "attraction",
    area: "보르게세",
    lat: 41.9142,
    lng: 12.4922,
    priority: 1,
    rank: 91,
    durationMin: 120,
    reservation: "필수",
    bestTime: "예약 시간 기준",
    price: "높음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["예약", "실내", "미술관", "체력아낌"],
    why: "로마에서 미술관 하나만 제대로 넣는다면 강한 후보. 예약 시간만 맞으면 동선이 깔끔하다.",
    tips: ["입장 시간이 엄격한 편이라 20분 전 도착", "공원 산책과 묶기", "바티칸과 같은 날은 과하다"],
    koreanTips: ["더위가 심한 날 실내 코스로 좋음", "작품 설명을 미리 저장하면 만족도가 크게 올라감"],
    watchOut: ["예약 매진 여부 확인", "큰 가방 보관 규정 확인"],
    pairWith: ["villa-borghese", "spanish-steps"],
    sourceIds: ["lonely-planet-rome", "turismo-roma"],
  },
  {
    id: "piazza-del-popolo",
    city: "rome",
    name: "Piazza del Popolo",
    koName: "포폴로 광장",
    category: "attraction",
    area: "보르게세/북쪽 중심부",
    lat: 41.9109,
    lng: 12.4764,
    priority: 2,
    rank: 73,
    durationMin: 30,
    reservation: "불필요",
    bestTime: "오전 또는 해질녘",
    price: "무료",
    safety: "주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["사진", "산책", "중심동선"],
    why: "스페인 계단, 핀초 언덕, 쇼핑 거리 사이를 부드럽게 이어주는 광장.",
    tips: ["핀초 언덕 전망과 묶기", "광장 공연 주변 소지품 주의", "짧은 산책 코스로 충분"],
    koreanTips: ["사진 욕심 있으면 스페인 계단보다 덜 답답한 후보"],
    watchOut: ["붐비는 시간 휴대폰 주의"],
    pairWith: ["villa-borghese", "spanish-steps", "via-del-corso"],
    sourceIds: ["timeout-rome", "lonely-planet-rome"],
  },
  {
    id: "capitoline-museums",
    city: "rome",
    name: "Capitoline Museums",
    koName: "카피톨리니 미술관",
    category: "attraction",
    area: "고대 로마/베네치아 광장",
    lat: 41.8933,
    lng: 12.4828,
    priority: 2,
    rank: 80,
    durationMin: 120,
    reservation: "권장",
    bestTime: "오후 또는 비 오는 날",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["실내", "미술관", "비오는날"],
    why: "콜로세움 권역에서 실내로 전환할 때 가장 안정적인 대체 코스.",
    tips: ["콜로세움 뒤 체력이 남으면", "비 오는 날 대체", "베네치아 광장 전망과 연결"],
    koreanTips: ["한낮 더위 피하기 좋음", "사진보다 관람형이라 컨디션 좋을 때"],
    watchOut: ["고대 로마 하루에 박물관까지 넣으면 피곤할 수 있음"],
    pairWith: ["colosseum-forum", "altare-patria", "galleria-doria-pamphilj"],
    sourceIds: ["turismo-roma", "lonely-planet-rome"],
  },
  {
    id: "altare-patria",
    city: "rome",
    name: "Altare della Patria",
    koName: "비토리오 에마누엘레 2세 기념관",
    category: "view",
    area: "베네치아 광장",
    lat: 41.8958,
    lng: 12.4823,
    priority: 2,
    rank: 75,
    durationMin: 50,
    reservation: "확인",
    bestTime: "해질녘 전",
    price: "확인",
    safety: "주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["전망", "사진", "중심동선"],
    why: "중심부와 고대 로마 사이에서 전망을 넣고 싶을 때 효율적이다.",
    tips: ["엘리베이터 전망대 여부 확인", "베네치아 광장 횡단 주의", "콜로세움 전후 연결"],
    koreanTips: ["로마 시내 전경 사진용으로 좋음", "입장 시간이 애매하면 외부만 봐도 충분"],
    watchOut: ["광장 주변 차와 혼잡"],
    pairWith: ["capitoline-museums", "colosseum-forum", "galleria-doria-pamphilj"],
    sourceIds: ["turismo-roma", "timeout-rome"],
  },
  {
    id: "santa-maria-maggiore",
    city: "rome",
    name: "Basilica di Santa Maria Maggiore",
    koName: "산타 마리아 마조레 대성당",
    category: "attraction",
    area: "Termini/Monti",
    lat: 41.8976,
    lng: 12.4985,
    priority: 2,
    rank: 74,
    durationMin: 45,
    reservation: "확인",
    bestTime: "오전 또는 이동 전후",
    price: "확인",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["성당", "실내", "역근처", "복장"],
    why: "테르미니 근처 시간이 남을 때 짧게 넣기 좋은 대성당.",
    tips: ["복장 체크", "역 주변 소지품 주의", "몬티 권역과 묶기"],
    koreanTips: ["기차 전후 애매한 시간을 메우기 좋음"],
    watchOut: ["테르미니 주변 늦은 밤 도보 이동"],
    pairWith: ["roma-termini", "monti", "regoli"],
    sourceIds: ["turismo-roma", "lonely-planet-rome"],
  },
  {
    id: "basilica-san-clemente",
    city: "rome",
    name: "Basilica di San Clemente",
    koName: "산 클레멘테 성당",
    category: "attraction",
    area: "고대 로마",
    lat: 41.8899,
    lng: 12.4974,
    priority: 2,
    rank: 72,
    durationMin: 55,
    reservation: "확인",
    bestTime: "콜로세움 전후",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["성당", "실내", "역사"],
    why: "콜로세움 근처에서 덜 붐비는 역사형 실내 코스.",
    tips: ["지하 유적 관람 여부 확인", "콜로세움 뒤 체력 있을 때", "사진보다 설명형 코스"],
    koreanTips: ["유명 랜드마크 위주 여행이면 우선순위는 낮춰도 됨"],
    watchOut: ["동행 둘 다 역사 취향일 때만"],
    pairWith: ["colosseum-forum", "caffe-propaganda"],
    sourceIds: ["lonely-planet-rome"],
  },
  {
    id: "baths-caracalla",
    city: "rome",
    name: "Baths of Caracalla",
    koName: "카라칼라 욕장",
    category: "attraction",
    area: "남쪽 고대 로마",
    lat: 41.8790,
    lng: 12.4923,
    priority: 2,
    rank: 70,
    durationMin: 75,
    reservation: "권장",
    bestTime: "오전",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 2,
    tags: ["유적", "사진", "덜붐빔"],
    why: "콜로세움보다 한적한 고대 유적 사진을 원할 때 좋은 확장 코스.",
    tips: ["한낮 더위 피하기", "콜로세움과 같은 날이면 이동 부담 계산", "햇빛 대비"],
    koreanTips: ["인파 적은 유적 사진을 원하면 만족도 높음"],
    watchOut: ["그늘 적음", "대중교통/택시 동선 확인"],
    pairWith: ["orange-garden", "colosseum-forum"],
    sourceIds: ["timeout-rome", "lonely-planet-rome"],
  },
  {
    id: "orange-garden",
    city: "rome",
    name: "Giardino degli Aranci",
    koName: "오렌지 정원",
    category: "view",
    area: "아벤티노",
    lat: 41.8840,
    lng: 12.4805,
    priority: 2,
    rank: 76,
    durationMin: 40,
    reservation: "불필요",
    bestTime: "해질녘",
    price: "무료",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["전망", "사진", "휴식", "해질녘"],
    why: "중심부에서 살짝 벗어나 조용한 전망과 휴식을 넣을 수 있다.",
    tips: ["해진 뒤 복귀 경로 확인", "진실의 입/테베레섬과 묶기", "사진은 난간 쪽"],
    koreanTips: ["사람 많은 스팟에 지쳤을 때 만족도 좋음"],
    watchOut: ["밤 늦게 오래 머무르지 않기"],
    pairWith: ["tiber-island", "baths-caracalla"],
    sourceIds: ["timeout-rome", "lonely-planet-rome"],
  },
  {
    id: "janiculum-terrace",
    city: "rome",
    name: "Janiculum Terrace",
    koName: "자니콜로 언덕",
    category: "view",
    area: "트라스테베레/전망",
    lat: 41.8919,
    lng: 12.4616,
    priority: 2,
    rank: 74,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "해질녘",
    price: "무료",
    safety: "밤주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["전망", "사진", "택시검토", "해질녘"],
    why: "트라스테베레 저녁 전에 로마 전경을 넣고 싶을 때.",
    tips: ["오르막이 있어 체력 체크", "해진 뒤 택시/버스 경로 확인", "트라스테베레 식당 예약과 연결"],
    koreanTips: ["예쁜 사진 욕심이면 좋지만 피곤하면 과감히 제외"],
    watchOut: ["밤 복귀", "구두/불편한 신발"],
    pairWith: ["trastevere", "da-enzo", "la-tavernaccia"],
    sourceIds: ["timeout-rome"],
  },
  {
    id: "tiber-island",
    city: "rome",
    name: "Tiber Island",
    koName: "테베레섬",
    category: "attraction",
    area: "강변/유대인 지구",
    lat: 41.8919,
    lng: 12.4786,
    priority: 2,
    rank: 68,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "저녁 전 산책",
    price: "무료",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["산책", "강변", "트라스테베레연결"],
    why: "중심부에서 트라스테베레로 넘어갈 때 자연스럽게 끼우는 짧은 산책 포인트.",
    tips: ["다리 위 사진", "비 오면 스킵", "유대인 지구와 연결"],
    koreanTips: ["동선 연결용이라 일부러 오래 잡지 않기"],
    watchOut: ["강변 아래 외진 곳은 늦은 밤 피하기"],
    pairWith: ["jewish-ghetto", "trastevere", "orange-garden"],
    sourceIds: ["turismo-roma"],
  },
  {
    id: "jewish-ghetto",
    city: "rome",
    name: "Jewish Ghetto",
    koName: "로마 유대인 지구",
    category: "attraction",
    area: "유대인 지구",
    lat: 41.8923,
    lng: 12.4772,
    priority: 2,
    rank: 72,
    durationMin: 55,
    reservation: "불필요",
    bestTime: "점심 또는 저녁 전",
    price: "무료",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["산책", "음식", "강변"],
    why: "중심부와 강변 사이에서 식사/산책을 같이 해결할 수 있는 권역.",
    tips: ["아티초크 메뉴 후보", "테베레섬과 묶기", "식당 가격 확인"],
    koreanTips: ["로마 음식이 느끼할 때 색다른 메뉴를 넣기 좋음"],
    watchOut: ["인기 식당은 예약/웨이팅 확인"],
    pairWith: ["tiber-island", "campo-de-fiori", "forno-campo-de-fiori"],
    sourceIds: ["eater-rome", "lonely-planet-rome"],
  },
  {
    id: "largo-argentina",
    city: "rome",
    name: "Largo di Torre Argentina",
    koName: "라르고 디 토레 아르젠티나",
    category: "attraction",
    area: "중심부",
    lat: 41.8955,
    lng: 12.4769,
    priority: 2,
    rank: 65,
    durationMin: 20,
    reservation: "확인",
    bestTime: "이동 중",
    price: "확인",
    safety: "주의",
    photo: 1,
    girlsTripFit: 2,
    tags: ["짧게", "중심동선", "고양이"],
    why: "판테온, 캄포 데 피오리, 유대인 지구 사이에서 짧게 보는 유적.",
    tips: ["시간 남을 때만", "교차로 주변 주의", "내부 관람 가능 여부 확인"],
    koreanTips: ["일부러 멀리서 갈 정도는 아니고 근처면 체크"],
    watchOut: ["차량 많은 교차로"],
    pairWith: ["pantheon", "campo-de-fiori", "jewish-ghetto"],
    sourceIds: ["turismo-roma"],
  },
  {
    id: "monti",
    city: "rome",
    name: "Monti",
    koName: "몬티 지구",
    category: "shopping",
    area: "Monti",
    lat: 41.8955,
    lng: 12.4927,
    priority: 2,
    rank: 78,
    durationMin: 75,
    reservation: "불필요",
    bestTime: "오후",
    price: "확인",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["소품샵", "빈티지", "카페", "한국인선호"],
    why: "콜로세움 이후 너무 유적만 보는 흐름을 카페/소품샵으로 바꿔주는 권역.",
    tips: ["골목 쇼핑은 낮~저녁 전", "카페 휴식과 묶기", "콜로세움 후 체력 회복"],
    koreanTips: ["소품샵, 빈티지, 카페 좋아하면 만족도 높음", "사진보다 분위기형 권역"],
    watchOut: ["가게별 휴무 확인"],
    pairWith: ["colosseum-forum", "fatamorgana-monti", "santa-maria-maggiore"],
    sourceIds: ["lonely-planet-rome", "timeout-rome"],
  },
  {
    id: "testaccio-market",
    city: "rome",
    name: "Mercato Testaccio",
    koName: "테스타치오 시장",
    category: "food",
    area: "Testaccio",
    lat: 41.8766,
    lng: 12.4756,
    priority: 2,
    rank: 76,
    durationMin: 70,
    reservation: "불필요",
    bestTime: "점심",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["시장", "가성비", "점심", "한국인선호"],
    why: "식당 예약 없이 로마식 간단식을 여러 개 맛보기 좋은 점심 후보.",
    tips: ["영업시간 확인", "현금/카드 둘 다 준비", "테스타치오까지 이동시간 계산"],
    koreanTips: ["한 끼를 가볍게 여러 메뉴로 먹고 싶을 때 좋음", "웨이팅 스트레스 낮음"],
    menuHints: ["trapizzino", "suppli", "panino", "espresso"],
    watchOut: ["저녁 코스로 잡지 않기"],
    pairWith: ["felice-testaccio", "piatto-romano", "trattoria-trecca"],
    sourceIds: ["eater-rome", "katie-parla-rome"],
  },
  {
    id: "mercato-trionfale",
    city: "rome",
    name: "Mercato Trionfale",
    koName: "메르카토 트리온팔레",
    category: "food",
    area: "바티칸/프라티",
    lat: 41.9083,
    lng: 12.4538,
    priority: 2,
    rank: 68,
    durationMin: 45,
    reservation: "불필요",
    bestTime: "바티칸 전후 낮 시간",
    price: "낮음",
    safety: "주의",
    photo: 1,
    girlsTripFit: 2,
    tags: ["시장", "바티칸근처", "간식"],
    why: "바티칸 권역에서 식당 예약이 애매할 때 쓰는 낮 시간 후보.",
    tips: ["영업시간 확인", "가볍게 먹기", "시장 혼잡 소지품 주의"],
    koreanTips: ["바티칸 후 식당 찾기 귀찮을 때 대안"],
    watchOut: ["늦은 오후/저녁은 부적합"],
    pairWith: ["vatican-museums", "st-peters-basilica"],
    sourceIds: ["eater-rome", "katie-parla-rome"],
  },
  {
    id: "santa-maria-trastevere",
    city: "rome",
    name: "Basilica di Santa Maria in Trastevere",
    koName: "산타 마리아 인 트라스테베레 성당",
    category: "attraction",
    area: "트라스테베레",
    lat: 41.8895,
    lng: 12.4709,
    priority: 2,
    rank: 73,
    durationMin: 35,
    reservation: "확인",
    bestTime: "저녁 전",
    price: "확인",
    safety: "밤주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["성당", "트라스테베레", "복장"],
    why: "트라스테베레 산책의 중심점을 잡아주는 짧은 실내 코스.",
    tips: ["저녁 식당 예약 전후", "광장 분위기 보기", "복장 체크"],
    koreanTips: ["트라스테베레에서 길 잃지 않게 기준점으로 쓰기 좋음"],
    watchOut: ["늦은 밤 외진 골목으로 빠지지 않기"],
    pairWith: ["trastevere", "da-enzo", "trapizzino-trastevere"],
    sourceIds: ["turismo-roma", "lonely-planet-rome"],
  },
  {
    id: "galleria-doria-pamphilj",
    city: "rome",
    name: "Galleria Doria Pamphilj",
    koName: "도리아 팜필리 미술관",
    category: "attraction",
    area: "중심부",
    lat: 41.8978,
    lng: 12.4817,
    priority: 2,
    rank: 76,
    durationMin: 80,
    reservation: "권장",
    bestTime: "오후 또는 비 오는 날",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["실내", "미술관", "비오는날", "중심동선"],
    why: "판테온/트레비 근처에서 비나 더위가 심할 때 넣기 좋은 미술관.",
    tips: ["중심부 일정의 대체 카드", "관람 후 트레비/판테온 연결", "오디오가이드 확인"],
    koreanTips: ["사진 스팟보다 분위기형 실내 관람"],
    watchOut: ["미술관 취향 아니면 스킵"],
    pairWith: ["pantheon", "trevi-fountain", "altare-patria"],
    sourceIds: ["timeout-rome", "lonely-planet-rome"],
  },
  {
    id: "palazzo-barberini",
    city: "rome",
    name: "Palazzo Barberini",
    koName: "바르베리니 궁전",
    category: "attraction",
    area: "바르베리니/트레비",
    lat: 41.9030,
    lng: 12.4890,
    priority: 2,
    rank: 72,
    durationMin: 85,
    reservation: "권장",
    bestTime: "오후",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["실내", "미술관", "트레비근처"],
    why: "트레비와 스페인 계단 사이에서 실내 관람을 넣는 선택지.",
    tips: ["한낮 더위 대피", "관람 시간은 짧게 잡아도 됨", "트레비와 연결"],
    koreanTips: ["중심부 걷다가 지치면 실내로 전환"],
    watchOut: ["예약/휴관일 확인"],
    pairWith: ["trevi-fountain", "spanish-steps"],
    sourceIds: ["turismo-roma", "lonely-planet-rome"],
  },
  {
    id: "via-condotti",
    city: "rome",
    name: "Via dei Condotti",
    koName: "콘도티 거리",
    category: "shopping",
    area: "스페인 광장",
    lat: 41.9057,
    lng: 12.4805,
    priority: 2,
    rank: 70,
    durationMin: 45,
    reservation: "불필요",
    bestTime: "오후",
    price: "확인",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["쇼핑", "명품", "한국인선호", "혼잡"],
    why: "스페인 계단과 함께 짧게 둘러보기 좋은 쇼핑 거리.",
    tips: ["쇼핑백 노출 줄이기", "택스리펀 서류 확인", "붐비면 오래 머물지 않기"],
    koreanTips: ["명품/코스메틱 쇼핑 계획이 있으면 지도에 고정", "여권 원본 휴대 여부는 매장 정책 확인"],
    watchOut: ["소매치기", "쇼핑 후 밤 도보 이동"],
    pairWith: ["spanish-steps", "via-del-corso", "antico-caffe-greco"],
    sourceIds: ["timeout-rome"],
  },
  {
    id: "rinascente-rome-rooftop",
    city: "rome",
    name: "Rinascente Roma Tritone Rooftop",
    koName: "리나센테 로마 루프탑",
    category: "view",
    area: "트레비/쇼핑",
    lat: 41.9021,
    lng: 12.4826,
    priority: 2,
    rank: 67,
    durationMin: 45,
    reservation: "확인",
    bestTime: "오후 휴식",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["쇼핑", "휴식", "전망", "화장실"],
    why: "쇼핑, 화장실, 카페 휴식을 한 번에 해결하는 실전형 스팟.",
    tips: ["비상 화장실/휴식 후보", "쇼핑 전후 동선", "가격대 확인"],
    koreanTips: ["걷다가 지쳤을 때 한국 백화점처럼 쓰기 좋음", "화장실/에어컨/휴식 포인트"],
    watchOut: ["식음료 가격대"],
    pairWith: ["trevi-fountain", "via-del-corso", "spanish-steps"],
    sourceIds: ["timeout-rome"],
  },
  {
    id: "bonci-pizzarium",
    city: "rome",
    name: "Bonci Pizzarium",
    koName: "Bonci Pizzarium",
    category: "food",
    area: "바티칸/치프로",
    lat: 41.9084,
    lng: 12.4457,
    priority: 1,
    rank: 86,
    durationMin: 45,
    reservation: "불필요",
    bestTime: "바티칸 전후 간단식",
    price: "중간",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["피자", "간단식사", "바티칸근처", "한국인선호"],
    why: "바티칸 권역에서 유명도와 실전성이 모두 있는 피자 알 taglio 후보.",
    tips: ["무게로 계산하는 방식 이해", "줄이 길면 다른 후보로 전환", "서서/가볍게 먹는 플랜"],
    koreanTips: ["둘이 여러 조각 나눠 먹기 좋음", "한 끼를 무겁게 먹기 싫을 때"],
    menuHints: ["pizza al taglio", "mortadella", "seasonal toppings"],
    watchOut: ["피크 시간 웨이팅", "좌석 기대 낮추기"],
    pairWith: ["vatican-museums", "mercato-trionfale"],
    sourceIds: ["eater-rome", "infatuation-rome", "katie-parla-rome"],
  },
  {
    id: "supplizio",
    city: "rome",
    name: "Supplizio",
    koName: "Supplizio",
    category: "food",
    area: "중심부/나보나",
    lat: 41.8965,
    lng: 12.4716,
    priority: 2,
    rank: 75,
    durationMin: 30,
    reservation: "불필요",
    bestTime: "간식",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["간식", "가성비", "중심부", "한국인선호"],
    why: "중심부에서 식사 사이에 로마식 튀김 간식을 넣기 좋은 후보.",
    tips: ["점심/저녁 사이 간식", "나보나와 묶기", "느끼하면 둘이 나눠 먹기"],
    koreanTips: ["한국인 입맛에 익숙한 튀김 느낌이라 실패 확률 낮음"],
    menuHints: ["suppli classico", "crocchetta"],
    watchOut: ["식사 직전 과식 금지"],
    pairWith: ["piazza-navona", "campo-de-fiori", "pantheon"],
    sourceIds: ["eater-rome", "katie-parla-rome"],
  },
  {
    id: "forno-campo-de-fiori",
    city: "rome",
    name: "Forno Campo de' Fiori",
    koName: "Forno Campo de' Fiori",
    category: "food",
    area: "캄포 데 피오리",
    lat: 41.8955,
    lng: 12.4717,
    priority: 2,
    rank: 78,
    durationMin: 30,
    reservation: "불필요",
    bestTime: "아침 또는 간식",
    price: "낮음",
    safety: "주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["빵", "피자", "가성비", "간단식사"],
    why: "시장 권역에서 빠르게 먹고 이동하기 좋은 베이커리/피자 후보.",
    tips: ["무게 계산 방식 확인", "시장과 묶기", "서서 먹는 플랜"],
    koreanTips: ["식당 예약 전 배고플 때 비상 간식"],
    menuHints: ["pizza bianca", "pizza rossa", "mortadella"],
    watchOut: ["혼잡 시 소지품 주의"],
    pairWith: ["campo-de-fiori", "roscioli", "jewish-ghetto"],
    sourceIds: ["eater-rome", "katie-parla-rome"],
  },
  {
    id: "trattoria-trecca",
    city: "rome",
    name: "Trattoria Trecca",
    koName: "Trattoria Trecca",
    category: "food",
    area: "Ostiense/Testaccio",
    lat: 41.8706,
    lng: 12.4846,
    priority: 2,
    rank: 82,
    durationMin: 90,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "밤주의",
    photo: 1,
    girlsTripFit: 2,
    tags: ["로마음식", "예약권장", "현지식"],
    why: "중심부를 벗어난 로마 음식 후보. 음식 우선 모드일 때 넣는다.",
    tips: ["택시/대중교통 복귀 확인", "식당 위주 날에만", "예약 확인"],
    koreanTips: ["맛집 욕심이 강한 날에만, 동선 효율은 낮음"],
    menuHints: ["pasta romana", "offal dishes", "seasonal specials"],
    watchOut: ["늦은 밤 복귀", "내장류 취향"],
    pairWith: ["testaccio-market", "felice-testaccio", "piatto-romano"],
    sourceIds: ["infatuation-rome", "cntraveler-rome"],
  },
  {
    id: "la-tavernaccia",
    city: "rome",
    name: "La Tavernaccia Da Bruno",
    koName: "La Tavernaccia Da Bruno",
    category: "food",
    area: "트라스테베레",
    lat: 41.8795,
    lng: 12.4674,
    priority: 2,
    rank: 84,
    durationMin: 100,
    reservation: "권장",
    bestTime: "점심 또는 이른 저녁",
    price: "중간",
    safety: "밤주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["트라스테베레", "로마음식", "예약권장"],
    why: "트라스테베레에서 Da Enzo 외에 강한 식사 대안으로 쓰기 좋다.",
    tips: ["트라스테베레 남쪽이라 복귀 경로 확인", "예약 권장", "무거운 저녁 전후 일정 줄이기"],
    koreanTips: ["Da Enzo 웨이팅이 싫으면 대안으로 고려"],
    menuHints: ["maialino", "parmigiana", "roman classics"],
    watchOut: ["중심부에서 도보 왕복은 길 수 있음"],
    pairWith: ["trastevere", "janiculum-terrace"],
    sourceIds: ["infatuation-rome", "eater-rome"],
  },
  {
    id: "piatto-romano",
    city: "rome",
    name: "Piatto Romano",
    koName: "Piatto Romano",
    category: "food",
    area: "Testaccio",
    lat: 41.8764,
    lng: 12.4764,
    priority: 2,
    rank: 80,
    durationMin: 90,
    reservation: "권장",
    bestTime: "점심 또는 저녁",
    price: "중간",
    safety: "밤주의",
    photo: 1,
    girlsTripFit: 2,
    tags: ["로마음식", "테스타치오", "현지식"],
    why: "테스타치오 권역에서 전통 로마 음식을 먹고 싶을 때.",
    tips: ["테스타치오 일정과 묶기", "예약 확인", "늦으면 택시"],
    koreanTips: ["중심부 맛집보다 로컬 느낌을 원할 때"],
    menuHints: ["cacio e pepe", "seasonal vegetables", "roman classics"],
    watchOut: ["동선 효율 낮음"],
    pairWith: ["testaccio-market", "felice-testaccio"],
    sourceIds: ["eater-rome", "cntraveler-rome"],
  },
  {
    id: "hosteria-grappolo-doro",
    city: "rome",
    name: "Hosteria Grappolo d'Oro",
    koName: "Hosteria Grappolo d'Oro",
    category: "food",
    area: "캄포 데 피오리",
    lat: 41.8951,
    lng: 12.4756,
    priority: 2,
    rank: 79,
    durationMin: 90,
    reservation: "권장",
    bestTime: "점심 또는 저녁",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["로마음식", "중심부", "예약권장"],
    why: "중심부에서 로마식 코스/전통식을 안정적으로 넣는 식당 후보.",
    tips: ["판테온/캄포 데 피오리 연결", "예약 확인", "메뉴 가격 확인"],
    koreanTips: ["첫 로마식 식사로 무난한 후보"],
    menuHints: ["cacio e pepe", "amatriciana", "roman tasting"],
    watchOut: ["관광지 권역이라 예약과 후기 재확인"],
    pairWith: ["pantheon", "campo-de-fiori", "piazza-navona"],
    sourceIds: ["eater-rome"],
  },
  {
    id: "emma-pizzeria",
    city: "rome",
    name: "Emma Pizzeria",
    koName: "Emma Pizzeria",
    category: "food",
    area: "중심부",
    lat: 41.8948,
    lng: 12.4752,
    priority: 2,
    rank: 76,
    durationMin: 75,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["피자", "중심부", "한국인선호"],
    why: "파스타가 이어질 때 피자로 바꾸는 중심부 대안.",
    tips: ["예약 확인", "나눠 먹기 좋음", "판테온/캄포 데 피오리와 묶기"],
    koreanTips: ["둘이 피자+사이드 나눠 먹기 편함"],
    menuHints: ["roman pizza", "suppli", "burrata"],
    watchOut: ["피크 시간 웨이팅"],
    pairWith: ["pantheon", "campo-de-fiori", "roscioli"],
    sourceIds: ["eater-rome", "cntraveler-rome"],
  },
  {
    id: "santo-palato",
    city: "rome",
    name: "SantoPalato",
    koName: "SantoPalato",
    category: "food",
    area: "San Giovanni",
    lat: 41.8829,
    lng: 12.5056,
    priority: 2,
    rank: 82,
    durationMin: 100,
    reservation: "필수",
    bestTime: "저녁",
    price: "중간",
    safety: "밤주의",
    photo: 1,
    girlsTripFit: 2,
    tags: ["예약", "로마음식", "미식"],
    why: "음식 중심 여행자에게 강한 후보지만 동선과 예약 난도가 있다.",
    tips: ["예약 먼저", "밤 귀가 교통 확인", "식당 하나를 위해 움직이는 날에"],
    koreanTips: ["맛집 욕심이 정말 클 때만 넣기", "동선 효율보다 음식 우선"],
    menuHints: ["carbonara", "roman classics", "offal dishes"],
    watchOut: ["예약 난도", "늦은 밤 복귀"],
    pairWith: ["basilica-san-clemente", "colosseum-forum"],
    sourceIds: ["eater-rome", "cntraveler-rome", "infatuation-rome"],
  },
  {
    id: "retrobottega",
    city: "rome",
    name: "Retrobottega",
    koName: "Retrobottega",
    category: "food",
    area: "중심부/나보나",
    lat: 41.8990,
    lng: 12.4748,
    priority: 2,
    rank: 77,
    durationMin: 100,
    reservation: "권장",
    bestTime: "저녁",
    price: "높음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["모던", "예약권장", "분위기"],
    why: "전통 파스타가 이어질 때 분위기 있는 모던 식사로 전환하는 후보.",
    tips: ["예산 확인", "예약 확인", "나보나/판테온 동선"],
    koreanTips: ["생일/기분 내는 저녁 후보로 좋음"],
    menuHints: ["modern tasting", "natural wine"],
    watchOut: ["전통 이탈리아 식당 기대와 다를 수 있음"],
    pairWith: ["piazza-navona", "pantheon"],
    sourceIds: ["eater-rome", "cntraveler-rome"],
  },
  {
    id: "pianostrada",
    city: "rome",
    name: "Pianostrada",
    koName: "Pianostrada",
    category: "food",
    area: "트라스테베레/강변",
    lat: 41.8943,
    lng: 12.4708,
    priority: 2,
    rank: 78,
    durationMin: 85,
    reservation: "권장",
    bestTime: "점심 또는 저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["분위기", "여자여행", "브런치", "한국인선호"],
    why: "둘이 가기 편한 분위기와 가벼운 식사 감각을 동시에 잡는 후보.",
    tips: ["예약 확인", "트라스테베레/나보나 사이 연결", "사진/분위기 우선"],
    koreanTips: ["무거운 전통식보다 예쁘고 편한 식사를 원할 때"],
    menuHints: ["sandwiches", "small plates", "dessert"],
    watchOut: ["정통 로마식 기대면 다른 후보"],
    pairWith: ["piazza-navona", "trastevere", "tiber-island"],
    sourceIds: ["cntraveler-rome", "eater-rome"],
  },
  {
    id: "marigold-roma",
    city: "rome",
    name: "Marigold Roma",
    koName: "Marigold Roma",
    category: "cafe",
    area: "Ostiense",
    lat: 41.8768,
    lng: 12.4829,
    priority: 2,
    rank: 72,
    durationMin: 55,
    reservation: "권장",
    bestTime: "브런치",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["브런치", "카페", "한국인선호", "분위기"],
    why: "이탈리아식만 계속 먹기 힘들 때 브런치로 리듬을 바꾸는 후보.",
    tips: ["중심부에서 거리가 있으니 일부러 가는 날만", "예약 확인", "테스타치오/오스티엔세와 묶기"],
    koreanTips: ["커피+브런치 감성 충전용", "한국 카페 감각에 가까운 휴식"],
    menuHints: ["brunch", "coffee", "pastries"],
    watchOut: ["동선 효율 낮음"],
    pairWith: ["testaccio-market", "trattoria-trecca"],
    sourceIds: ["eater-rome", "cntraveler-rome"],
  },
  {
    id: "gelateria-del-teatro",
    city: "rome",
    name: "Gelateria del Teatro",
    koName: "Gelateria del Teatro",
    category: "cafe",
    area: "나보나/강변",
    lat: 41.9002,
    lng: 12.4689,
    priority: 2,
    rank: 74,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "오후",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["젤라또", "휴식", "한국인선호"],
    why: "나보나에서 강변 쪽으로 걸을 때 넣기 좋은 젤라또 휴식.",
    tips: ["맛 조합 둘이 나눠보기", "나보나/산탄젤로 사이", "혼잡하면 들고 이동"],
    koreanTips: ["짧은 휴식과 사진을 같이 해결"],
    menuHints: ["seasonal fruit", "pistachio", "ricotta"],
    watchOut: ["식사 직전 과식 금지"],
    pairWith: ["piazza-navona", "castel-sant-angelo"],
    sourceIds: ["timeout-rome", "katie-parla-rome"],
  },
  {
    id: "frigidarium",
    city: "rome",
    name: "Frigidarium",
    koName: "Frigidarium",
    category: "cafe",
    area: "나보나",
    lat: 41.8983,
    lng: 12.4718,
    priority: 2,
    rank: 70,
    durationMin: 20,
    reservation: "불필요",
    bestTime: "오후 또는 밤 초반",
    price: "낮음",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["젤라또", "중심부", "간식"],
    why: "나보나 바로 근처에서 빠르게 넣는 젤라또 후보.",
    tips: ["줄이 길면 다른 젤라또로", "밤 늦게 오래 머물지 않기", "광장 소매치기 주의"],
    koreanTips: ["지도에 찍어두고 근처일 때만 사용"],
    menuHints: ["chocolate coating", "pistachio", "fruit"],
    watchOut: ["혼잡"],
    pairWith: ["piazza-navona", "pantheon"],
    sourceIds: ["timeout-rome"],
  },
  {
    id: "fatamorgana-monti",
    city: "rome",
    name: "Fatamorgana Monti",
    koName: "Fatamorgana Monti",
    category: "cafe",
    area: "Monti",
    lat: 41.8944,
    lng: 12.4931,
    priority: 2,
    rank: 68,
    durationMin: 20,
    reservation: "불필요",
    bestTime: "콜로세움 후",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["젤라또", "몬티", "휴식"],
    why: "콜로세움 뒤 몬티 산책으로 전환할 때 쓰는 젤라또 후보.",
    tips: ["몬티 골목 산책과 묶기", "피곤하면 카페로 전환", "맛은 취향껏"],
    koreanTips: ["유적 일정 후 당 보충용"],
    menuHints: ["creative flavors", "pistachio", "fruit"],
    watchOut: ["좌석 기대 낮추기"],
    pairWith: ["monti", "colosseum-forum"],
    sourceIds: ["timeout-rome", "katie-parla-rome"],
  },
  {
    id: "tazza-doro",
    city: "rome",
    name: "La Casa del Caffe Tazza d'Oro",
    koName: "Tazza d'Oro",
    category: "cafe",
    area: "판테온",
    lat: 41.8989,
    lng: 12.4770,
    priority: 2,
    rank: 69,
    durationMin: 18,
    reservation: "불필요",
    bestTime: "판테온 전후",
    price: "낮음",
    safety: "주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["커피", "판테온", "휴식"],
    why: "판테온 바로 옆에서 빠르게 에스프레소를 마시는 후보.",
    tips: ["서서 마시면 빠름", "좌석 가격 확인", "소지품 주의"],
    koreanTips: ["아아보다 에스프레소/카푸치노 경험용으로 짧게"],
    menuHints: ["espresso", "granita di caffe"],
    watchOut: ["혼잡", "테이블 요금"],
    pairWith: ["pantheon", "sant-eustachio"],
    sourceIds: ["timeout-rome", "katie-parla-rome"],
  },
  {
    id: "antico-caffe-greco",
    city: "rome",
    name: "Antico Caffe Greco",
    koName: "Antico Caffe Greco",
    category: "cafe",
    area: "스페인 광장",
    lat: 41.9064,
    lng: 12.4801,
    priority: 2,
    rank: 65,
    durationMin: 35,
    reservation: "확인",
    bestTime: "쇼핑 중 휴식",
    price: "높음",
    safety: "주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["카페", "역사", "사진", "비쌈"],
    why: "맛보다 역사와 분위기 사진을 위한 클래식 카페 후보.",
    tips: ["가격대 확인", "스페인 계단/콘도티와 묶기", "서서 마시는 옵션 확인"],
    koreanTips: ["사진/기분값으로 생각하면 만족, 가성비 기대는 낮추기"],
    menuHints: ["espresso", "pastry"],
    watchOut: ["높은 가격", "혼잡"],
    pairWith: ["spanish-steps", "via-condotti"],
    sourceIds: ["timeout-rome"],
  },
  {
    id: "regoli",
    city: "rome",
    name: "Pasticceria Regoli",
    koName: "Pasticceria Regoli",
    category: "cafe",
    area: "Esquilino/Termini",
    lat: 41.8959,
    lng: 12.5046,
    priority: 2,
    rank: 71,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "아침 또는 간식",
    price: "낮음",
    safety: "주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["디저트", "마리토쪼", "역근처"],
    why: "테르미니/마조레 근처에서 로마식 디저트로 쓰는 후보.",
    tips: ["마리토쪼는 아침/오전", "역 주변 소지품 주의", "포장 가능 여부 확인"],
    koreanTips: ["크림빵 계열 좋아하면 만족", "달아서 둘이 나눠도 좋음"],
    menuHints: ["maritozzo", "pastries", "coffee"],
    watchOut: ["역 주변 혼잡"],
    pairWith: ["santa-maria-maggiore", "roma-termini"],
    sourceIds: ["eater-rome", "katie-parla-rome"],
  },
  {
    id: "pastificio-guerra",
    city: "rome",
    name: "Pastificio Guerra",
    koName: "Pastificio Guerra",
    category: "food",
    area: "스페인 광장",
    lat: 41.9071,
    lng: 12.4809,
    priority: 2,
    rank: 63,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "간단 점심",
    price: "낮음",
    safety: "주의",
    photo: 1,
    girlsTripFit: 2,
    tags: ["가성비", "파스타", "간단식사", "한국인선호"],
    why: "스페인 계단 근처에서 빠르게 파스타를 먹는 비상 카드.",
    tips: ["줄과 운영시간 확인", "좌석 기대 낮추기", "메인 식사보다 비상식"],
    koreanTips: ["가성비 파스타로 유명하지만 맛집 기대보다는 비상식 개념"],
    menuHints: ["daily pasta", "takeaway pasta"],
    watchOut: ["혼잡", "맛집 과대기대"],
    pairWith: ["spanish-steps", "via-condotti"],
    sourceIds: ["timeout-rome"],
  },
  {
    id: "bargello",
    city: "florence",
    name: "Bargello National Museum",
    koName: "바르젤로 미술관",
    category: "attraction",
    area: "시뇨리아/산타 크로체",
    lat: 43.7705,
    lng: 11.2575,
    priority: 2,
    rank: 80,
    durationMin: 90,
    reservation: "권장",
    bestTime: "오전 또는 비 오는 날",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["실내", "미술관", "비오는날"],
    why: "우피치/아카데미아 다음 단계의 실내 미술관 후보.",
    tips: ["우피치와 같은 날이면 짧게", "비 오는 날 대체", "조각 작품 위주"],
    koreanTips: ["미술관 좋아하면 만족, 아니면 우피치/아카데미아 우선"],
    watchOut: ["미술관 피로 누적"],
    pairWith: ["uffizi", "santa-croce", "gelateria-dei-neri"],
    sourceIds: ["lonely-planet-florence", "feelflorence"],
  },
  {
    id: "medici-chapels",
    city: "florence",
    name: "Medici Chapels",
    koName: "메디치 예배당",
    category: "attraction",
    area: "산 로렌초/중앙시장",
    lat: 43.7754,
    lng: 11.2531,
    priority: 2,
    rank: 78,
    durationMin: 75,
    reservation: "권장",
    bestTime: "두오모 전후",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["실내", "역사", "두오모근처"],
    why: "두오모/중앙시장 권역에서 짧은 실내 관람으로 넣기 좋다.",
    tips: ["중앙시장과 묶기", "예약/운영시간 확인", "두오모 일정과 충돌 피하기"],
    koreanTips: ["메디치 역사 관심 있으면 강한 후보"],
    watchOut: ["관심 없으면 피로도 대비 낮음"],
    pairWith: ["duomo-florence", "mercato-centrale", "sergio-gozzi"],
    sourceIds: ["lonely-planet-florence", "feelflorence"],
  },
  {
    id: "santa-maria-novella-basilica",
    city: "florence",
    name: "Basilica of Santa Maria Novella",
    koName: "산타 마리아 노벨라 성당",
    category: "attraction",
    area: "SMN/역",
    lat: 43.7746,
    lng: 11.2493,
    priority: 2,
    rank: 76,
    durationMin: 60,
    reservation: "권장",
    bestTime: "도착일 또는 출발일",
    price: "중간",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["성당", "역근처", "실내", "복장"],
    why: "피렌체 역과 숙소 사이에서 시간을 채우기 좋은 성당.",
    tips: ["복장 체크", "기차 전후 짐 보관 여부 확인", "약국 쇼핑과 묶기"],
    koreanTips: ["SMN 약국과 같이 잡으면 동선이 예쁨"],
    watchOut: ["역 주변 소매치기"],
    pairWith: ["officina-profumo", "santa-maria-novella", "florence-hotel"],
    sourceIds: ["feelflorence", "lonely-planet-florence"],
  },
  {
    id: "basilica-san-lorenzo",
    city: "florence",
    name: "Basilica di San Lorenzo",
    koName: "산 로렌초 성당",
    category: "attraction",
    area: "산 로렌초/중앙시장",
    lat: 43.7754,
    lng: 11.2536,
    priority: 2,
    rank: 70,
    durationMin: 45,
    reservation: "확인",
    bestTime: "중앙시장 전후",
    price: "중간",
    safety: "주의",
    photo: 1,
    girlsTripFit: 2,
    tags: ["성당", "시장근처", "복장"],
    why: "중앙시장과 두오모 사이에서 짧게 넣는 성당 후보.",
    tips: ["시장 혼잡 소지품 주의", "복장 체크", "메디치 예배당과 중복 고려"],
    koreanTips: ["동선상 지나가면 체크, 일부러 넣을 우선순위는 중간"],
    watchOut: ["가죽시장 호객"],
    pairWith: ["mercato-centrale", "medici-chapels", "duomo-florence"],
    sourceIds: ["feelflorence"],
  },
  {
    id: "palazzo-strozzi",
    city: "florence",
    name: "Palazzo Strozzi",
    koName: "스트로치 궁전",
    category: "attraction",
    area: "레푸블리카/쇼핑",
    lat: 43.7715,
    lng: 11.2517,
    priority: 2,
    rank: 68,
    durationMin: 60,
    reservation: "확인",
    bestTime: "전시 관심 있을 때",
    price: "확인",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["전시", "실내", "쇼핑근처"],
    why: "현재 전시에 따라 만족도가 크게 달라지는 실내 대체 카드.",
    tips: ["전시 내용 확인", "쇼핑/카페와 묶기", "비 오는 날 고려"],
    koreanTips: ["전시 취향이 맞을 때만 넣기"],
    watchOut: ["전시별 호불호"],
    pairWith: ["via-tornabuoni", "caffe-gilli", "rinascente-florence-rooftop"],
    sourceIds: ["feelflorence", "timeout-florence"],
  },
  {
    id: "palazzo-medici-riccardi",
    city: "florence",
    name: "Palazzo Medici Riccardi",
    koName: "메디치 리카르디 궁전",
    category: "attraction",
    area: "두오모/산 로렌초",
    lat: 43.7750,
    lng: 11.2555,
    priority: 2,
    rank: 69,
    durationMin: 55,
    reservation: "확인",
    bestTime: "두오모 전후",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["궁전", "실내", "메디치"],
    why: "두오모 권역에서 메디치 역사 흐름을 보충하는 짧은 코스.",
    tips: ["두오모/아카데미아 사이", "미술관 피로 있으면 스킵", "운영시간 확인"],
    koreanTips: ["메디치 스토리 알고 가면 재미가 오른다"],
    watchOut: ["랜드마크 우선 여행이면 후순위"],
    pairWith: ["duomo-florence", "accademia", "medici-chapels"],
    sourceIds: ["feelflorence", "lonely-planet-florence"],
  },
  {
    id: "brancacci-chapel",
    city: "florence",
    name: "Brancacci Chapel",
    koName: "브란카치 예배당",
    category: "attraction",
    area: "올트라르노",
    lat: 43.7676,
    lng: 11.2439,
    priority: 2,
    rank: 68,
    durationMin: 45,
    reservation: "권장",
    bestTime: "올트라르노 산책 중",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["실내", "예배당", "올트라르노"],
    why: "올트라르노에서 조용한 미술/성당 코스를 넣고 싶을 때.",
    tips: ["예약 확인", "피티/산토 스피리토와 묶기", "짧게 보기"],
    koreanTips: ["미술사 관심 없으면 우선순위 낮춤"],
    watchOut: ["예약 시간", "동선 벗어남"],
    pairWith: ["osteria-santo-spirito", "pitti-boboli"],
    sourceIds: ["lonely-planet-florence", "feelflorence"],
  },
  {
    id: "san-miniato-al-monte",
    city: "florence",
    name: "San Miniato al Monte",
    koName: "산 미니아토 알 몬테",
    category: "view",
    area: "전망/미켈란젤로",
    lat: 43.7621,
    lng: 11.2651,
    priority: 2,
    rank: 77,
    durationMin: 55,
    reservation: "확인",
    bestTime: "해질녘 전",
    price: "확인",
    safety: "밤주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["전망", "성당", "사진", "오르막"],
    why: "미켈란젤로 광장보다 조금 더 조용한 전망/성당 후보.",
    tips: ["오르막 체력 체크", "해진 뒤 복귀 경로", "미켈란젤로 광장과 묶기"],
    koreanTips: ["전망 사진 욕심 있으면 미켈란젤로와 같이 고려"],
    watchOut: ["밤 귀가", "불편한 신발"],
    pairWith: ["piazzale-michelangelo", "rose-garden"],
    sourceIds: ["lonely-planet-florence", "feelflorence"],
  },
  {
    id: "rose-garden",
    city: "florence",
    name: "Giardino delle Rose",
    koName: "장미 정원",
    category: "view",
    area: "전망/미켈란젤로",
    lat: 43.7641,
    lng: 11.2636,
    priority: 2,
    rank: 72,
    durationMin: 40,
    reservation: "불필요",
    bestTime: "오후 또는 해질녘 전",
    price: "무료",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["전망", "정원", "사진", "휴식"],
    why: "미켈란젤로 광장 오르내리는 길에 쉬어가기 좋은 정원.",
    tips: ["계절감 확인", "오르막 중간 휴식", "비 오면 제외"],
    koreanTips: ["사진+휴식 둘 다 필요한 날에 좋음"],
    watchOut: ["더운 한낮"],
    pairWith: ["piazzale-michelangelo", "san-miniato-al-monte"],
    sourceIds: ["feelflorence", "lonely-planet-florence"],
  },
  {
    id: "bardini-garden",
    city: "florence",
    name: "Bardini Garden",
    koName: "바르디니 정원",
    category: "view",
    area: "올트라르노/전망",
    lat: 43.7653,
    lng: 11.2583,
    priority: 2,
    rank: 74,
    durationMin: 70,
    reservation: "권장",
    bestTime: "오전 또는 늦은 오후",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["정원", "전망", "사진", "오르막"],
    why: "보볼리보다 작고 사진/전망 집중형으로 넣기 좋은 정원.",
    tips: ["더운 한낮 피하기", "피티/베키오 다리와 묶기", "입장권 확인"],
    koreanTips: ["정원 사진 좋아하면 보볼리보다 만족도가 높을 수 있음"],
    watchOut: ["오르막", "날씨 영향"],
    pairWith: ["pitti-boboli", "ponte-vecchio", "piazzale-michelangelo"],
    sourceIds: ["feelflorence", "lonely-planet-florence"],
  },
  {
    id: "museo-galileo",
    city: "florence",
    name: "Museo Galileo",
    koName: "갈릴레오 박물관",
    category: "attraction",
    area: "우피치/아르노",
    lat: 43.7678,
    lng: 11.2555,
    priority: 2,
    rank: 65,
    durationMin: 60,
    reservation: "확인",
    bestTime: "비 오는 날 또는 우피치 전후",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["실내", "박물관", "우피치근처"],
    why: "우피치 근처에서 색다른 실내 대체 코스로 쓰기 좋다.",
    tips: ["관심 분야일 때만", "비 오는 날 대체", "우피치 뒤에는 짧게"],
    koreanTips: ["과학/기구 전시 취향이면 의외로 좋음"],
    watchOut: ["취향 아니면 지루할 수 있음"],
    pairWith: ["uffizi", "ponte-vecchio", "piazza-signoria"],
    sourceIds: ["feelflorence", "lonely-planet-florence"],
  },
  {
    id: "mercato-sant-ambrogio",
    city: "florence",
    name: "Mercato di Sant'Ambrogio",
    koName: "산탐브로조 시장",
    category: "food",
    area: "산타 크로체",
    lat: 43.7710,
    lng: 11.2666,
    priority: 2,
    rank: 74,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "점심",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["시장", "점심", "가성비", "한국인선호"],
    why: "중앙시장보다 조금 더 생활감 있는 점심/간식 후보.",
    tips: ["낮 시간에만", "산타 크로체와 묶기", "현금/카드 준비"],
    koreanTips: ["예약 없이 점심을 가볍게 해결하기 좋음"],
    menuHints: ["panino", "lampredotto", "market lunch"],
    watchOut: ["저녁 코스 아님"],
    pairWith: ["santa-croce", "semel", "ditta-artigianale"],
    sourceIds: ["eater-florence", "girl-in-florence"],
  },
  {
    id: "via-tornabuoni",
    city: "florence",
    name: "Via de' Tornabuoni",
    koName: "토르나부오니 거리",
    category: "shopping",
    area: "쇼핑/레푸블리카",
    lat: 43.7718,
    lng: 11.2502,
    priority: 2,
    rank: 70,
    durationMin: 45,
    reservation: "불필요",
    bestTime: "오후",
    price: "확인",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["쇼핑", "명품", "한국인선호"],
    why: "피렌체 쇼핑 동선의 중심. 레푸블리카/SMN과 묶기 좋다.",
    tips: ["택스리펀 확인", "쇼핑백 관리", "카페 휴식과 묶기"],
    koreanTips: ["명품/향수/가죽 쇼핑 관심 있으면 고정"],
    watchOut: ["쇼핑 시간 과소평가 금지"],
    pairWith: ["officina-profumo", "palazzo-strozzi", "procacci"],
    sourceIds: ["timeout-florence"],
  },
  {
    id: "rinascente-florence-rooftop",
    city: "florence",
    name: "Rinascente Firenze Rooftop",
    koName: "리나센테 피렌체 루프탑",
    category: "view",
    area: "레푸블리카/두오모",
    lat: 43.7715,
    lng: 11.2539,
    priority: 2,
    rank: 67,
    durationMin: 40,
    reservation: "확인",
    bestTime: "오후 휴식",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["전망", "카페", "쇼핑", "화장실", "한국인선호"],
    why: "두오모 주변에서 휴식, 화장실, 전망을 동시에 해결하는 실전 스팟.",
    tips: ["자리/가격 확인", "두오모 사진 보충", "쇼핑 중 휴식"],
    koreanTips: ["백화점 휴식 포인트처럼 쓰기 좋음", "사진과 화장실 해결"],
    watchOut: ["카페 가격대"],
    pairWith: ["duomo-florence", "caffe-gilli", "via-tornabuoni"],
    sourceIds: ["timeout-florence", "girl-in-florence"],
  },
  {
    id: "scuola-del-cuoio",
    city: "florence",
    name: "Scuola del Cuoio",
    koName: "가죽 학교",
    category: "shopping",
    area: "산타 크로체",
    lat: 43.7682,
    lng: 11.2630,
    priority: 2,
    rank: 66,
    durationMin: 40,
    reservation: "확인",
    bestTime: "산타 크로체 전후",
    price: "확인",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["가죽", "쇼핑", "선물", "한국인선호"],
    why: "피렌체 가죽 쇼핑을 조금 더 의미 있게 넣는 후보.",
    tips: ["운영시간 확인", "산타 크로체와 묶기", "구매 예산 정하기"],
    koreanTips: ["기념품/선물 쇼핑에 좋음", "시장 가죽보다 차분하게 보기 좋음"],
    watchOut: ["가격대", "택스리펀 조건"],
    pairWith: ["santa-croce", "gelateria-dei-neri"],
    sourceIds: ["feelflorence", "girl-in-florence"],
  },
  {
    id: "trattoria-sostanza",
    city: "florence",
    name: "Trattoria Sostanza",
    koName: "Trattoria Sostanza",
    category: "food",
    area: "SMN/토르나부오니",
    lat: 43.7714,
    lng: 11.2470,
    priority: 1,
    rank: 88,
    durationMin: 90,
    reservation: "필수",
    bestTime: "저녁",
    price: "높음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["예약", "피렌체음식", "버터치킨", "한국인선호"],
    why: "피렌체에서 클래식한 식사를 한 번 제대로 넣을 때 강한 후보.",
    tips: ["예약 먼저", "합석/분위기 감안", "저녁 후 숙소 복귀 경로 확인"],
    koreanTips: ["버터치킨/스테이크류가 한국인 입맛에 잘 맞을 가능성 높음"],
    menuHints: ["butter chicken", "bistecca", "artichoke pie"],
    watchOut: ["예약 난도", "가격대"],
    pairWith: ["via-tornabuoni", "officina-profumo"],
    sourceIds: ["eater-florence", "infatuation-florence", "girl-in-florence"],
  },
  {
    id: "trattoria-cammillo",
    city: "florence",
    name: "Trattoria Cammillo",
    koName: "Trattoria Cammillo",
    category: "food",
    area: "올트라르노/아르노",
    lat: 43.7672,
    lng: 11.2480,
    priority: 1,
    rank: 86,
    durationMin: 95,
    reservation: "필수",
    bestTime: "저녁",
    price: "높음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["예약", "클래식", "올트라르노"],
    why: "피렌체 클래식 식당 중 분위기 있는 저녁 후보.",
    tips: ["예약 필수로 보기", "베키오 다리/올트라르노와 묶기", "예산 확인"],
    koreanTips: ["분위기 있는 전통 식사를 원할 때", "둘이 저녁 메인 코스로 적합"],
    menuHints: ["pasta", "seasonal Tuscan dishes", "dessert"],
    watchOut: ["예약 난도", "가격대"],
    pairWith: ["ponte-vecchio", "pitti-boboli", "gelateria-la-carraia"],
    sourceIds: ["eater-florence", "infatuation-florence"],
  },
  {
    id: "trattoria-ruggero",
    city: "florence",
    name: "Trattoria Ruggero",
    koName: "Trattoria Ruggero",
    category: "food",
    area: "남쪽 올트라르노",
    lat: 43.7577,
    lng: 11.2448,
    priority: 2,
    rank: 80,
    durationMin: 90,
    reservation: "권장",
    bestTime: "점심 또는 저녁",
    price: "중간",
    safety: "밤주의",
    photo: 1,
    girlsTripFit: 2,
    tags: ["전통식", "현지식", "택시검토"],
    why: "음식 우선이라면 고려할 만하지만 중심부에서 벗어난다.",
    tips: ["왕복 이동시간 확인", "늦으면 택시", "식당 하나를 위해 이동하는 날에"],
    koreanTips: ["맛집 집착이 아니면 일정이 빡빡할 때 제외"],
    menuHints: ["Tuscan classics", "meat dishes"],
    watchOut: ["동선 효율 낮음"],
    pairWith: ["pitti-boboli", "piazzale-michelangelo"],
    sourceIds: ["infatuation-florence", "eater-florence"],
  },
  {
    id: "sergio-gozzi",
    city: "florence",
    name: "Trattoria Sergio Gozzi",
    koName: "Trattoria Sergio Gozzi",
    category: "food",
    area: "산 로렌초/중앙시장",
    lat: 43.7756,
    lng: 11.2531,
    priority: 2,
    rank: 81,
    durationMin: 70,
    reservation: "확인",
    bestTime: "점심",
    price: "중간",
    safety: "주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["점심", "전통식", "시장근처", "한국인선호"],
    why: "두오모/중앙시장 권역에서 강한 점심 후보.",
    tips: ["점심 운영 여부 확인", "웨이팅 길면 중앙시장으로 전환", "두오모 후 배치"],
    koreanTips: ["점심 한 끼를 현지식으로 넣기 좋음"],
    menuHints: ["ribollita", "pasta", "Tuscan mains"],
    watchOut: ["영업시간 짧을 수 있음"],
    pairWith: ["mercato-centrale", "medici-chapels", "duomo-florence"],
    sourceIds: ["eater-florence", "girl-in-florence", "curious-appetite"],
  },
  {
    id: "vini-e-vecchi-sapori",
    city: "florence",
    name: "Vini e Vecchi Sapori",
    koName: "Vini e Vecchi Sapori",
    category: "food",
    area: "시뇨리아",
    lat: 43.7695,
    lng: 11.2560,
    priority: 1,
    rank: 86,
    durationMin: 90,
    reservation: "필수",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["예약", "전통식", "우피치근처", "한국인선호"],
    why: "우피치/시뇨리아 권역에서 예약이 된다면 매우 효율적인 저녁 후보.",
    tips: ["예약 먼저", "우피치 후 바로 연결", "메뉴판/가격 확인"],
    koreanTips: ["동선 효율이 좋아 피렌체 초반 저녁으로 좋음"],
    menuHints: ["pasta", "Tuscan specials", "house wine"],
    watchOut: ["예약 난도"],
    pairWith: ["uffizi", "piazza-signoria", "perche-no"],
    sourceIds: ["eater-florence", "infatuation-florence", "girl-in-florence"],
  },
  {
    id: "trattoria-la-casalinga",
    city: "florence",
    name: "Trattoria La Casalinga",
    koName: "Trattoria La Casalinga",
    category: "food",
    area: "올트라르노",
    lat: 43.7666,
    lng: 11.2474,
    priority: 2,
    rank: 79,
    durationMin: 80,
    reservation: "권장",
    bestTime: "점심 또는 저녁",
    price: "중간",
    safety: "밤주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["전통식", "올트라르노", "가성비"],
    why: "피티/산토 스피리토 권역에서 전통식을 넣는 안정 후보.",
    tips: ["예약/웨이팅 확인", "올트라르노 산책과 묶기", "밤 복귀 경로"],
    koreanTips: ["과하게 비싼 저녁 대신 로컬한 식사를 원할 때"],
    menuHints: ["Tuscan home cooking", "pasta", "meat dishes"],
    watchOut: ["밤 귀가"],
    pairWith: ["pitti-boboli", "osteria-santo-spirito"],
    sourceIds: ["eater-florence", "girl-in-florence"],
  },
  {
    id: "il-santo-bevitore",
    city: "florence",
    name: "Il Santo Bevitore",
    koName: "Il Santo Bevitore",
    category: "food",
    area: "올트라르노",
    lat: 43.7690,
    lng: 11.2465,
    priority: 2,
    rank: 82,
    durationMin: 95,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "밤주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["분위기", "올트라르노", "와인", "한국인선호"],
    why: "올트라르노에서 분위기 있는 저녁과 와인을 원할 때.",
    tips: ["예약 권장", "와인 예산 확인", "숙소 복귀 경로 미리 열기"],
    koreanTips: ["여자 둘 분위기 저녁 후보로 좋음"],
    menuHints: ["seasonal menu", "wine", "pasta"],
    watchOut: ["늦은 밤 복귀"],
    pairWith: ["ponte-vecchio", "osteria-santo-spirito", "gelateria-la-carraia"],
    sourceIds: ["eater-florence", "infatuation-florence", "girl-in-florence"],
  },
  {
    id: "zeb",
    city: "florence",
    name: "Zeb",
    koName: "Zeb",
    category: "food",
    area: "산 니콜로/미켈란젤로",
    lat: 43.7657,
    lng: 11.2581,
    priority: 2,
    rank: 78,
    durationMin: 85,
    reservation: "권장",
    bestTime: "점심 또는 저녁",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["모던", "파스타", "미켈란젤로근처"],
    why: "미켈란젤로 광장 쪽 이동 전후에 식사를 넣는 후보.",
    tips: ["예약 확인", "오르막 전후 체력 고려", "산 니콜로 산책과 묶기"],
    koreanTips: ["전통식보다 깔끔한 식사를 원할 때"],
    menuHints: ["fresh pasta", "Tuscan dishes"],
    watchOut: ["좌석/예약 확인"],
    pairWith: ["piazzale-michelangelo", "rose-garden"],
    sourceIds: ["eater-florence", "infatuation-florence"],
  },
  {
    id: "nerbone",
    city: "florence",
    name: "Nerbone",
    koName: "Nerbone",
    category: "food",
    area: "중앙시장",
    lat: 43.7767,
    lng: 11.2530,
    priority: 2,
    rank: 74,
    durationMin: 35,
    reservation: "불필요",
    bestTime: "점심",
    price: "낮음",
    safety: "주의",
    photo: 1,
    girlsTripFit: 2,
    tags: ["시장", "가성비", "간단식사", "람프레도토"],
    why: "중앙시장에서 피렌체식 간단식을 빠르게 해결하는 후보.",
    tips: ["점심 시간 줄 확인", "내장류 메뉴 취향 확인", "시장 혼잡 소지품 주의"],
    koreanTips: ["내장류가 부담되면 다른 메뉴 선택", "둘이 하나 나눠 맛보기"],
    menuHints: ["lampredotto", "bollito sandwich", "market lunch"],
    watchOut: ["내장류 호불호", "혼잡"],
    pairWith: ["mercato-centrale", "medici-chapels"],
    sourceIds: ["eater-florence", "girl-in-florence"],
  },
  {
    id: "i-due-fratellini",
    city: "florence",
    name: "I Due Fratellini",
    koName: "I Due Fratellini",
    category: "food",
    area: "두오모/시뇨리아",
    lat: 43.7710,
    lng: 11.2553,
    priority: 2,
    rank: 72,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "간단 점심/간식",
    price: "낮음",
    safety: "주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["샌드위치", "가성비", "간단식사", "한국인선호"],
    why: "두오모와 시뇨리아 사이에서 빠르게 먹는 샌드위치 후보.",
    tips: ["서서 먹는 플랜", "줄 길면 스킵", "음료와 같이"],
    koreanTips: ["일정 빡빡한 날 점심 대체로 좋음"],
    menuHints: ["schiacciata", "panino", "wine by glass"],
    watchOut: ["좌석 없음", "혼잡"],
    pairWith: ["duomo-florence", "piazza-signoria", "uffizi"],
    sourceIds: ["eater-florence", "girl-in-florence"],
  },
  {
    id: "semel",
    city: "florence",
    name: "Semel",
    koName: "Semel",
    category: "food",
    area: "산탐브로조",
    lat: 43.7710,
    lng: 11.2660,
    priority: 2,
    rank: 70,
    durationMin: 30,
    reservation: "불필요",
    bestTime: "점심",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["샌드위치", "시장근처", "가성비"],
    why: "산탐브로조 시장 권역에서 짧고 맛있는 점심 후보.",
    tips: ["낮 시간 확인", "시장과 묶기", "작은 공간 감안"],
    koreanTips: ["한 끼를 가볍게 먹고 카페/젤라또를 더 넣고 싶을 때"],
    menuHints: ["panini", "wine", "seasonal fillings"],
    watchOut: ["운영시간"],
    pairWith: ["mercato-sant-ambrogio", "santa-croce"],
    sourceIds: ["eater-florence", "girl-in-florence"],
  },
  {
    id: "procacci",
    city: "florence",
    name: "Procacci",
    koName: "Procacci",
    category: "cafe",
    area: "토르나부오니",
    lat: 43.7719,
    lng: 11.2504,
    priority: 2,
    rank: 69,
    durationMin: 35,
    reservation: "확인",
    bestTime: "쇼핑 중 간식",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["간식", "와인", "쇼핑", "한국인선호"],
    why: "쇼핑 거리에서 작게 먹고 쉬기 좋은 클래식 간식 후보.",
    tips: ["트러플 파니니 소량", "와인/음료 가격 확인", "토르나부오니와 묶기"],
    koreanTips: ["쇼핑 중 당 떨어질 때 예쁘게 쉬기 좋음"],
    menuHints: ["truffle panini", "prosecco", "small bites"],
    watchOut: ["가성비보다 분위기"],
    pairWith: ["via-tornabuoni", "palazzo-strozzi"],
    sourceIds: ["eater-florence", "girl-in-florence"],
  },
  {
    id: "ditta-artigianale",
    city: "florence",
    name: "Ditta Artigianale",
    koName: "Ditta Artigianale",
    category: "cafe",
    area: "산타 크로체",
    lat: 43.7686,
    lng: 11.2606,
    priority: 2,
    rank: 73,
    durationMin: 45,
    reservation: "불필요",
    bestTime: "오전 또는 오후",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["스페셜티커피", "브런치", "한국인선호", "휴식"],
    why: "이탈리아 에스프레소 말고 익숙한 커피/브런치가 필요할 때.",
    tips: ["산타 크로체/우피치 사이 휴식", "아이스 커피 가능 여부 확인", "브런치 대체"],
    koreanTips: ["한국 카페 감성에 가까운 회복 포인트"],
    menuHints: ["flat white", "filter coffee", "brunch"],
    watchOut: ["이탈리아 전통 카페 기대와 다름"],
    pairWith: ["santa-croce", "gelateria-dei-neri", "mercato-sant-ambrogio"],
    sourceIds: ["eater-florence", "girl-in-florence"],
  },
  {
    id: "la-menagere",
    city: "florence",
    name: "La Menagere",
    koName: "La Menagere",
    category: "cafe",
    area: "두오모/산 로렌초",
    lat: 43.7752,
    lng: 11.2565,
    priority: 2,
    rank: 72,
    durationMin: 55,
    reservation: "권장",
    bestTime: "브런치 또는 오후",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["브런치", "카페", "사진", "한국인선호"],
    why: "분위기와 사진, 휴식을 같이 잡는 피렌체 카페 후보.",
    tips: ["예약/대기 확인", "두오모 전후", "식사보다 휴식 목적"],
    koreanTips: ["인스타 감성 카페로 만족도 높을 가능성", "둘이 쉬면서 사진 정리하기 좋음"],
    menuHints: ["brunch", "coffee", "dessert"],
    watchOut: ["피크 시간 혼잡"],
    pairWith: ["duomo-florence", "accademia", "mercato-centrale"],
    sourceIds: ["girl-in-florence", "timeout-florence"],
  },
  {
    id: "rivoire",
    city: "florence",
    name: "Rivoire",
    koName: "Rivoire",
    category: "cafe",
    area: "시뇨리아",
    lat: 43.7697,
    lng: 11.2559,
    priority: 2,
    rank: 67,
    durationMin: 35,
    reservation: "확인",
    bestTime: "우피치 전후",
    price: "중간",
    safety: "주의",
    photo: 3,
    girlsTripFit: 3,
    tags: ["카페", "디저트", "광장", "사진"],
    why: "시뇨리아 광장에서 클래식하게 쉬는 카페 후보.",
    tips: ["테이블 가격 확인", "우피치 전후 휴식", "광장 소지품 주의"],
    koreanTips: ["뷰값/자리값을 감안하면 좋은 휴식"],
    menuHints: ["hot chocolate", "coffee", "pastries"],
    watchOut: ["광장 가격", "소매치기"],
    pairWith: ["piazza-signoria", "uffizi"],
    sourceIds: ["girl-in-florence", "timeout-florence"],
  },
  {
    id: "vivoli",
    city: "florence",
    name: "Vivoli",
    koName: "Vivoli 젤라또",
    category: "cafe",
    area: "산타 크로체",
    lat: 43.7703,
    lng: 11.2609,
    priority: 2,
    rank: 69,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "오후",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["젤라또", "디저트", "산타크로체"],
    why: "산타 크로체 권역에서 젤라또/디저트 후보로 쓰기 좋다.",
    tips: ["Gelateria dei Neri와 비교", "식사 전 작은 사이즈", "혼잡하면 이동"],
    koreanTips: ["젤라또 비교용으로 지도에 저장"],
    menuHints: ["gelato", "affogato", "seasonal flavors"],
    watchOut: ["달아서 과식 주의"],
    pairWith: ["santa-croce", "ditta-artigianale"],
    sourceIds: ["eater-florence", "girl-in-florence"],
  },
  {
    id: "gelateria-la-carraia",
    city: "florence",
    name: "Gelateria La Carraia",
    koName: "Gelateria La Carraia",
    category: "cafe",
    area: "올트라르노/강변",
    lat: 43.7685,
    lng: 11.2455,
    priority: 2,
    rank: 71,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "베키오 다리 산책 전후",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["젤라또", "강변", "한국인선호"],
    why: "강변 산책 중 넣기 쉬운 젤라또 후보.",
    tips: ["베키오 다리 서쪽 산책과 묶기", "해질녘 전후", "줄 길면 다음 후보"],
    koreanTips: ["강변 사진 찍고 젤라또 먹는 흐름이 좋음"],
    menuHints: ["pistachio", "fruit", "cream flavors"],
    watchOut: ["식사 직전 과식"],
    pairWith: ["ponte-vecchio", "il-santo-bevitore", "trattoria-cammillo"],
    sourceIds: ["girl-in-florence", "eater-florence"],
  },
  {
    id: "perche-no",
    city: "florence",
    name: "Perche No!",
    koName: "Perche No!",
    category: "cafe",
    area: "두오모/시뇨리아",
    lat: 43.7708,
    lng: 11.2561,
    priority: 2,
    rank: 70,
    durationMin: 20,
    reservation: "불필요",
    bestTime: "오후",
    price: "낮음",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["젤라또", "중심부", "휴식"],
    why: "두오모, 시뇨리아, 우피치 사이에서 빠르게 쓰는 젤라또 후보.",
    tips: ["중심부 혼잡 주의", "짧게 들르기", "맛 조합 둘이 나누기"],
    koreanTips: ["동선 낭비 없이 당 충전"],
    menuHints: ["gelato", "sorbetto", "pistachio"],
    watchOut: ["혼잡", "소지품"],
    pairWith: ["duomo-florence", "piazza-signoria", "vini-e-vecchi-sapori"],
    sourceIds: ["girl-in-florence", "eater-florence"],
  },
  {
    id: "sbrino",
    city: "florence",
    name: "Sbrino",
    koName: "Sbrino",
    category: "cafe",
    area: "올트라르노",
    lat: 43.7670,
    lng: 11.2413,
    priority: 2,
    rank: 68,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "올트라르노 산책 중",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["젤라또", "올트라르노", "휴식"],
    why: "올트라르노 서쪽 산책 중 쓰는 젤라또 후보.",
    tips: ["근처에 있을 때만", "피티/산토 스피리토와 묶기", "짧게 들르기"],
    koreanTips: ["덜 붐비는 젤라또 후보로 저장"],
    menuHints: ["gelato", "seasonal flavors"],
    watchOut: ["중심부에서 일부러 가기엔 멀 수 있음"],
    pairWith: ["osteria-santo-spirito", "trattoria-la-casalinga"],
    sourceIds: ["girl-in-florence", "eater-florence"],
  },
  {
    id: "gusta-pizza",
    city: "florence",
    name: "Gusta Pizza",
    koName: "Gusta Pizza",
    category: "food",
    area: "올트라르노",
    lat: 43.7664,
    lng: 11.2479,
    priority: 2,
    rank: 70,
    durationMin: 55,
    reservation: "불필요",
    bestTime: "점심 또는 가벼운 저녁",
    price: "낮음",
    safety: "밤주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["피자", "가성비", "올트라르노", "한국인선호"],
    why: "올트라르노에서 간단하고 실패 확률 낮은 피자 후보.",
    tips: ["웨이팅 길면 다른 후보", "피티/산토 스피리토와 묶기", "가볍게 먹기"],
    koreanTips: ["파스타가 질릴 때 피자로 전환"],
    menuHints: ["margherita", "napoli", "pizza"],
    watchOut: ["혼잡", "좌석 기대 낮추기"],
    pairWith: ["pitti-boboli", "osteria-santo-spirito"],
    sourceIds: ["girl-in-florence", "eater-florence"],
  },
  {
    id: "buca-lapi",
    city: "florence",
    name: "Buca Lapi",
    koName: "Buca Lapi",
    category: "food",
    area: "토르나부오니",
    lat: 43.7718,
    lng: 11.2500,
    priority: 2,
    rank: 80,
    durationMin: 110,
    reservation: "필수",
    bestTime: "저녁",
    price: "높음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["스테이크", "예약", "피렌체음식", "한국인선호"],
    why: "피렌체식 스테이크를 제대로 넣는 고전 후보.",
    tips: ["Bistecca는 양이 크므로 둘이 주문 전략 필요", "예약 필수", "예산 확인"],
    koreanTips: ["스테이크를 꼭 먹고 싶다면 강한 후보", "레어 굽기가 기본임을 감안"],
    menuHints: ["bistecca alla fiorentina", "pasta", "wine"],
    watchOut: ["가격대", "레어 스테이크 호불호"],
    pairWith: ["via-tornabuoni", "officina-profumo"],
    sourceIds: ["eater-florence", "infatuation-florence", "girl-in-florence"],
  },
  {
    id: "osteria-cinghiale-bianco",
    city: "florence",
    name: "Osteria del Cinghiale Bianco",
    koName: "Osteria del Cinghiale Bianco",
    category: "food",
    area: "올트라르노/베키오 다리",
    lat: 43.7683,
    lng: 11.2492,
    priority: 2,
    rank: 76,
    durationMin: 90,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "밤주의",
    photo: 1,
    girlsTripFit: 3,
    tags: ["전통식", "파스타", "올트라르노", "한국인선호"],
    why: "베키오 다리 근처에서 토스카나식 저녁을 넣는 후보.",
    tips: ["예약 확인", "베키오 다리 산책과 묶기", "와일드보어 메뉴 취향 확인"],
    koreanTips: ["라구/파스타류가 한국인 입맛에도 비교적 편함"],
    menuHints: ["pappardelle al cinghiale", "Tuscan dishes"],
    watchOut: ["피크 시간 혼잡"],
    pairWith: ["ponte-vecchio", "gelateria-la-carraia"],
    sourceIds: ["infatuation-florence", "girl-in-florence"],
  },
  {
    id: "la-fettunta",
    city: "florence",
    name: "La Fettunta",
    koName: "La Fettunta",
    category: "food",
    area: "우피치/산타 크로체",
    lat: 43.7692,
    lng: 11.2576,
    priority: 2,
    rank: 72,
    durationMin: 65,
    reservation: "권장",
    bestTime: "점심 또는 이른 저녁",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["전통식", "우피치근처", "가성비"],
    why: "우피치 전후 식사 후보가 부족할 때 넣기 좋은 위치.",
    tips: ["웨이팅 확인", "All'Antico Vinaio 대기 길 때 대안", "메뉴 가격 확인"],
    koreanTips: ["너무 포멀하지 않은 식사를 원할 때"],
    menuHints: ["bruschetta", "pasta", "Tuscan mains"],
    watchOut: ["혼잡"],
    pairWith: ["uffizi", "all-antico-vinaio", "gelateria-dei-neri"],
    sourceIds: ["girl-in-florence", "curious-appetite"],
  },
  {
    id: "caffe-scudieri",
    city: "florence",
    name: "Caffe Scudieri",
    koName: "Caffe Scudieri",
    category: "cafe",
    area: "두오모",
    lat: 43.7733,
    lng: 11.2558,
    priority: 2,
    rank: 66,
    durationMin: 30,
    reservation: "확인",
    bestTime: "두오모 전후",
    price: "중간",
    safety: "주의",
    photo: 2,
    girlsTripFit: 3,
    tags: ["카페", "두오모뷰", "휴식"],
    why: "두오모 바로 앞에서 클래식 카페 휴식을 넣는 후보.",
    tips: ["뷰/자리 가격 확인", "짧게 쉬기", "두오모 광장 소지품 주의"],
    koreanTips: ["두오모 뷰값을 감안하고 쉬는 곳"],
    menuHints: ["coffee", "pastries", "aperitivo"],
    watchOut: ["관광지 가격", "혼잡"],
    pairWith: ["duomo-florence", "caffe-gilli"],
    sourceIds: ["girl-in-florence", "timeout-florence"],
  },
];

export const extraSources: Source[] = [
  {
    id: "timeout-rome",
    label: "Time Out Rome",
    url: "https://www.timeout.com/rome",
    note: "로마 명소, 식당, 젤라또, 동네 후보 교차 확인.",
  },
  {
    id: "lonely-planet-rome",
    label: "Lonely Planet Rome",
    url: "https://www.lonelyplanet.com/destinations/italy/rome",
    note: "로마 대표 명소와 동네/실전 팁 확인.",
  },
  {
    id: "eater-rome",
    label: "Eater Rome 38",
    url: "https://www.eater.com/maps/best-restaurants-rome-italy",
    note: "로마 식당, 피자, 간식, 젤라또 후보 교차 확인.",
  },
  {
    id: "infatuation-rome",
    label: "The Infatuation Rome",
    url: "https://www.theinfatuation.com/rome/guides/best-rome-restaurants",
    note: "로마 식당 분위기와 사용 상황 확인.",
  },
  {
    id: "cntraveler-rome",
    label: "Condé Nast Traveler Rome Restaurants",
    url: "https://www.cntraveler.com/gallery/best-restaurants-in-rome",
    note: "2026년 기준 로마 레스토랑 후보 교차 확인.",
  },
  {
    id: "katie-parla-rome",
    label: "Katie Parla Rome Food Guide",
    url: "https://katieparla.com/where-to-eat-drink-shop-rome/",
    note: "로마 음식 전문 로컬 가이드 교차 확인.",
  },
  {
    id: "timeout-florence",
    label: "Time Out Florence",
    url: "https://www.timeout.com/florence",
    note: "피렌체 명소, 식당, 카페, 쇼핑 후보 확인.",
  },
  {
    id: "lonely-planet-florence",
    label: "Lonely Planet Florence",
    url: "https://www.lonelyplanet.com/destinations/italy/florence",
    note: "피렌체 명소와 권역 구성 확인.",
  },
  {
    id: "eater-florence",
    label: "Eater Florence 35",
    url: "https://www.eater.com/maps/best-restaurants-florence-italy",
    note: "피렌체 식당과 간단식 후보 확인.",
  },
  {
    id: "infatuation-florence",
    label: "The Infatuation Florence",
    url: "https://www.theinfatuation.com/florence/guides/best-restaurants-florence-italy",
    note: "피렌체 식당 분위기와 목적별 후보 확인.",
  },
  {
    id: "girl-in-florence",
    label: "Girl in Florence Food Guide",
    url: "https://girlinflorence.com/2024/01/24/restaurantsnightlife-list/",
    note: "피렌체 로컬 음식/카페/나이트라이프 후보 확인.",
  },
  {
    id: "curious-appetite",
    label: "The Curious Appetite Florence",
    url: "https://thecuriousappetite.com/2024/11/21/best-restaurants-in-florence-italy/",
    note: "피렌체 음식 전문 로컬 가이드 교차 확인.",
  },
  {
    id: "korean-embassy-italy",
    label: "주이탈리아 대한민국 대사관",
    url: "https://it.mofa.go.kr/it-ko/index.do",
    note: "한국인 여행자 긴급 연락처와 영사 정보 확인.",
  },
  {
    id: "adr-fco-taxi",
    label: "Aeroporti di Roma Taxi",
    url: "https://www.adr.it/web/aeroporti-di-roma-en/pax-fco-taxi",
    note: "로마 공항 택시 고정 요금 확인.",
  },
  {
    id: "smartraveller-italy",
    label: "Smartraveller Italy Advice",
    url: "https://www.smartraveller.gov.au/destinations/europe/italy",
    note: "관광지/교통 소매치기와 주의사항 확인.",
  },
];

export const koreanTravelGuides = [
  {
    title: "한국인 2명 여행 운영 원칙",
    items: [
      "하루 Must는 2-3개까지만 고정하고 나머지는 지도에서 근처 후보로 넣는다.",
      "식당 예약은 점심 1개 또는 저녁 1개만 강하게 고정한다. 둘 다 고정하면 현장 피로도가 높다.",
      "두 명 중 한 명이 사진/쇼핑을 좋아하면 중심부 일정마다 카페 1개와 쇼핑 1개를 완충재로 둔다.",
      "숙소 복귀는 밤 9시 이후부터 별도 일정으로 취급한다. 밝은 길, 택시, 지하철 혼잡도를 같이 본다.",
    ],
  },
  {
    title: "한국인 입맛 리셋",
    items: [
      "파스타가 이어지면 다음 끼니는 피자, 샌드위치, 시장, 브런치로 바꾼다.",
      "짜게 느껴질 수 있으니 물을 충분히 주문하고, 둘이 여러 메뉴를 나눠서 간을 분산한다.",
      "스테이크는 레어가 기본인 경우가 많다. 완전 익힘을 기대하면 주문 전에 굽기 표현을 준비한다.",
      "젤라또는 하루 1-2회까지도 여행 리듬상 괜찮지만 식사 직전에는 작은 사이즈로 간다.",
    ],
  },
  {
    title: "쇼핑/택스리펀",
    items: [
      "명품/화장품/가죽 쇼핑 후보는 지도에 미리 찍고, 여권 원본 필요 여부는 매장별로 확인한다.",
      "택스리펀 서류는 결제 직후 바로 사진으로 저장한다.",
      "쇼핑백은 여러 개 들고 밤 이동하지 않는다. 숙소 들렀다 나오는 루트를 우선한다.",
      "가격 비교가 필요한 품목은 한국 가격 캡처를 미리 저장해둔다.",
    ],
  },
  {
    title: "여자 둘 안전 루틴",
    items: [
      "역, 광장, 분수, 박물관 줄에서는 휴대폰을 손에 오래 들고 있지 않는다.",
      "길을 볼 때는 한 명이 지도, 한 명이 주변을 본다.",
      "사진 찍어준다는 접근, 팔찌, 서명, 장미, 무료 선물은 응대하지 않는다.",
      "밤에 분위기가 애매하면 걷기보다 택시 앱/택시 승강장을 우선한다.",
    ],
  },
];

export const foodOrderGuides = [
  {
    city: "로마",
    title: "로마에서 먹어볼 것",
    items: [
      "Carbonara: 크림이 아니라 달걀, 치즈, 후추, guanciale 기반. 짠맛이 강할 수 있다.",
      "Cacio e pepe: 치즈와 후추 중심이라 둘이 나눠 먹기 좋다.",
      "Amatriciana: 토마토와 guanciale가 들어가 한국인 입맛에 비교적 편하다.",
      "Suppli: 튀긴 주먹밥 느낌의 간식. 식사 사이에 좋다.",
      "Maritozzo: 크림빵 계열. 아침이나 카페 간식으로 좋다.",
    ],
  },
  {
    city: "피렌체",
    title: "피렌체에서 먹어볼 것",
    items: [
      "Bistecca alla Fiorentina: 양이 크고 레어가 기본. 둘이 하나를 나누는 전략이 좋다.",
      "Pappardelle al cinghiale: 멧돼지 라구 파스타. 진한 라구 좋아하면 만족도 높다.",
      "Ribollita: 채소/빵 수프. 무거운 고기 식사 사이에 좋다.",
      "Lampredotto: 내장 샌드위치. 호불호가 있어 둘이 하나만 맛보기 추천.",
      "Schiacciata: 피렌체식 납작빵 샌드위치. 일정 빡빡한 날 점심 대체로 좋다.",
    ],
  },
  {
    city: "공통",
    title: "주문 전에 확인",
    items: [
      "Coperto: 자리세/커버차지가 붙을 수 있다.",
      "Acqua naturale: 탄산 없는 물. Acqua frizzante는 탄산수.",
      "카푸치노는 보통 오전 이미지가 강하지만 관광객이라고 큰 문제는 아니다.",
      "테이블에 앉으면 서서 마시는 커피보다 가격이 높을 수 있다.",
      "영업시간은 구글맵과 공식 채널을 당일 한 번 더 확인한다.",
    ],
  },
];
