import type { Place } from "./data";

// 2026-06 대량 수집분 — 한국 블로그/Time Out/Eater/50 Top Pizza 등 교차 확인.
// 좌표는 도보 내비 수준 근사값(±100m). 정밀 이동은 카드의 Maps 링크 사용.
export const morePlaces: Place[] = [
  /* ===== 로마 ===== */
  {
    id: "seu-pizza-illuminati",
    city: "rome",
    name: "Seu Pizza Illuminati",
    koName: "세우 피자 일루미나티",
    category: "food",
    area: "트라스테베레 남쪽",
    lat: 41.8782,
    lng: 12.4659,
    priority: 2,
    rank: 79,
    durationMin: 80,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["피자", "모던", "수상경력"],
    why: "50 Top Pizza 세계 상위권 단골의 창작 피자. 클래식 로마 피자와 전혀 다른 모던 토핑이 강점.",
    tips: ["마르게리타+창작 1판씩 섞기", "디저트 피자도 평 좋음"],
    koreanTips: ["트라스테베레 중심에서 도보 12분 — 저녁 산책 겸"],
    menuHints: ["창작 시즌 피자", "마리나라", "디저트 피자"],
    watchOut: ["주말 예약 권장"],
    pairWith: ["trastevere", "ai-marmi"],
    sourceIds: ["timeout-rome", "eater-rome"],
  },
  {
    id: "ai-marmi",
    city: "rome",
    name: "Ai Marmi",
    koName: "아이 마르미",
    category: "food",
    area: "트라스테베레",
    lat: 41.8867,
    lng: 12.4699,
    priority: 2,
    rank: 76,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "저녁 (늦게까지)",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["피자", "로마식", "현지인", "심야"],
    why: "대리석 테이블 때문에 '영안실'이란 별명으로 불리는 트라스테베레 피자 명소. 종잇장처럼 바삭한 로마식 도우의 기준점.",
    tips: ["수플리·바칼라 튀김 전채가 국룰", "회전 빨라 웨이팅 금방 빠짐"],
    koreanTips: ["쫄깃한 나폴리식 기대하면 실망 — 바삭한 과자 식감"],
    menuHints: ["수플리", "바칼라", "마르게리타"],
    watchOut: ["현금 위주", "월요일 휴무 패턴"],
    pairWith: ["trastevere", "santa-maria-trastevere"],
    sourceIds: ["timeout-rome", "katie-parla-rome"],
  },
  {
    id: "pizzeria-da-remo",
    city: "rome",
    name: "Pizzeria Da Remo",
    koName: "다 레모",
    category: "food",
    area: "테스타치오",
    lat: 41.8758,
    lng: 12.4737,
    priority: 2,
    rank: 78,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "저녁 오픈 직후",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["피자", "로마식", "현지인", "가성비"],
    why: "테스타치오 토박이들의 로마식 피자 1순위. 시끌벅적한 야외 테이블과 종이 식탁보가 그 자체로 로마다.",
    tips: ["오픈(19시) 직후 도착이 답", "전채 튀김류 같이"],
    koreanTips: ["영어 메뉴 없어도 마르게리타+수플리면 충분"],
    menuHints: ["마르게리타", "수플리", "필레티 디 바칼라"],
    watchOut: ["현금만", "일요일 휴무"],
    pairWith: ["testaccio-market", "felice-testaccio"],
    sourceIds: ["katie-parla-rome", "eater-rome"],
  },
  {
    id: "da-cesare-al-casaletto",
    city: "rome",
    name: "Da Cesare al Casaletto",
    koName: "다 체사레 알 카살레토",
    category: "food",
    area: "몬테베르데 (트램 8)",
    lat: 41.8689,
    lng: 12.4452,
    priority: 3,
    rank: 77,
    durationMin: 90,
    reservation: "필수",
    bestTime: "점심 또는 이른 저녁",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["트라토리아", "현지인", "전채튀김"],
    why: "음식 기자들이 '로마 최고의 트라토리아'로 자주 꼽는 교외 명가. 폴페테 디 볼리토와 프리티(튀김 전채)가 전설.",
    tips: ["트램 8 종점 — 트라스테베레에서 20분", "전채 3종은 무조건"],
    koreanTips: ["일정 여유 있는 날만 — 동선 밖이지만 가는 가치 충분"],
    menuHints: ["폴페테 디 볼리토", "프리티 전채", "카르보나라"],
    watchOut: ["예약 없이는 불가 수준", "이동시간 왕복 1시간"],
    pairWith: ["trastevere"],
    sourceIds: ["katie-parla-rome", "eater-rome"],
  },
  {
    id: "antica-birreria-peroni",
    city: "rome",
    name: "Antica Birreria Peroni",
    koName: "안티카 비레리아 페로니",
    category: "food",
    area: "트레비/중심부",
    lat: 41.8976,
    lng: 12.4839,
    priority: 3,
    rank: 72,
    durationMin: 70,
    reservation: "불필요",
    bestTime: "저녁",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["비어홀", "가성비", "고기"],
    why: "1906년부터 자리를 지킨 페로니 직영 비어홀. 소시지·슈니첼류와 생맥주를 시내 한복판 가격답지 않게 판다.",
    tips: ["합석 문화 — 피크엔 기다림", "맥주는 사이즈 단위 주문"],
    koreanTips: ["트레비 야경 보고 맥주 한잔 동선에 최적"],
    menuHints: ["수제 소시지", "슈니첼", "페로니 생맥주"],
    watchOut: ["일요일 휴무"],
    pairWith: ["trevi-fountain", "galleria-sciarra"],
    sourceIds: ["timeout-rome"],
  },
  {
    id: "pane-e-salame",
    city: "rome",
    name: "Pane e Salame",
    koName: "파네 에 살라메",
    category: "food",
    area: "트레비/중심부",
    lat: 41.9007,
    lng: 12.4822,
    priority: 2,
    rank: 75,
    durationMin: 30,
    reservation: "불필요",
    bestTime: "점심",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["파니니", "줄맛집", "가성비"],
    why: "트레비 분수 도보 3분의 파니니·살루미 보드 줄맛집. 5유로대 파니니로 중심부 점심을 해결하는 한국인 단골 코스.",
    tips: ["피크(12-14시) 줄 김 — 비껴가기", "보드는 2인 1개면 충분"],
    koreanTips: ["트레비 → 판테온 이동 중 끼니로 딱"],
    menuHints: ["프로슈토 파니니", "믹스 살루미 보드", "부라타"],
    watchOut: ["좌석 적음 — 서서/포장 각오"],
    pairWith: ["trevi-fountain", "pantheon"],
    sourceIds: ["timeout-rome"],
  },
  {
    id: "la-prosciutteria-trevi",
    city: "rome",
    name: "La Prosciutteria Trevi",
    koName: "라 프로슈테리아 (트레비)",
    category: "food",
    area: "트레비/중심부",
    lat: 41.9009,
    lng: 12.4815,
    priority: 3,
    rank: 72,
    durationMin: 40,
    reservation: "불필요",
    bestTime: "늦은 오후 아페리티보",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["살루미", "와인", "아페리티보"],
    why: "나무 도마에 프로슈토·치즈·과일을 수북이 — 와인 한 잔 곁들이는 토스카나식 보드 전문점.",
    tips: ["보드는 인원수보다 한 단계 작게", "하우스 와인 가성비"],
    menuHints: ["믹스 보드", "키안티 글라스", "트러플 살라미"],
    watchOut: ["지하석은 어두움 — 사진은 1층"],
    pairWith: ["trevi-fountain", "pantheon"],
    sourceIds: ["timeout-rome"],
  },
  {
    id: "aroma-rooftop",
    city: "rome",
    name: "Aroma at Palazzo Manfredi",
    koName: "아로마 (콜로세움 뷰 루프탑)",
    category: "food",
    area: "콜로세움",
    lat: 41.8901,
    lng: 12.4983,
    priority: 3,
    rank: 70,
    durationMin: 120,
    reservation: "필수",
    bestTime: "일몰 시간대 디너",
    price: "높음",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["미슐랭", "루프탑", "기념일", "뷰"],
    why: "콜로세움이 정면으로 보이는 미슐랭 1스타 루프탑. 가격은 로마 최상급이지만 '한 번의 기념 디너'로는 대체 불가.",
    tips: ["일몰 30분 전 예약이 베스트", "드레스코드 스마트 캐주얼"],
    koreanTips: ["런치 코스가 디너보다 진입장벽 낮음"],
    menuHints: ["테이스팅 코스", "런치 코스"],
    watchOut: ["1인 10만원대 이상 각오", "수주 전 예약"],
    pairWith: ["colosseum-forum", "monti"],
    sourceIds: ["restaurant-official", "cntraveler-rome"],
  },
  {
    id: "terrazza-borromini",
    city: "rome",
    name: "Terrazza Borromini",
    koName: "테라차 보로미니",
    category: "view",
    area: "나보나",
    lat: 41.8987,
    lng: 12.4720,
    priority: 3,
    rank: 71,
    durationMin: 60,
    reservation: "권장",
    bestTime: "해질녘 아페리티보",
    price: "높음",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["루프탑", "아페리티보", "나보나뷰"],
    why: "나보나 광장 돔이 손에 닿을 듯한 루프탑 바. 칵테일 한 잔 가격으로 로마 지붕 일몰을 산다.",
    tips: ["미니멈 차지/시간제 좌석 확인", "일몰 40분 전 입장"],
    koreanTips: ["식사보다 음료+사진 목적이 만족도 높음"],
    menuHints: ["스프리츠", "칵테일"],
    watchOut: ["드레스코드 약간 있음", "바람 부는 날 추움"],
    pairWith: ["piazza-navona", "campo-de-fiori"],
    sourceIds: ["timeout-rome", "cntraveler-rome"],
  },
  {
    id: "ginger-spagna",
    city: "rome",
    name: "Ginger Sapori e Salute",
    koName: "진저 (스파냐)",
    category: "cafe",
    area: "스페인 계단/쇼핑",
    lat: 41.9046,
    lng: 12.4809,
    priority: 3,
    rank: 70,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "브런치/점심",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["브런치", "샐러드", "건강식"],
    why: "쇼핑 거리 한복판의 밝은 브런치 카페. 파스타에 지친 날 샐러드·주스·아보카도 토스트로 환기하기 좋다.",
    tips: ["피크 점심 대기 있음", "착즙주스 평 좋음"],
    koreanTips: ["느끼함 리셋용 — 한국인 입맛 보험"],
    menuHints: ["아보카도 토스트", "착즙 주스", "샐러드 볼"],
    pairWith: ["spanish-steps", "via-condotti"],
    sourceIds: ["timeout-rome"],
  },
  {
    id: "coromandel",
    city: "rome",
    name: "Coromandel",
    koName: "코로만델",
    category: "cafe",
    area: "나보나",
    lat: 41.8996,
    lng: 12.4690,
    priority: 2,
    rank: 73,
    durationMin: 70,
    reservation: "권장",
    bestTime: "아침-브런치",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["브런치", "분위기", "예쁜인테리어"],
    why: "앤티크 가구와 자기 그릇의 살롱풍 브런치 — '로마에서 가장 예쁜 아침'으로 불리는 곳.",
    tips: ["주말 브런치는 예약", "팬케이크·에그 베네딕트 시그니처"],
    koreanTips: ["나보나 오전 산책과 묶으면 완벽"],
    menuHints: ["팬케이크", "에그 베네딕트", "카푸치노"],
    watchOut: ["좌석 간격 좁음"],
    pairWith: ["piazza-navona", "via-margutta"],
    sourceIds: ["timeout-rome", "cntraveler-rome"],
  },
  {
    id: "barnum-cafe",
    city: "rome",
    name: "Barnum Cafe",
    koName: "바넘 카페",
    category: "cafe",
    area: "캄포 데 피오리",
    lat: 41.8965,
    lng: 12.4703,
    priority: 3,
    rank: 69,
    durationMin: 50,
    reservation: "불필요",
    bestTime: "오후 휴식",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["스페셜티", "휴식", "빈티지"],
    why: "캄포 근처 빈티지 소파 카페. 관광 동선 한복판에서 노트북·수다·플랫화이트가 다 되는 드문 공간.",
    tips: ["오후 케이크+커피 조합", "저녁엔 칵테일 바로 전환"],
    menuHints: ["플랫화이트", "수제 케이크", "스프리츠"],
    pairWith: ["campo-de-fiori", "piazza-navona"],
    sourceIds: ["timeout-rome"],
  },
  {
    id: "gelato-san-crispino",
    city: "rome",
    name: "Il Gelato di San Crispino",
    koName: "산 크리스피노 젤라또",
    category: "cafe",
    area: "트레비",
    lat: 41.9014,
    lng: 12.4845,
    priority: 2,
    rank: 74,
    durationMin: 20,
    reservation: "불필요",
    bestTime: "트레비 전후",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["젤라또", "정통파", "뚜껑보관"],
    why: "맛 변질을 막으려 금속 뚜껑에 젤라또를 숨겨 파는 정통파. 꿀 젤라또와 자몽 소르베가 시그니처.",
    tips: ["콘 없음 — 컵만(맛 순수주의)", "트레비에서 도보 2분"],
    koreanTips: ["화려한 비주얼 없음 — 맛으로 승부하는 집"],
    menuHints: ["미엘레(꿀)", "자몽 소르베", "피스타치오"],
    pairWith: ["trevi-fountain", "galleria-sciarra"],
    sourceIds: ["timeout-rome", "lonely-planet-rome"],
  },
  {
    id: "castroni",
    city: "rome",
    name: "Castroni",
    koName: "카스트로니 (프라티 본점)",
    category: "shopping",
    area: "바티칸/프라티",
    lat: 41.9078,
    lng: 12.4603,
    priority: 3,
    rank: 69,
    durationMin: 40,
    reservation: "불필요",
    bestTime: "바티칸 일정 전후",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["식료품", "선물", "원두"],
    why: "1932년부터 이어진 식료품 백화점. 원두·초콜릿·파스타·올리브오일 — 식품 선물은 여기서 한 번에 끝난다.",
    tips: ["자체 로스팅 원두 가성비", "바 코너 에스프레소도 수준급"],
    koreanTips: ["슈퍼보다 살짝 비싸지만 선물 포장 퀄리티가 다름"],
    menuHints: ["원두", "잔두야 초콜릿", "트러플 제품"],
    pairWith: ["vatican-museums", "mercato-trionfale"],
    sourceIds: ["timeout-rome"],
  },
  {
    id: "quartiere-coppede",
    city: "rome",
    name: "Quartiere Coppedè",
    koName: "코페데 지구",
    category: "attraction",
    area: "트리에스테 (북동)",
    lat: 41.9183,
    lng: 12.5027,
    priority: 3,
    rank: 66,
    durationMin: 50,
    reservation: "불필요",
    bestTime: "오전 산책",
    price: "무료",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["건축", "한산", "사진", "히든"],
    why: "동화책에서 튀어나온 듯한 아르누보 건축 골목. 관광객이 거의 없어 한적한 사진 산책에 최고.",
    tips: ["개구리 분수가 중심 포인트", "보르게세 공원과 같은 북쪽 동선"],
    koreanTips: ["대중교통 필요 — 여유일에만"],
    pairWith: ["villa-borghese", "borghese-gallery"],
    sourceIds: ["timeout-rome", "cntraveler-rome"],
  },
  {
    id: "san-luigi-dei-francesi",
    city: "rome",
    name: "San Luigi dei Francesi",
    koName: "산 루이지 데이 프란체시 성당",
    category: "attraction",
    area: "나보나/중심부",
    lat: 41.8995,
    lng: 12.4744,
    priority: 2,
    rank: 78,
    durationMin: 30,
    reservation: "불필요",
    bestTime: "오전 (개방시간 확인)",
    price: "무료",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["카라바조", "무료", "성당", "실내"],
    why: "카라바조의 '성 마태오' 3부작을 무료로 보는 성당. 나보나에서 도보 2분 — 가성비 최고의 미술 코스.",
    tips: ["조명 동전(1유로) 넣으면 그림이 켜짐", "점심시간 폐문 주의"],
    koreanTips: ["나보나-판테온 사이 5분 경유로 명화 3점"],
    pairWith: ["piazza-navona", "pantheon", "sant-ignazio"],
    sourceIds: ["turismo-roma", "lonely-planet-rome"],
  },
  {
    id: "santa-maria-della-vittoria",
    city: "rome",
    name: "Santa Maria della Vittoria",
    koName: "산타 마리아 델라 비토리아 성당",
    category: "attraction",
    area: "레푸블리카/바르베리니",
    lat: 41.9046,
    lng: 12.4944,
    priority: 3,
    rank: 71,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "오전",
    price: "무료",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["베르니니", "무료", "성당", "실내"],
    why: "베르니니의 '성녀 테레사의 환희'가 있는 작은 성당. 보르게세 못 가는 일정이면 여기서 베르니니를 채운다.",
    tips: ["바르베리니 궁전과 도보 7분 묶음", "미사 중 관람 불가"],
    pairWith: ["palazzo-barberini", "santa-maria-maggiore"],
    sourceIds: ["turismo-roma"],
  },
  {
    id: "appia-antica",
    city: "rome",
    name: "Via Appia Antica",
    koName: "아피아 안티카 (옛 가도)",
    category: "attraction",
    area: "남부 근교",
    lat: 41.8554,
    lng: 12.5203,
    priority: 3,
    rank: 69,
    durationMin: 240,
    reservation: "불필요",
    bestTime: "일요일 오전 (차량 통제)",
    price: "낮음",
    safety: "보통",
    photo: 3,
    girlsTripFit: 2,
    tags: ["근교", "자전거", "유적", "반나절"],
    why: "2300년 된 로마 가도를 자전거로 달리는 반나절 코스. 카타콤베·수도교와 묶으면 로마의 또 다른 얼굴.",
    tips: ["일요일은 차 없는 거리", "입구 카페에서 자전거 대여"],
    koreanTips: ["한여름엔 오전만 — 그늘 적음"],
    watchOut: ["돌길 — 운동화 필수"],
    pairWith: ["baths-caracalla"],
    sourceIds: ["turismo-roma", "lonely-planet-rome"],
  },

  /* ===== 피렌체 ===== */
  {
    id: "trattoria-sabatino",
    city: "florence",
    name: "Trattoria Sabatino",
    koName: "트라토리아 사바티노",
    category: "food",
    area: "산 프레디아노",
    lat: 43.7715,
    lng: 11.2390,
    priority: 3,
    rank: 74,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "점심 (이른 저녁)",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["가정식", "초저가", "현지인", "노포"],
    why: "1956년부터 가격표가 거의 멈춘 듯한 동네 식당. 파스타가 5-6유로 — 피렌체 물가의 해방구.",
    tips: ["손글씨 일일 메뉴", "오픈 직후가 한산"],
    koreanTips: ["맛집보다 '경험'으로 — 옆 테이블 다 동네 어르신"],
    menuHints: ["일일 파스타", "구이 요리", "하우스 와인"],
    watchOut: ["현금만", "주말 휴무 확인"],
    pairWith: ["santo-spirito-basilica", "berbere-firenze"],
    sourceIds: ["curious-appetite", "girl-in-florence"],
  },
  {
    id: "il-latini",
    city: "florence",
    name: "Il Latini",
    koName: "일 라티니",
    category: "food",
    area: "산타 마리아 노벨라",
    lat: 43.7714,
    lng: 11.2491,
    priority: 2,
    rank: 79,
    durationMin: 100,
    reservation: "필수",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["전통", "티본", "프로슈토", "푸짐"],
    why: "천장에 프로슈토 다리가 주렁주렁 — 1911년부터 이어진 토스카나 만찬의 전형. 코스로 맡기면 끝없이 나온다.",
    tips: ["배 비우고 가기", "비스테카는 인원수 맞춰 주문"],
    koreanTips: ["혼잡한 합석 분위기 자체가 매력 포인트"],
    menuHints: ["비스테카", "리볼리타", "프로슈토 전채", "칸투치+빈산토"],
    watchOut: ["예약 필수", "양 조절 실패 주의"],
    pairWith: ["santa-maria-novella-basilica", "via-tornabuoni"],
    sourceIds: ["timeout-florence", "lonely-planet-florence"],
  },
  {
    id: "regina-bistecca",
    city: "florence",
    name: "Regina Bistecca",
    koName: "레지나 비스테카",
    category: "food",
    area: "두오모",
    lat: 43.7745,
    lng: 11.2580,
    priority: 2,
    rank: 80,
    durationMin: 100,
    reservation: "필수",
    bestTime: "저녁",
    price: "높음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["티본", "격식", "두오모권"],
    why: "옛 고서점을 개조한 '스테이크의 여왕'. 달오스테보다 차분하고 격식 있는 티본을 원하면 1순위.",
    tips: ["숙성 등급별 티본 선택 가능", "두오모 도보 2분"],
    koreanTips: ["서버의 고기 카트 설명이 친절 — 무게 보고 결정"],
    menuHints: ["비스테카 알라 피오렌티나", "타르타르", "토스카나 레드"],
    watchOut: ["저녁 예약 필수", "1kg 단위 과금"],
    pairWith: ["duomo-florence", "caffe-scudieri"],
    sourceIds: ["timeout-florence", "restaurant-official"],
  },
  {
    id: "all-antico-ristoro-di-cambi",
    city: "florence",
    name: "All'Antico Ristoro di' Cambi",
    koName: "디 캄비",
    category: "food",
    area: "산 프레디아노",
    lat: 43.7716,
    lng: 11.2407,
    priority: 2,
    rank: 78,
    durationMin: 90,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["티본", "로컬", "노포"],
    why: "관광객 줄 없이 현지인이 티본 먹으러 가는 산 프레디아노 명가. 가격도 중심부보다 한 단계 아래.",
    tips: ["벽돌 아치 안쪽 자리가 분위기", "수요일 휴무 확인"],
    koreanTips: ["달오스테 예약 실패 시 최고의 대안"],
    menuHints: ["비스테카", "파파르델레 멧돼지 라구", "콩 스튜"],
    pairWith: ["santo-spirito-basilica", "trattoria-sabatino"],
    sourceIds: ["curious-appetite", "girl-in-florence"],
  },
  {
    id: "osteria-dell-enoteca",
    city: "florence",
    name: "Osteria dell'Enoteca",
    koName: "오스테리아 델레노테카",
    category: "food",
    area: "로마나/피티",
    lat: 43.7627,
    lng: 11.2469,
    priority: 3,
    rank: 75,
    durationMin: 90,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["모던", "스테이크", "와인"],
    why: "와인 셀러를 낀 모던 토스카나 다이닝. 전통 트라토리아의 소란이 부담스러운 날의 조용한 선택지.",
    tips: ["스테이크 단품+사이드 조합", "보볼리 정원과 같은 동선"],
    menuHints: ["드라이에이징 스테이크", "계절 전채", "토스카나 와인"],
    pairWith: ["pitti-boboli", "pitti-gola-e-cantina"],
    sourceIds: ["timeout-florence"],
  },
  {
    id: "simbiosi-pizza",
    city: "florence",
    name: "SimBIOsi Organic Pizza",
    koName: "심비오시 피자",
    category: "food",
    area: "산 로렌초",
    lat: 43.7766,
    lng: 11.2552,
    priority: 3,
    rank: 72,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "저녁",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["피자", "유기농", "캐주얼"],
    why: "유기농 재료의 나폴리식 피자. 아카데미아·산 로렌초 권역에서 가볍게 한 판 하기 좋다.",
    tips: ["같은 집 파스타 지점도 옆에", "피크 살짝 대기"],
    menuHints: ["마르게리타 DOP", "부팔라 피자", "수제 맥주"],
    pairWith: ["accademia", "mercato-centrale"],
    sourceIds: ["timeout-florence"],
  },
  {
    id: "berbere-firenze",
    city: "florence",
    name: "Berberè Firenze",
    koName: "베르베레",
    category: "food",
    area: "산 프레디아노",
    lat: 43.7705,
    lng: 11.2412,
    priority: 3,
    rank: 73,
    durationMin: 70,
    reservation: "권장",
    bestTime: "저녁",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["피자", "사워도우", "힙"],
    why: "사워도우 발효 도우로 유명한 볼로냐 출신 피자 브랜드. 조각조각 잘라 나눠 먹는 방식이 재밌다.",
    tips: ["반반 토핑 가능", "크래프트 맥주 페어링"],
    menuHints: ["사워도우 마르게리타", "계절 토핑", "크래프트 맥주"],
    pairWith: ["santo-spirito-basilica", "gusta-pizza"],
    sourceIds: ["timeout-florence", "eater-florence"],
  },
  {
    id: "cibreo-caffe",
    city: "florence",
    name: "Cibrèo Caffè",
    koName: "치브레오 카페",
    category: "cafe",
    area: "산탐브로조",
    lat: 43.7705,
    lng: 11.2679,
    priority: 3,
    rank: 71,
    durationMin: 50,
    reservation: "불필요",
    bestTime: "아침-점심",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["클래식", "카페", "산탐브로조"],
    why: "피렌체 미식 제국 '치브레오'의 카페. 원목 인테리어에서 마시는 카푸치노와 케이크 — 시장 산책의 품격 마무리.",
    tips: ["같은 골목 치브레오 트라토리아도 후보", "아침 페이스트리 추천"],
    menuHints: ["카푸치노", "치즈케이크", "브리오슈"],
    pairWith: ["mercato-sant-ambrogio", "semel"],
    sourceIds: ["curious-appetite", "timeout-florence"],
  },
  {
    id: "le-vespe-cafe",
    city: "florence",
    name: "Le Vespe Cafe",
    koName: "레 베스페",
    category: "cafe",
    area: "산타 크로체",
    lat: 43.7697,
    lng: 11.2622,
    priority: 3,
    rank: 72,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "브런치",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["브런치", "팬케이크", "캐나다풍"],
    why: "캐나다식 팬케이크와 에그 베네딕트로 줄 서는 작은 브런치집. 이탈리아 아침이 물릴 때쯤 최고.",
    tips: ["주말 오픈런 권장", "현금 우대"],
    koreanTips: ["산타 크로체 아침 산책+브런치 조합"],
    menuHints: ["팬케이크", "에그 베네딕트", "스무디"],
    watchOut: ["좌석 매우 적음"],
    pairWith: ["santa-croce", "vivoli"],
    sourceIds: ["girl-in-florence"],
  },
  {
    id: "melaleuca-bakery",
    city: "florence",
    name: "Melaleuca Bakery & Bistrot",
    koName: "멜라레우카",
    category: "cafe",
    area: "아르노 강변/산타 크로체",
    lat: 43.7675,
    lng: 11.2614,
    priority: 2,
    rank: 74,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "아침-브런치",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["베이커리", "브런치", "강변"],
    why: "크루아상 맛집으로 소문난 강변 베이커리 비스트로. 주말 브런치 줄이 길지만 회전이 빠르다.",
    tips: ["페이스트리는 오전 소진", "강변 좌석 노리기"],
    menuHints: ["크루아상", "에그 디시", "플랫화이트"],
    pairWith: ["santa-croce", "ponte-vecchio"],
    sourceIds: ["girl-in-florence", "timeout-florence"],
  },
  {
    id: "amble-firenze",
    city: "florence",
    name: "Amblé",
    koName: "암블레",
    category: "cafe",
    area: "폰테베키오",
    lat: 43.7690,
    lng: 11.2517,
    priority: 3,
    rank: 71,
    durationMin: 50,
    reservation: "불필요",
    bestTime: "오후-아페리티보",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["빈티지", "안뜰", "아페리티보"],
    why: "폰테베키오 뒤 숨은 안뜰의 빈티지 가구 카페. 가구까지 전부 판매품 — 앉은 의자가 마음에 들면 산다.",
    tips: ["골목 안쪽이라 지도 필수", "파니니+스프리츠 조합"],
    menuHints: ["스프리츠", "파니니", "수제 레모네이드"],
    pairWith: ["ponte-vecchio", "piazza-signoria"],
    sourceIds: ["girl-in-florence"],
  },
  {
    id: "santarosa-bistrot",
    city: "florence",
    name: "Santarosa Bistrot",
    koName: "산타로사 비스트로",
    category: "cafe",
    area: "산 프레디아노 성벽",
    lat: 43.7724,
    lng: 11.2392,
    priority: 3,
    rank: 70,
    durationMin: 70,
    reservation: "권장",
    bestTime: "점심-해질녘",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["정원", "비스트로", "휴식"],
    why: "옛 성벽 아래 정원에 파라솔이 펼쳐진 비스트로. 나무 그늘 점심과 아페리티보로 현지 젊은층이 채운다.",
    tips: ["날씨 좋은 날만 진가", "주말 점심 예약 권장"],
    menuHints: ["계절 파스타", "스프리츠", "치즈 보드"],
    pairWith: ["berbere-firenze", "trattoria-sabatino"],
    sourceIds: ["girl-in-florence", "timeout-florence"],
  },
  {
    id: "pitti-gola-e-cantina",
    city: "florence",
    name: "Pitti Gola e Cantina",
    koName: "피티 골라 에 칸티나",
    category: "food",
    area: "피티",
    lat: 43.7654,
    lng: 11.2500,
    priority: 3,
    rank: 72,
    durationMin: 70,
    reservation: "권장",
    bestTime: "오후-저녁",
    price: "높음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["와인바", "피티뷰", "소믈리에"],
    why: "피티 궁전이 정면인 와인 바. 소믈리에 형제가 토스카나 소량 생산자를 골라준다 — 와인 애호가의 성지.",
    tips: ["잔 추천은 예산 말하고 맡기기", "안주는 살루미 보드"],
    menuHints: ["키안티 클라시코", "브루넬로", "살루미 보드"],
    watchOut: ["잔당 가격대 높은 편"],
    pairWith: ["pitti-boboli", "osteria-dell-enoteca"],
    sourceIds: ["curious-appetite"],
  },
  {
    id: "le-volpi-e-luva",
    city: "florence",
    name: "Le Volpi e l'Uva",
    koName: "레 볼피 에 루바",
    category: "food",
    area: "폰테베키오 남단",
    lat: 43.7670,
    lng: 11.2531,
    priority: 2,
    rank: 74,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "오후 늦게 (아페리티보)",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["와인바", "치즈", "테라스"],
    why: "폰테베키오 건너자마자 나오는 작은 광장의 와인 바. 소규모 생산자 와인+치즈·크로스티니 조합이 정평.",
    tips: ["테라스석 선착순", "치즈 플레이트 2인 1개"],
    koreanTips: ["베키오 다리 야경 보기 전 1잔 동선"],
    menuHints: ["내추럴 와인", "치즈 플레이트", "크로스티니"],
    pairWith: ["ponte-vecchio", "pitti-boboli"],
    sourceIds: ["curious-appetite", "timeout-florence"],
  },
  {
    id: "signorvino-firenze",
    city: "florence",
    name: "Signorvino Firenze",
    koName: "시뇨르비노",
    category: "food",
    area: "폰테베키오",
    lat: 43.7677,
    lng: 11.2539,
    priority: 3,
    rank: 70,
    durationMin: 70,
    reservation: "권장",
    bestTime: "저녁 (테라스)",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["와인", "베키오뷰", "테라스"],
    why: "폰테베키오가 정면인 테라스 와인숍 겸 식당. 뷰 좋은 자리 중 가격이 현실적인 드문 곳.",
    tips: ["테라스는 예약 필수급", "와인은 숍 가격+콜키지 개념"],
    menuHints: ["글라스 와인", "토스카나 플래터", "파스타"],
    pairWith: ["ponte-vecchio", "uffizi"],
    sourceIds: ["timeout-florence"],
  },
  {
    id: "gelateria-santa-trinita",
    city: "florence",
    name: "Gelateria Santa Trinita",
    koName: "산타 트리니타 젤라또",
    category: "cafe",
    area: "산타 트리니타 다리",
    lat: 43.7686,
    lng: 11.2492,
    priority: 2,
    rank: 75,
    durationMin: 20,
    reservation: "불필요",
    bestTime: "해질녘 (다리 일몰 조합)",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["젤라또", "강변", "일몰조합"],
    why: "산타 트리니타 다리 옆 — 젤라또 들고 다리에서 폰테베키오 일몰을 보는 공식 코스. 흑임자(세사모 네로)가 유명.",
    tips: ["세사모 네로+피스타치오 조합", "일몰 30분 전 구매"],
    koreanTips: ["흑임자 맛이 한국인 취향 저격"],
    menuHints: ["세사모 네로", "피스타치오", "리코타 무화과"],
    pairWith: ["ponte-vecchio", "via-tornabuoni"],
    sourceIds: ["girl-in-florence", "timeout-florence"],
  },
  {
    id: "my-sugar",
    city: "florence",
    name: "My Sugar",
    koName: "마이 슈가",
    category: "cafe",
    area: "산 로렌초",
    lat: 43.7768,
    lng: 11.2554,
    priority: 3,
    rank: 72,
    durationMin: 20,
    reservation: "불필요",
    bestTime: "아카데미아 전후",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["젤라또", "소량생산", "수제"],
    why: "부부가 매일 소량만 만드는 장인 젤라테리아. 통이 비면 그날 장사 끝 — 신선도가 무기다.",
    tips: ["오후 늦으면 인기 맛 소진", "컵 소 사이즈도 충분"],
    menuHints: ["크레마 마이 슈가", "피스타치오", "초콜릿 럼"],
    pairWith: ["accademia", "mercato-centrale"],
    sourceIds: ["girl-in-florence"],
  },
  {
    id: "san-marco-museum",
    city: "florence",
    name: "Museo di San Marco",
    koName: "산 마르코 미술관",
    category: "attraction",
    area: "산 마르코",
    lat: 43.7781,
    lng: 11.2589,
    priority: 3,
    rank: 77,
    durationMin: 70,
    reservation: "불필요",
    bestTime: "오전",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["프라안젤리코", "수도원", "한산", "실내"],
    why: "수도사들의 방마다 프라 안젤리코의 프레스코가 — '수태고지' 원본을 줄 없이 보는 피렌체 최고의 조용한 미술관.",
    tips: ["아카데미아와 도보 3분 묶음", "월요일 휴관 패턴 확인"],
    koreanTips: ["우피치 인파에 지쳤다면 여기가 해독제"],
    pairWith: ["accademia", "my-sugar"],
    sourceIds: ["feelflorence", "lonely-planet-florence"],
  },
  {
    id: "orsanmichele",
    city: "florence",
    name: "Orsanmichele",
    koName: "오르산미켈레 성당",
    category: "attraction",
    area: "시뇨리아/중심",
    lat: 43.7707,
    lng: 11.2549,
    priority: 3,
    rank: 70,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "경유 (두오모-시뇨리아 사이)",
    price: "무료",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["조각", "길드", "무료", "경유"],
    why: "곡물창고였다가 성당이 된 독특한 건물. 외벽 벽감의 길드 수호성인 조각(도나텔로 등)이 야외 조각 교과서.",
    tips: ["외벽 조각만 봐도 충분", "두오모→시뇨리아 이동 중 5분"],
    pairWith: ["duomo-florence", "piazza-signoria"],
    sourceIds: ["feelflorence"],
  },
  {
    id: "santo-spirito-basilica",
    city: "florence",
    name: "Basilica di Santo Spirito",
    koName: "산토 스피리토 성당",
    category: "attraction",
    area: "산토 스피리토",
    lat: 43.7669,
    lng: 11.2474,
    priority: 3,
    rank: 73,
    durationMin: 40,
    reservation: "불필요",
    bestTime: "오전 또는 광장 저녁",
    price: "무료",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["브루넬레스키", "미켈란젤로", "광장", "무료"],
    why: "브루넬레스키 최후의 걸작 성당. 17세 미켈란젤로가 조각한 목제 십자가가 안에 있고, 앞 광장은 저녁마다 동네 사랑방.",
    tips: ["내부 십자가는 성구실 쪽", "광장 아페리티보와 묶기"],
    pairWith: ["osteria-santo-spirito", "trattoria-la-casalinga"],
    sourceIds: ["feelflorence", "lonely-planet-florence"],
  },
];
