import type { PlaceCategory } from "./data";

export type PlaceEnhancement = {
  shortLabel?: string;
  /** 원어명을 한국어로 읽을 때의 발음 */
  pronunciation?: string;
  wikiTitle?: string;
  imageUrl?: string;
  imageCredit?: string;
  imageSourceUrl?: string;
  /** 상세 카드용 풀 설명 — 블로그/여행지 평판 리서치 기반 2-4문장 */
  story?: string;
  google?: {
    rating: number;
    reviewCountLabel: string;
    lastChecked?: string; // "YYYY-MM-DD" — 값을 수동 입력/확인한 날짜
    priceLevel?: "무료" | "€" | "€€" | "€€€" | "€€€€";
    crowdLevel?: "낮음" | "보통" | "높음" | "매우 높음";
    visitConfidence?: "검증 강함" | "검증 보통" | "취향 탐";
  };
  highlights?: string[];
  reviewSignals?: string[];
  bestFor?: string[];
};

export const categoryShortLabels: Record<PlaceCategory, string> = {
  stay: "숙소",
  station: "역",
  attraction: "명소",
  food: "맛집",
  cafe: "카페",
  shopping: "쇼핑",
  view: "전망",
  rest: "휴식",
};

export const placeEnhancements: Record<string, PlaceEnhancement> = {
  "colosseum-forum": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseo_2020.jpg/330px-Colosseo_2020.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Colosseum",
    story:
      "서기 80년 완공된 5만 석 원형경기장과 로마 제국의 심장부 유적을 한 동선으로 묶은 코스. 입장권 하나로 콜로세움, 포로 로마노, 팔라티노 언덕을 모두 돌며 검투사 경기장 지하 구조와 개선문까지 반나절이 꽉 찬다. 예약 시간대 입장이라 시간 엄수가 핵심.",
    shortLabel: "콜로세움",
    wikiTitle: "Colosseum",
    google: { lastChecked: "2026-06-10", rating: 4.7, reviewCountLabel: "40만+", priceLevel: "€€", crowdLevel: "매우 높음", visitConfidence: "검증 강함" },
    highlights: ["고대 로마 대표", "예약 필수", "반나절 코스"],
    reviewSignals: ["사진 만족도 높음", "입장 줄/보안검색 변수", "한낮 더위 피하기"],
    bestFor: ["첫 로마", "역사", "사진"],
  },
  pantheon: {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Pantheon_%28Rome%29_-_Right_side_and_front.jpg/330px-Pantheon_%28Rome%29_-_Right_side_and_front.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Pantheon%2C_Rome",
    story:
      "서기 126년경 하드리아누스 황제가 재건한 신전으로, 2천 년 가까이 무보강 콘크리트 돔 세계 최대 기록을 지키고 있다. 돔 꼭대기 9m 오쿨루스로 쏟아지는 빛이 하이라이트이며, 라파엘로의 무덤도 이곳에 있다.",
    shortLabel: "판테온",
    wikiTitle: "Pantheon, Rome",
    google: { lastChecked: "2026-06-10", rating: 4.8, reviewCountLabel: "25만+", priceLevel: "€", crowdLevel: "매우 높음", visitConfidence: "검증 강함" },
    highlights: ["중심부 루트 허브", "실내 대체 가능", "짧고 강한 코스"],
    reviewSignals: ["광장 혼잡", "비 오는 날 만족도 높음", "나보나/트레비와 묶기 좋음"],
    bestFor: ["중심부", "비 오는 날", "짧은 관람"],
  },
  "trevi-fountain": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Trevi_Fountain_-_Roma.jpg/330px-Trevi_Fountain_-_Roma.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Trevi_Fountain",
    story:
      "1762년 완공된 바로크 분수의 최고 걸작. 등을 돌리고 동전을 던지면 로마에 다시 온다는 전설 덕에 하루 종일 인파가 몰린다. 이른 아침이나 밤 10시 이후가 그나마 한산하다.",
    shortLabel: "트레비",
    wikiTitle: "Trevi Fountain",
    google: { lastChecked: "2026-06-10", rating: 4.8, reviewCountLabel: "40만+", priceLevel: "무료", crowdLevel: "매우 높음", visitConfidence: "검증 강함" },
    highlights: ["사진 스팟", "무료", "짧은 체류"],
    reviewSignals: ["혼잡도 매우 높음", "아침 일찍 추천", "소매치기 주의"],
    bestFor: ["사진", "야경", "중심부 산책"],
  },
  "spanish-steps": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Piazza_di_Spagna_%28Rome%29_0004.jpg/330px-Piazza_di_Spagna_%28Rome%29_0004.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Spanish_Steps",
    story:
      "135개 계단이 트리니타 데이 몬티 성당까지 이어지는 '로마의 거실'. 영화 '로마의 휴일'로 유명해졌고 아래로는 콘도티 명품 거리가 뻗는다. 계단 착석은 벌금 대상이니 주의.",
    shortLabel: "스페인",
    wikiTitle: "Spanish Steps",
    google: { lastChecked: "2026-06-10", rating: 4.5, reviewCountLabel: "8만+", priceLevel: "무료", crowdLevel: "높음", visitConfidence: "검증 보통" },
    highlights: ["쇼핑 동선", "사진 스팟", "중심부 산책"],
    reviewSignals: ["계단 착석 금지", "쇼핑백 관리", "트레비와 도보 연결"],
    bestFor: ["쇼핑", "사진", "저녁 산책"],
  },
  "piazza-navona": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Piazza_Navona_%28Rome%29_at_night.jpg/330px-Piazza_Navona_%28Rome%29_at_night.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Piazza_Navona",
    story:
      "고대 도미티아누스 경기장 터 위에 세워진 바로크 광장. 베르니니의 4대 강 분수와 거리 화가, 보로미니의 성당이 어우러져 해질녘 산책 1순위로 꼽힌다.",
    shortLabel: "나보나",
    wikiTitle: "Piazza Navona",
    google: { lastChecked: "2026-06-10", rating: 4.7, reviewCountLabel: "18만+", priceLevel: "무료", crowdLevel: "높음", visitConfidence: "검증 강함" },
    highlights: ["광장 산책", "해질녘", "판테온 근처"],
    reviewSignals: ["광장 앞 식당 가격 확인", "사진 찍기 좋음", "소매치기 주의"],
    bestFor: ["해질녘", "중심부", "카페"],
  },
  "vatican-museums": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Sistina-interno.jpg/330px-Sistina-interno.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Sistine_Chapel",
    story:
      "교황들이 500년간 모은 인류 최대급 컬렉션. 라파엘로의 방과 지도의 갤러리를 지나 시스티나 성당의 미켈란젤로 천장화로 끝나는 동선이며, 제대로 보면 반나절이 모자란다. 시간 지정 예약과 복장 규정(어깨·무릎 가림)이 필수.",
    shortLabel: "바티칸",
    wikiTitle: "Vatican Museums",
    google: { lastChecked: "2026-06-10", rating: 4.6, reviewCountLabel: "18만+", priceLevel: "€€€", crowdLevel: "매우 높음", visitConfidence: "검증 강함" },
    highlights: ["예약 필수", "시스티나 성당", "반나절 이상"],
    reviewSignals: ["입장 시간 엄격", "체력 소모 큼", "대표 작품 우선순위 필요"],
    bestFor: ["미술", "실내", "고정 일정"],
  },
  "st-peters-basilica": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg/330px-Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/St._Peter's_Basilica",
    story:
      "가톨릭의 총본산이자 세계 최대 성당. 미켈란젤로의 피에타와 베르니니의 발다키노가 내부에 있고, 쿠폴라(551계단)에 오르면 바티칸과 로마 전경이 한눈에 담긴다. 입장은 무료지만 보안 검색 줄이 길다.",
    shortLabel: "성베드로",
    wikiTitle: "St. Peter's Basilica",
    google: { lastChecked: "2026-06-10", rating: 4.8, reviewCountLabel: "15만+", priceLevel: "무료", crowdLevel: "매우 높음", visitConfidence: "검증 강함" },
    highlights: ["복장 체크", "바티칸 핵심", "사진 스팟"],
    reviewSignals: ["줄 길 수 있음", "성당 복장 필요", "호객 투어 주의"],
    bestFor: ["성당", "바티칸", "사진"],
  },
  "castel-sant-angelo": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Castel_Sant%27_Angelo_Between_Leaves.jpg/330px-Castel_Sant%27_Angelo_Between_Leaves.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Castel_Sant'Angelo",
    story:
      "하드리아누스 황제의 영묘로 지어져 요새, 교황 피난처, 감옥을 거친 2천 년 건물. 천사의 다리에서 보는 외관과 옥상 테라스의 강 전망이 핵심으로, 해질녘이 가장 아름답다.",
    shortLabel: "산탄젤로",
    wikiTitle: "Castel Sant'Angelo",
    google: { lastChecked: "2026-06-10", rating: 4.7, reviewCountLabel: "9만+", priceLevel: "€€", crowdLevel: "높음", visitConfidence: "검증 보통" },
    highlights: ["전망", "강변 산책", "바티칸 근처"],
    reviewSignals: ["해질녘 만족도 높음", "체력 남을 때 내부", "다리 사진 좋음"],
    bestFor: ["전망", "해질녘", "강변"],
  },
  trastevere: {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Santa_Maria_in_Trastevere_fountain.jpg/330px-Santa_Maria_in_Trastevere_fountain.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Trastevere",
    story:
      "테베레 강 건너의 옛 서민 동네. 담쟁이 골목과 자갈길, 광장 성당, 늦은 밤까지 도는 트라토리아가 로마의 '저녁 분위기'를 책임진다. 식당은 예약해 두고 골목은 발 가는 대로 걷는 게 정석.",
    shortLabel: "트라스테베레",
    wikiTitle: "Trastevere",
    google: { lastChecked: "2026-06-10", rating: 4.6, reviewCountLabel: "권역 리뷰 다수", priceLevel: "€€", crowdLevel: "높음", visitConfidence: "검증 강함" },
    highlights: ["저녁 분위기", "맛집 권역", "골목 사진"],
    reviewSignals: ["밤 귀가 경로 확인", "예약 식당 기준으로 걷기", "외진 골목 주의"],
    bestFor: ["저녁", "분위기", "맛집"],
  },
  "villa-borghese": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Ingresso_monumentale_di_Villa_Borghese_a_Roma_su_piazzale_Flaminio_2018-02.jpg/330px-Ingresso_monumentale_di_Villa_Borghese_a_Roma_su_piazzale_Flaminio_2018-02.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Villa_Borghese_gardens",
    shortLabel: "보르게세",
    wikiTitle: "Villa Borghese gardens",
    google: { lastChecked: "2026-06-10", rating: 4.6, reviewCountLabel: "8만+", priceLevel: "무료", crowdLevel: "보통", visitConfidence: "검증 보통" },
    highlights: ["공원", "핀초 전망", "휴식"],
    reviewSignals: ["해질녘 좋음", "어두워지면 큰길", "스페인 계단과 연결"],
    bestFor: ["휴식", "전망", "산책"],
  },
  "borghese-gallery": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Galleria_Borghese_-_logo_%28Italy%2C_2022-%29.svg/330px-Galleria_Borghese_-_logo_%28Italy%2C_2022-%29.svg.png",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Galleria_Borghese",
    story:
      "베르니니의 '아폴로와 다프네'와 카라바조 진품 여러 점이 한 건물에 모인, 밀도로는 로마 최강의 미술관. 2시간 단위 완전 예약제라 입장 시간을 그날 일정의 축으로 삼아야 한다.",
    shortLabel: "보르게세",
    wikiTitle: "Galleria Borghese",
    google: { lastChecked: "2026-06-10", rating: 4.6, reviewCountLabel: "2만+", priceLevel: "€€€", crowdLevel: "높음", visitConfidence: "검증 강함" },
    highlights: ["예약 필수", "실내 미술관", "공원과 묶기"],
    reviewSignals: ["입장 시간 엄격", "작품 밀도 높음", "바티칸과 같은 날은 과함"],
    bestFor: ["미술", "비 오는 날", "체력 아낌"],
  },
  "campo-de-fiori": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Campo_dei_Fiori.jpg/330px-Campo_dei_Fiori.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Campo_de'_Fiori",
    story:
      "아침엔 청과·향신료 시장, 밤엔 광장 바로 변하는 두 얼굴의 광장. 시장 구경 후 모퉁이 빵집의 피자 비앙카로 마무리하는 게 공식 코스다.",
    shortLabel: "캄포",
    wikiTitle: "Campo de' Fiori",
    highlights: ["시장", "중심부 연결", "짧은 산책"],
    reviewSignals: ["오전 시장", "밤 분위기 확인", "식당은 후기 확인"],
    bestFor: ["시장", "나보나 근처", "간식"],
  },
  "piazza-del-popolo": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/PIAZZA_DEL_POPOLO_VISTA_AEREA.jpg/330px-PIAZZA_DEL_POPOLO_VISTA_AEREA.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Piazza_del_Popolo",
    shortLabel: "포폴로",
    wikiTitle: "Piazza del Popolo",
    highlights: ["광장", "핀초 언덕", "쇼핑 연결"],
    reviewSignals: ["넓어서 사진 편함", "공연 주변 소지품 주의", "스페인 계단과 연결"],
    bestFor: ["사진", "산책", "전망"],
  },
  "capitoline-museums": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/0_Cordonata_-_Dioscuri_-_Palazzo_Senatorio.JPG/330px-0_Cordonata_-_Dioscuri_-_Palazzo_Senatorio.JPG",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Capitoline_Museums",
    shortLabel: "카피톨리니",
    wikiTitle: "Capitoline Museums",
    highlights: ["실내", "고대 로마", "비 오는 날"],
    reviewSignals: ["콜로세움 뒤 대체", "관람 피로 관리", "베네치아 광장과 연결"],
    bestFor: ["비", "역사", "실내"],
  },
  "altare-patria": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Piazza_Venezia_-_Il_Vittoriano_%28cropped%29.jpg/330px-Piazza_Venezia_-_Il_Vittoriano_%28cropped%29.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Victor_Emmanuel_II_Monument",
    shortLabel: "기념관",
    wikiTitle: "Victor Emmanuel II Monument",
    highlights: ["전망", "중심부", "사진"],
    reviewSignals: ["광장 횡단 주의", "전망대 여부 확인", "콜로세움 전후 연결"],
    bestFor: ["전망", "사진", "중심부"],
  },
  "santa-maria-maggiore": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Basilica_di_Santa_Maria_Maggiore_-_Roma.jpg/330px-Basilica_di_Santa_Maria_Maggiore_-_Roma.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Santa_Maria_Maggiore",
    shortLabel: "마조레",
    wikiTitle: "Santa Maria Maggiore",
    highlights: ["역 근처", "성당", "실내"],
    reviewSignals: ["복장 체크", "기차 전후 시간 활용", "역 주변 소지품 주의"],
    bestFor: ["기차 전후", "성당", "실내"],
  },
  "baths-caracalla": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Baths_of_Caracalla%2C_facing_Caldarium.jpg/330px-Baths_of_Caracalla%2C_facing_Caldarium.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Baths_of_Caracalla",
    shortLabel: "카라칼라",
    wikiTitle: "Baths of Caracalla",
    highlights: ["고대 유적", "덜 붐빔", "사진"],
    reviewSignals: ["그늘 적음", "한낮 피하기", "대중교통 확인"],
    bestFor: ["유적", "사진", "한적함"],
  },
  "orange-garden": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Giardino_degli_Aranci.JPG/330px-Giardino_degli_Aranci.JPG",
    imageSourceUrl: "https://it.wikipedia.org/wiki/Giardino_degli_Aranci",
    shortLabel: "오렌지",
    wikiTitle: "Giardino degli Aranci",
    highlights: ["전망", "무료", "휴식"],
    reviewSignals: ["해질녘 좋음", "밤 늦게 오래 머물지 않기", "테베레섬과 연결"],
    bestFor: ["전망", "휴식", "사진"],
  },
  "duomo-florence": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Cattedrale_di_Santa_Maria_del_Fiore_%E2%80%93_Il_Duomo_di_Firenze.jpg/330px-Cattedrale_di_Santa_Maria_del_Fiore_%E2%80%93_Il_Duomo_di_Firenze.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Florence_Cathedral",
    story:
      "공식 명칭 산타 마리아 델 피오레. 브루넬레스키의 붉은 쿠폴라(463계단)는 르네상스 공학의 상징이고, 브루넬레스키 패스 하나로 쿠폴라·종탑·세례당·박물관을 묶어 본다. 쿠폴라는 시간 지정 예약 필수.",
    shortLabel: "두오모",
    wikiTitle: "Florence Cathedral",
    google: { lastChecked: "2026-06-10", rating: 4.8, reviewCountLabel: "10만+", priceLevel: "€€", crowdLevel: "매우 높음", visitConfidence: "검증 강함" },
    highlights: ["피렌체 핵심", "예약", "쿠폴라/종탑"],
    reviewSignals: ["쿠폴라 체력 소모", "복장 체크", "광장 혼잡"],
    bestFor: ["첫 피렌체", "사진", "랜드마크"],
  },
  uffizi: {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Florence%2C_Italy_-_panoramio_%28125%29.jpg/330px-Florence%2C_Italy_-_panoramio_%28125%29.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Uffizi",
    story:
      "메디치 가문 컬렉션에서 출발한 르네상스 회화의 본진. 보티첼리의 '비너스의 탄생'과 '프리마베라', 다빈치 초기작이 핵심이며 성수기엔 예약 없이는 긴 줄을 각오해야 한다.",
    shortLabel: "우피치",
    wikiTitle: "Uffizi",
    google: { lastChecked: "2026-06-10", rating: 4.7, reviewCountLabel: "8만+", priceLevel: "€€€", crowdLevel: "매우 높음", visitConfidence: "검증 강함" },
    highlights: ["예약 필수", "핵심 미술관", "반나절"],
    reviewSignals: ["대표 작품 위주", "관람 후 휴식 필요", "가방 규정 확인"],
    bestFor: ["미술", "실내", "고정 일정"],
  },
  accademia: {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/David_at_the_Galleria_dell%27Accademia_%2861351%29.jpg/330px-David_at_the_Galleria_dell%27Accademia_%2861351%29.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Galleria_dell'Accademia",
    story:
      "미켈란젤로의 다비드 원본 하나로 존재 이유가 충분한 미술관. 미완성 '노예' 연작이 다비드로 가는 복도에 도열해 조각이 돌에서 풀려나는 과정을 보여준다. 관람 자체는 1시간이면 충분.",
    shortLabel: "아카데미아",
    wikiTitle: "Galleria dell'Accademia",
    google: { lastChecked: "2026-06-10", rating: 4.6, reviewCountLabel: "4만+", priceLevel: "€€", crowdLevel: "높음", visitConfidence: "검증 강함" },
    highlights: ["다비드", "예약", "짧고 강함"],
    reviewSignals: ["예약 시간 중요", "두오모와 묶기", "짧게 보기 좋음"],
    bestFor: ["다비드", "미술", "두오모 권역"],
  },
  "ponte-vecchio": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Ponte_Vecchio_from_Ponte_alle_Grazie.jpg/330px-Ponte_Vecchio_from_Ponte_alle_Grazie.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Ponte_Vecchio",
    story:
      "1345년부터 아르노강을 지킨 피렌체에서 가장 오래된 다리. 다리 위엔 금세공 상점이 줄지어 있고 머리 위로는 메디치의 비밀 통로인 바사리 회랑이 지난다. 다리 위보다 옆 다리(산타 트리니타)에서 보는 모습이 사진 포인트.",
    shortLabel: "베키오",
    wikiTitle: "Ponte Vecchio",
    google: { lastChecked: "2026-06-10", rating: 4.7, reviewCountLabel: "14만+", priceLevel: "무료", crowdLevel: "매우 높음", visitConfidence: "검증 강함" },
    highlights: ["강변", "해질녘", "무료"],
    reviewSignals: ["다리 위 혼잡", "강변 사진 추천", "올트라르노 연결"],
    bestFor: ["산책", "사진", "해질녘"],
  },
  "piazza-signoria": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Piazza_Signoria_-_Firenze.jpg/330px-Piazza_Signoria_-_Firenze.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Piazza_della_Signoria",
    story:
      "베키오 궁전 앞의 야외 조각 미술관급 광장. 다비드 복제상, 넵튠 분수, 란치 회랑의 조각들이 무료로 펼쳐져 있어 피렌체 동선의 허브가 된다.",
    shortLabel: "시뇨리아",
    wikiTitle: "Piazza della Signoria",
    google: { lastChecked: "2026-06-10", rating: 4.8, reviewCountLabel: "8만+", priceLevel: "무료", crowdLevel: "높음", visitConfidence: "검증 강함" },
    highlights: ["광장", "우피치 근처", "야외 조각"],
    reviewSignals: ["광장 카페 가격 확인", "소지품 주의", "우피치 전후에 좋음"],
    bestFor: ["우피치", "광장", "사진"],
  },
  "piazzale-michelangelo": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Blick_auf_und_vom_Piazzale_Michelangelo_%28LM28908%29.jpg/330px-Blick_auf_und_vom_Piazzale_Michelangelo_%28LM28908%29.jpg",
    imageSourceUrl: "https://it.wikipedia.org/wiki/Piazzale_Michelangelo",
    story:
      "아르노강 남쪽 언덕의 전망 광장. 두오모, 베키오궁, 폰테베키오가 한 프레임에 담기는 피렌체 대표 일몰 포인트로, 해 지기 40분 전 도착이 정석이다.",
    shortLabel: "미켈란젤로",
    wikiTitle: "Piazzale Michelangelo",
    google: { lastChecked: "2026-06-10", rating: 4.8, reviewCountLabel: "10만+", priceLevel: "무료", crowdLevel: "매우 높음", visitConfidence: "검증 강함" },
    highlights: ["피렌체 전망", "해질녘", "사진"],
    reviewSignals: ["오르막", "해진 뒤 복귀 경로", "버스/택시 고려"],
    bestFor: ["전망", "사진", "해질녘"],
  },
  "pitti-boboli": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Palazzo_Pitti_nel_tardo_pomeriggio.jpg/330px-Palazzo_Pitti_nel_tardo_pomeriggio.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Palazzo_Pitti",
    story:
      "메디치가 살던 거대한 피티 궁전과 그 뒤의 보볼리 정원. 팔라티나 미술관의 라파엘로 밀도는 우피치 다음으로 꼽히고, 정원은 르네상스식 정원의 교과서다. 한여름 정원은 그늘이 적으니 아침에.",
    shortLabel: "피티",
    wikiTitle: "Pitti Palace",
    highlights: ["궁전", "정원", "올트라르노"],
    reviewSignals: ["더운 한낮 피하기", "체력 소모", "보볼리와 시간 관리"],
    bestFor: ["정원", "궁전", "올트라르노"],
  },
  "santa-croce": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Basilica_di_Santa_Croce_%2812437%29.jpg/330px-Basilica_di_Santa_Croce_%2812437%29.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Santa_Croce%2C_Florence",
    story:
      "미켈란젤로, 갈릴레이, 마키아벨리가 잠든 '이탈리아의 판테온'. 조토의 프레스코가 남아 있고, 부속 가죽학교까지 같은 단지에 있다.",
    shortLabel: "산타크로체",
    wikiTitle: "Basilica of Santa Croce, Florence",
    highlights: ["성당", "실내", "산타 크로체 권역"],
    reviewSignals: ["복장 체크", "우피치 후 체력 확인", "젤라또와 묶기"],
    bestFor: ["성당", "비", "동쪽 권역"],
  },
  "mercato-centrale": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Mercato_centrale_di_san_lorenzo_01.jpg/330px-Mercato_centrale_di_san_lorenzo_01.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Mercato_Centrale_(Florence)",
    story:
      "1874년 철골 구조의 중앙시장. 1층은 정육·치즈·식재료 시장, 2층은 푸드코트로, 네르보네 곱창버거부터 트러플 파스타까지 한 지붕에서 해결된다.",
    shortLabel: "중앙시장",
    wikiTitle: "Mercato Centrale (Florence)",
    google: { lastChecked: "2026-06-10", rating: 4.4, reviewCountLabel: "5만+", priceLevel: "€€", crowdLevel: "높음", visitConfidence: "검증 보통" },
    highlights: ["푸드홀", "역 근처", "비상식사"],
    reviewSignals: ["자리 확보 먼저", "혼잡 소지품 주의", "예약 실패 대안"],
    bestFor: ["점심", "가성비", "비상식사"],
  },
  "bargello": {
    shortLabel: "바르젤로",
    wikiTitle: "Bargello",
    highlights: ["조각", "실내", "비 오는 날"],
    reviewSignals: ["미술관 피로 관리", "우피치 다음 단계", "짧게 보기 가능"],
    bestFor: ["미술", "비", "조각"],
  },
  "medici-chapels": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Medicibib.jpg/330px-Medicibib.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Medici_Chapels",
    shortLabel: "메디치",
    wikiTitle: "Medici Chapel",
    highlights: ["메디치", "실내", "중앙시장 근처"],
    reviewSignals: ["두오모 권역과 묶기", "운영시간 확인", "역사 취향이면 좋음"],
    bestFor: ["역사", "실내", "두오모"],
  },
  "santa-maria-novella-basilica": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Florence%2C_Santa_Maria_Novella%2C_facade.jpg/330px-Florence%2C_Santa_Maria_Novella%2C_facade.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Santa_Maria_Novella",
    shortLabel: "SMN성당",
    wikiTitle: "Santa Maria Novella",
    highlights: ["역 근처", "성당", "SMN 약국"],
    reviewSignals: ["기차 전후 좋음", "복장 체크", "역 주변 소지품 주의"],
    bestFor: ["도착일", "출발일", "성당"],
  },
  "san-miniato-al-monte": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/San_Miniato_al_Monte%2C_exterior%2C_Florencia%2C_Italia%2C_2019_01_cropped.jpg/330px-San_Miniato_al_Monte%2C_exterior%2C_Florencia%2C_Italia%2C_2019_01_cropped.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/San_Miniato_al_Monte",
    shortLabel: "산미니아토",
    wikiTitle: "San Miniato al Monte",
    highlights: ["전망", "성당", "조용함"],
    reviewSignals: ["오르막", "해진 뒤 복귀", "미켈란젤로와 묶기"],
    bestFor: ["전망", "성당", "사진"],
  },
  "bardini-garden": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Giardino_bardini%2C_terrazze_della_scalinata_principale%2C_05.jpg/330px-Giardino_bardini%2C_terrazze_della_scalinata_principale%2C_05.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Bardini_Gardens",
    shortLabel: "바르디니",
    wikiTitle: "Giardino Bardini",
    highlights: ["정원", "전망", "사진"],
    reviewSignals: ["날씨 영향", "오르막", "보볼리보다 작고 집중형"],
    bestFor: ["사진", "정원", "올트라르노"],
  },
  "trattoria-sostanza": {
    story:
      "1869년 개업, 테이블 공유가 전통인 피렌체 노포. 버터 치킨(폴로 알 부로)과 아티초크 토르티노 두 접시로 150년을 버텼다. 현금만 받는 점 주의.",
    shortLabel: "Sostanza",
    google: { lastChecked: "2026-06-10", rating: 4.5, reviewCountLabel: "2천+", priceLevel: "€€€", crowdLevel: "높음", visitConfidence: "검증 강함" },
    highlights: ["예약 필수", "버터치킨", "피렌체 클래식"],
    reviewSignals: ["한국인 입맛 가능성 높음", "예약 난도", "가격대 확인"],
    bestFor: ["저녁", "클래식", "둘이 식사"],
  },
  "bonci-pizzarium": {
    story:
      "'피자의 미켈란젤로'로 불리는 가브리엘레 본치의 조각 피자 본점. 무게 단위로 잘라 파는 알 탈리오 방식이며, 바티칸 박물관에서 도보 10분이라 관람 전후로 최적.",
    shortLabel: "Bonci",
    google: { lastChecked: "2026-06-10", rating: 4.3, reviewCountLabel: "8천+", priceLevel: "€€", crowdLevel: "높음", visitConfidence: "검증 보통" },
    highlights: ["바티칸 근처", "피자 al taglio", "간단식"],
    reviewSignals: ["무게 계산", "웨이팅 가능", "좌석 기대 낮추기"],
    bestFor: ["바티칸", "간단 점심", "피자"],
  },
  "vini-e-vecchi-sapori": {
    shortLabel: "Vini",
    google: { lastChecked: "2026-06-10", rating: 4.6, reviewCountLabel: "1천+", priceLevel: "€€", crowdLevel: "높음", visitConfidence: "검증 강함" },
    highlights: ["시뇨리아", "예약", "전통식"],
    reviewSignals: ["우피치 후 동선 좋음", "예약 난도", "메뉴 가격 확인"],
    bestFor: ["저녁", "우피치", "전통식"],
  },
  "all-antico-vinaio": {
    story:
      "피렌체에서 시작해 세계로 퍼진 스키아차타 파니니 줄맛집. 라 파보로사(프로슈토+트러플 크림)가 시그니처로, 우피치 옆 골목 본점은 줄이 길어도 회전이 빠르다.",
    shortLabel: "Vinaio",
    google: { lastChecked: "2026-06-10", rating: 4.5, reviewCountLabel: "4만+", priceLevel: "€", crowdLevel: "매우 높음", visitConfidence: "검증 보통" },
    highlights: ["샌드위치", "유명", "간단식"],
    reviewSignals: ["줄 길면 스킵", "먹을 장소 생각", "간단 점심 대체"],
    bestFor: ["간식", "빠른 점심", "우피치 근처"],
  },
  "la-menagere": {
    story:
      "철물점을 개조한 콘셉트 카페 겸 레스토랑, 플라워샵. 피렌체 '예쁜 브런치'의 대명사라 아침 일찍 가야 자리가 있다.",
    shortLabel: "Menagere",
    google: { lastChecked: "2026-06-10", rating: 4.3, reviewCountLabel: "8천+", priceLevel: "€€", crowdLevel: "높음", visitConfidence: "검증 보통" },
    highlights: ["브런치", "사진", "카페"],
    reviewSignals: ["피크 시간 혼잡", "두오모 전후", "한국 카페 감성"],
    bestFor: ["휴식", "브런치", "사진"],
  },
  "bocca-della-verita": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Et%C3%A0_imperiale%2C_chiusino_a_forma_di_mascherone_di_divinit%C3%A0_fluviale%2C_detta_bocca_della_verit%C3%A0%2C_collocata_qui_nel_1632.jpg/330px-Et%C3%A0_imperiale%2C_chiusino_a_forma_di_mascherone_di_divinit%C3%A0_fluviale%2C_detta_bocca_della_verit%C3%A0%2C_collocata_qui_nel_1632.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Bocca_della_Verit%C3%A0",
    shortLabel: "진실의입",
    wikiTitle: "Bocca della Verità",
    highlights: ["로마의 휴일", "인증샷", "아벤티노 묶음"],
    bestFor: ["사진", "영화 따라가기", "짧은 코스"],
  },
  "sant-ignazio": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Church_of_Sant%27Ignazio_di_Loyola.jpg/330px-Church_of_Sant%27Ignazio_di_Loyola.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Sant'Ignazio%2C_Rome",
    shortLabel: "산티냐치오",
    wikiTitle: "Sant'Ignazio, Rome",
    highlights: ["가짜 돔 천장화", "무료", "판테온 3분"],
    bestFor: ["비 오는 날", "사진", "중심부"],
  },
  "galleria-sciarra": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Galleria_Sciarra.jpg/330px-Galleria_Sciarra.jpg",
    imageSourceUrl: "https://it.wikipedia.org/wiki/Galleria_Sciarra",
    shortLabel: "시아라",
    wikiTitle: "Galleria Sciarra",
    highlights: ["숨은 아르누보 중정", "트레비 2분", "한적"],
    bestFor: ["사진", "숨은 스팟"],
  },
  "via-margutta": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Via_Marguta_Rome.jpg/330px-Via_Marguta_Rome.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Via_Margutta",
    shortLabel: "마르구타",
    wikiTitle: "Via Margutta",
    highlights: ["예술가 골목", "로마의 휴일", "조용한 산책"],
    bestFor: ["사진", "산책", "한적함"],
  },
  "aventine-keyhole": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Aventino_s_Maria_del_Priorato_villa_dal_giardino_1050419.JPG/330px-Aventino_s_Maria_del_Priorato_villa_dal_giardino_1050419.JPG",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Villa_del_Priorato_di_Malta",
    shortLabel: "열쇠구멍",
    wikiTitle: "Villa del Priorato di Malta",
    highlights: ["열쇠구멍 너머 성 베드로 돔", "무료", "오렌지 정원 3분"],
    bestFor: ["숨은 스팟", "아벤티노 묶음"],
  },
  "pincio-terrace": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Terrazza_del_Pincio_%2846397854832%29.jpg/330px-Terrazza_del_Pincio_%2846397854832%29.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Pincian_Hill",
    shortLabel: "핀초",
    wikiTitle: "Pincian Hill",
    highlights: ["로마 대표 일몰", "무료", "포폴로 광장 위"],
    bestFor: ["해질녘", "사진", "산책"],
  },
  tonnarello: {
    story:
      "트라스테베레의 한국인 인지도 1위 식당. 까르보나라와 톤나렐리 면, 기타 라이브 덕에 '로마 첫 저녁' 단골 코스가 됐다. 예약 없이는 30분 이상 대기가 기본.",
    shortLabel: "Tonnarello",
    highlights: ["트라스테베레 인기 1순위", "회전 빠름", "한국인 단골"],
    bestFor: ["저녁", "파스타", "첫 트라스테베레"],
  },
  "osteria-da-fortunata": {
    story:
      "창가에서 수제 파스타를 빚는 모습으로 유명한 캄포 데 피오리 옆 오스테리아. 까르보나라와 카초 에 페페가 한국인 베스트 메뉴다.",
    shortLabel: "Fortunata",
    highlights: ["창가 수타 파스타 시연", "본점 Via del Pellegrino", "캄포 옆"],
    bestFor: ["점심", "파스타", "구경하는 재미"],
  },
  "cantina-e-cucina": {
    shortLabel: "Cantina",
    highlights: ["한국인 리뷰 다수", "친절", "나보나 근처"],
    bestFor: ["첫 끼", "저녁", "무난한 선택"],
  },
  "pompi-tiramisu": {
    story:
      "1960년부터 '티라미수의 집'으로 불린 로마 디저트 명가. 클래식 외에 피스타치오, 딸기 변형도 강하고 스페인 계단 근처 지점이 동선에 편하다.",
    shortLabel: "Pompi",
    highlights: ["로마 티라미수 대명사", "테이크아웃", "쇼핑 동선"],
    bestFor: ["간식", "당 충전", "쇼핑 중"],
  },
  "two-sizes-tiramisu": {
    story:
      "나보나 근처의 미니 티라미수 전문점. 두 가지 컵 사이즈에 피스타치오, 솔티드카라멜 등 변형 맛 — 폼피와 양대 산맥으로 묶인다.",
    shortLabel: "TwoSizes",
    highlights: ["컵 티라미수", "가성비", "나보나 산책"],
    bestFor: ["간식", "비교 시식"],
  },
  "da-francesco": {
    shortLabel: "DaFrancesco",
    highlights: ["화덕 피자", "현지 손님 비중", "피코 광장"],
    bestFor: ["저녁", "피자", "나보나 근처"],
  },
  "trattoria-mario": {
    story:
      "1953년부터 중앙시장 앞에서 점심만 파는 합석 트라토리아. 손글씨 메뉴판과 현금 결제, 비스테카와 리볼리타 — 피렌체 점심 문화의 원형이다.",
    shortLabel: "Mario",
    highlights: ["1953년 점심 전용", "비스테카 가성비", "예약 불가 오픈런"],
    bestFor: ["점심", "스테이크", "현지 분위기"],
  },
  "trattoria-zaza": {
    story:
      "중앙시장 광장의 대형 트라토리아. 티본 스테이크와 트러플 파스타를 부담 없는 분위기로 — 한국인 예약 단골집이라 한국어 후기도 많다.",
    shortLabel: "ZaZa",
    highlights: ["중앙시장 광장", "메뉴 폭 넓음", "저녁 예약 필수"],
    bestFor: ["저녁", "스테이크", "단체/테라스"],
  },
  "golden-view": {
    shortLabel: "GoldenView",
    highlights: ["베키오 다리 뷰", "마지막 밤 후보", "창가 예약"],
    bestFor: ["기념 저녁", "뷰", "해질녘"],
  },
  "san-lorenzo-market": {
    shortLabel: "가죽시장",
    highlights: ["노점 가죽시장", "흥정 기본", "기념품"],
    bestFor: ["쇼핑", "기념품", "시장 구경"],
  },
  "palazzo-vecchio": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Piazza_della_signoria%2C_palazzo_vecchio%2C_veduta_01.jpg/330px-Piazza_della_signoria%2C_palazzo_vecchio%2C_veduta_01.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Palazzo_Vecchio",
    shortLabel: "베키오궁",
    wikiTitle: "Palazzo Vecchio",
    highlights: ["아르놀포 탑 전망", "두오모 뷰", "야간 개장 변수"],
    bestFor: ["전망", "역사", "쿠폴라 대안"],
  },
  "edoardo-gelato": {
    shortLabel: "Edoardo",
    highlights: ["유기농 젤라또", "수제 콘", "두오모 앞"],
    bestFor: ["간식", "두오모 전후"],
  },
  fiesole: {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/FiesoleDec102023_15.jpg/330px-FiesoleDec102023_15.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Fiesole",
    shortLabel: "피에솔레",
    wikiTitle: "Fiesole",
    highlights: ["버스 25분 근교", "피렌체 전경", "반나절"],
    bestFor: ["전망", "한적함", "여유일"],
  },

  /* ===== 로마 — 맛집·카페·명소 보강 (2026-06 리서치) ===== */
  "armando-al-pantheon": {
    shortLabel: "아르만도",
    wikiTitle: "Armando al Pantheon",
    story:
      "판테온 돌담 바로 옆에서 1961년부터 한 가족이 지켜온 트라토리아. 관광지 한복판인데도 로마 클래식(카르보나라, 카초 에 페페)을 정석으로 내는 곳으로 꼽혀 미슐랭 가이드에도 꾸준히 오른다. 좌석이 적어 예약 경쟁이 치열하다.",
    highlights: ["판테온 옆 60년 가족 트라토리아", "로마 4대 파스타 정석", "예약 전쟁"],
    reviewSignals: ["몇 주 전 예약 필요", "회전 빠른 점심이 그나마 수월", "양보다 완성도형"],
    bestFor: ["로마 전통 파스타", "기념 식사", "중심부"],
  },
  roscioli: {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Forno_Roscoli%27s_Sign.jpg/330px-Forno_Roscoli%27s_Sign.jpg",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Forno_Roscoli%27s_Sign.jpg",
    imageCredit: "Ph8l / CC BY-SA 3.0",
    shortLabel: "로숄리",
    wikiTitle: "Roscioli",
    story:
      "살루메리아(식료품점)와 레스토랑이 합쳐진 로마 미식의 상징. 카르보나라와 부라타+안초비가 시그니처로, 전 세계 푸드 매체가 '로마 카르보나라 성지'로 인용한다. 빵집(Antico Forno Roscioli)과 카페도 같은 골목에 있다.",
    highlights: ["카르보나라 성지", "살루메리아 겸 레스토랑", "같은 골목 빵집·카페"],
    reviewSignals: ["예약 필수(주말은 수 주 전)", "카운터석은 당일 가능성", "치즈·살루미 추가 주문 만족도 높음"],
    bestFor: ["미식", "카르보나라", "와인"],
  },
  "da-enzo": {
    shortLabel: "다 엔초",
    story:
      "트라스테베레 골목의 작은 전통 트라토리아. 예약을 받지 않아 오픈 30분 전 줄서기가 공식이 됐고, 그만큼 카르보나라·아마트리치아나·티라미수가 '줄 설 가치'로 회자된다.",
    highlights: ["오픈런 명소", "로마 클래식 정석", "티라미수 마무리"],
    reviewSignals: ["예약 불가 — 오픈 전 도착", "웨이팅 1시간+ 흔함", "좁고 시끌벅적한 분위기"],
    bestFor: ["트라스테베레 저녁", "전통 파스타", "현지 분위기"],
  },
  "la-tavernaccia": {
    shortLabel: "타베르나차",
    story: "트라스테베레 남쪽 주택가의 동네 명가. 장작 화덕 라자냐와 새끼돼지 통구이가 유명하고, 관광 동선 밖이라 현지인 비율이 높다.",
    highlights: ["장작 화덕 라자냐", "현지인 단골", "동선 밖 보석"],
    reviewSignals: ["예약 권장", "중심부에서 도보 20분+", "가족 운영 친절"],
    bestFor: ["로컬 분위기", "라자냐", "느긋한 저녁"],
  },
  "trattoria-trecca": {
    shortLabel: "트레카",
    highlights: ["로마 전통 신세대 해석", "내장 요리 강점", "오스티엔세 권역"],
    reviewSignals: ["모험 메뉴는 직원 추천 따라가기", "관광 동선 밖"],
    bestFor: ["로컬 미식", "두 번째 로마"],
  },
  "santo-palato": {
    shortLabel: "산토팔라토",
    highlights: ["스타 셰프 트라토리아", "로마 클래식 재해석", "미식 매체 단골"],
    reviewSignals: ["예약 필수", "산 조반니 권역 — 동선 계획 필요"],
    bestFor: ["미식", "모던 로마 요리"],
  },
  "piatto-romano": {
    shortLabel: "피아토로마노",
    highlights: ["테스타치오 전통식", "제철 채소 강점", "수요일 곱창 전통"],
    reviewSignals: ["시장과 묶기 좋음", "내장 요리는 호불호"],
    bestFor: ["테스타치오", "전통 로마식"],
  },
  "hosteria-grappolo-doro": {
    shortLabel: "그라폴로도로",
    highlights: ["캄포 데 피오리 근처", "합리적 가격 전통식", "관광지 한복판 양심집"],
    reviewSignals: ["피크 대기 있음", "파스타 클래식 위주가 안전"],
    bestFor: ["중심부 저녁", "가성비"],
  },
  "felice-testaccio": {
    shortLabel: "펠리체",
    story:
      "1936년부터 테스타치오를 지킨 카초 에 페페의 대명사. 테이블에서 직원이 면을 비벼주는 퍼포먼스로 유명하고, 목요일 뇨키 전통도 지킨다. 예약 없이는 사실상 입장이 어렵다.",
    highlights: ["카초 에 페페 대명사", "테이블 비빔 퍼포먼스", "1936년 전통"],
    reviewSignals: ["예약 필수(앱/전화)", "노쇼 방지 정책 엄격", "티라미수도 평 좋음"],
    bestFor: ["카초 에 페페", "테스타치오 저녁"],
  },
  "forno-campo-de-fiori": {
    shortLabel: "포르노캄포",
    wikiTitle: "Forno Campo de' Fiori",
    highlights: ["피자 비앙카 원조급", "광장 모퉁이 베이커리", "조각 피자 간편"],
    reviewSignals: ["점심 전후 회전 빠름", "서서/걸으며 먹기"],
    bestFor: ["간단 점심", "캄포 데 피오리"],
  },
  pianostrada: {
    shortLabel: "피아노스트라다",
    highlights: ["여성 셰프 크루", "수제 포카치아", "안뜰 좌석"],
    reviewSignals: ["예약 권장", "모던·창작 메뉴 — 전통파엔 비추"],
    bestFor: ["분위기", "creative 다이닝"],
  },
  retrobottega: {
    shortLabel: "레트로보테가",
    highlights: ["모던 파인 캐주얼", "카운터 다이닝", "판테온 근처"],
    reviewSignals: ["가격대 있음", "코스 구성 취향 탐"],
    bestFor: ["미식 모험", "기념일"],
  },
  "testaccio-market": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Porta_San_Paolo_-_Piramid_Cestius.JPG/330px-Porta_San_Paolo_-_Piramid_Cestius.JPG",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Testaccio",
    shortLabel: "테스타치오시장",
    wikiTitle: "Testaccio",
    story: "로마 토박이 동네 테스타치오의 실내 시장. 트라피치노 원조 부스, 수플리, 생면 파스타 부스가 모여 있어 시장 한 바퀴로 로마 스트리트푸드를 정리할 수 있다.",
    highlights: ["스트리트푸드 집결", "트라피치노 원조 부스", "현지 장보기 구경"],
    reviewSignals: ["점심 시간대가 활기 최고", "오후 3시 전후 마감 부스 많음"],
    bestFor: ["시장 투어", "가벼운 점심", "로컬 분위기"],
  },
  "galleria-doria-pamphilj": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Palazzo_Doria_Pamphilj.jpg/330px-Palazzo_Doria_Pamphilj.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Galleria_Doria_Pamphilj",
    shortLabel: "도리아팜필리",
    wikiTitle: "Doria Pamphilj Gallery",
    story:
      "코르소 거리의 귀족 저택 미술관. 벨라스케스의 '교황 인노첸시오 10세 초상'과 거울의 방이 하이라이트로, 바티칸보다 한산하게 명작을 보는 옵션으로 통한다.",
    highlights: ["벨라스케스 교황 초상", "거울의 방", "한산한 명작 관람"],
    reviewSignals: ["오디오가이드 평 좋음", "비 오는 날 대체로 최적"],
    bestFor: ["미술", "비 오는 날", "중심부"],
  },
  "emma-pizzeria": {
    shortLabel: "엠마",
    highlights: ["로마식 얇은 피자", "캄포 데 피오리 근처", "깔끔한 실내"],
    reviewSignals: ["예약 권장", "토핑 시즌 메뉴 주목"],
    bestFor: ["로마식 피자", "단체 식사"],
  },
  supplizio: {
    shortLabel: "수플리치오",
    highlights: ["수플리 전문점", "장인 버전 길거리 간식", "포장 간편"],
    reviewSignals: ["좌석 적음", "클래식+계절 한정 같이"],
    bestFor: ["간식", "걷는 날"],
  },
  monti: {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Rome_via_dei_fori_imperiali_20050922.jpg/330px-Rome_via_dei_fori_imperiali_20050922.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Monti_(rione_of_Rome)",
    shortLabel: "몬티",
    wikiTitle: "Monti (rione of Rome)",
    story:
      "콜로세움 뒤편의 빈티지·공방 동네. 보헤미안 부티크와 와인바가 골목마다 있고, 마돈나 데이 몬티 광장 분수 주변이 저녁마다 동네 사랑방이 된다. 콜로세움과 묶는 산책 코스로 가장 좋다.",
    highlights: ["빈티지 샵 골목", "광장 분수 사랑방", "콜로세움 뒤 산책"],
    reviewSignals: ["상점 시에스타 휴무 주의", "저녁 와인바 활기"],
    bestFor: ["쇼핑", "골목 산책", "저녁 한 잔"],
  },
  giolitti: {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/GiolittiCafeRoma.jpg/330px-GiolittiCafeRoma.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Giolitti",
    shortLabel: "졸리티",
    wikiTitle: "Giolitti",
    story:
      "1900년 개업, 이탈리아 왕실에 납품하던 로마 최고참 젤라테리아. 판테온에서 도보 2분이라 중심부 코스에 자연스럽게 끼고, 한국 여행자들의 '로마 3대 젤라또' 단골 1번이다.",
    highlights: ["1900년 왕실 납품 이력", "판테온 도보 2분", "한국인 3대 젤라또"],
    reviewSignals: ["계산 먼저 → 픽업 순서", "피크엔 카오스급 혼잡", "콘+생크림 무료 토핑"],
    bestFor: ["중심부 코스", "디저트", "더운 오후"],
  },
  "janiculum-terrace": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Janiculum.jpg/330px-Janiculum.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Janiculum",
    shortLabel: "자니콜로",
    wikiTitle: "Janiculum",
    highlights: ["로마 파노라마 전망", "정오 대포 전통", "트라스테베레 위 언덕"],
    reviewSignals: ["해질녘이 베스트", "오르막 — 체력 배분", "밤엔 큰길로"],
    bestFor: ["전망", "해질녘", "산책"],
  },
  "gelateria-del-teatro": {
    shortLabel: "델테아트로",
    story: "나보나 뒤 골목의 장인 젤라테리아. 로즈마리 꿀, 세이지 라즈베리 같은 허브 조합이 시그니처로, '예쁜 골목 + 진짜 수제'로 평이 갈리지 않는 집.",
    highlights: ["허브 조합 시그니처", "그림 같은 골목", "진짜 수제"],
    reviewSignals: ["좌석 거의 없음", "시즌 플레이버 물어보기"],
    bestFor: ["젤라또", "나보나 근처", "사진"],
  },
  "sant-eustachio": {
    shortLabel: "산테우스타키오",
    wikiTitle: "Sant'Eustachio Il Caffè",
    story:
      "1938년부터 장작 로스팅을 지키는 로마 대표 카페. 크레마를 살린 '그란 카페'가 시그니처인데 기본이 설탕 포함이라, 무설탕은 주문 때 미리 말해야 한다.",
    highlights: ["로마 카페 원탑급", "그란 카페 시그니처", "장작 로스팅"],
    reviewSignals: ["설탕 디폴트 — senza zucchero", "바 스탠딩이 싸고 빠름"],
    bestFor: ["에스프레소", "중심부 휴식"],
  },
  "santa-maria-trastevere": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/01_Santa_Maria_in_Trastevere_Facade.jpg/330px-01_Santa_Maria_in_Trastevere_Facade.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Santa_Maria_in_Trastevere",
    shortLabel: "산타마리아",
    wikiTitle: "Santa Maria in Trastevere",
    highlights: ["로마 최고(最古)급 성모 성당", "황금 모자이크", "광장 분수 야경"],
    reviewSignals: ["미사 시간 관람 제한", "저녁 광장 분위기 좋음"],
    bestFor: ["트라스테베레", "모자이크", "야경"],
  },
  "basilica-san-clemente": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Basilica_di_San_Clemente_al_Laterano_-_esterno.jpg/330px-Basilica_di_San_Clemente_al_Laterano_-_esterno.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/San_Clemente%2C_Rome",
    shortLabel: "산클레멘테",
    wikiTitle: "Basilica di San Clemente",
    highlights: ["3개 층 시대 단면", "지하 미트라 신전", "콜로세움 도보 10분"],
    reviewSignals: ["지하는 유료·사진 금지", "서늘해서 한낮 피서 겸"],
    bestFor: ["역사", "콜로세움 연계", "더운 오후"],
  },
  "jewish-ghetto": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/ViaRuaInGhettoByRoeslerFranz.jpg/330px-ViaRuaInGhettoByRoeslerFranz.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Roman_Ghetto",
    shortLabel: "유대인지구",
    wikiTitle: "Roman Ghetto",
    story:
      "테베레 강가의 옛 유대인 게토. 튀긴 아티초크(카르초피 알라 주디아)의 본고장으로, 마르첼로 극장 유적과 좁은 골목, 코셔 베이커리가 이어진다. 캄포 데 피오리·테베레섬과 한 동선.",
    highlights: ["튀긴 아티초크 본고장", "마르첼로 극장 유적", "골목 산책"],
    reviewSignals: ["아티초크 시즌(겨울~봄) 외엔 냉동인 집도", "토요일 안식일 휴무 가게 많음"],
    bestFor: ["음식+역사", "산책", "캄포 연계"],
  },
  "palazzo-barberini": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Palazzo_Barberini_-_esterno.jpg/330px-Palazzo_Barberini_-_esterno.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Palazzo_Barberini",
    shortLabel: "바르베리니",
    wikiTitle: "Palazzo Barberini",
    highlights: ["카라바조 컬렉션", "보로미니 나선 계단", "한산한 국립미술관"],
    reviewSignals: ["트레비에서 도보 10분", "비 오는 날 대체 1순위급"],
    bestFor: ["미술", "비 오는 날"],
  },
  "marigold-roma": {
    shortLabel: "마리골드",
    highlights: ["북유럽풍 브런치", "베이커리 겸업", "테스타치오 권역"],
    reviewSignals: ["주말 브런치 대기", "월·화 휴무 패턴 확인"],
    bestFor: ["브런치", "커피"],
  },
  "caffe-propaganda": {
    shortLabel: "프로파간다",
    highlights: ["콜로세움 도보 5분", "비스트로풍 카페", "티라미수 평 좋음"],
    reviewSignals: ["식사보다 카페 활용이 안전", "관광지 물가"],
    bestFor: ["콜로세움 휴식", "디저트"],
  },
  regoli: {
    shortLabel: "레골리",
    story: "1916년 개업 파스티체리아. 생크림을 가득 채운 마리토초(maritozzo)의 로마 대표로 꼽히고, 아침 일찍 가야 줄이 짧다.",
    highlights: ["마리토초 대표", "1916년 파스티체리아", "현지 아침 문화"],
    reviewSignals: ["일찍 품절되는 품목", "월요일 휴무 패턴"],
    bestFor: ["아침 디저트", "빵지순례"],
  },
  "via-condotti": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Dolce_%26_Gabbana%2C_Via_dei_Condotti_%2846129645824%29.jpg/330px-Dolce_%26_Gabbana%2C_Via_dei_Condotti_%2846129645824%29.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Via_Condotti",
    shortLabel: "콘도티",
    wikiTitle: "Via dei Condotti",
    highlights: ["로마 명품 1번가", "스페인 계단 정면 축", "윈도 쇼핑"],
    reviewSignals: ["인파+소매치기 주의", "세금 환급은 매장에서 바로"],
    bestFor: ["쇼핑", "스페인 계단 연계"],
  },
  frigidarium: {
    shortLabel: "프리지다리움",
    story: "나보나 광장 옆 골목의 인기 젤라테리아. 초콜릿 디핑 마무리가 시그니처로, 한국 여행자들 사이에서 '나보나 오면 무조건'으로 통한다.",
    highlights: ["초코 디핑 마무리", "나보나 도보 1분", "한국인 단골"],
    reviewSignals: ["저녁 줄 김", "좌석 없음 — 광장에서"],
    bestFor: ["나보나 코스", "디저트"],
  },
  "trapizzino-trastevere": {
    shortLabel: "트라피치노",
    highlights: ["피자 도우 주머니+로마 스튜", "한 손 스트리트푸드", "야식 가능"],
    reviewSignals: ["치킨 카차토라·소꼬리 인기", "서서 먹는 구조"],
    bestFor: ["간단 끼니", "야식", "걷는 날"],
  },
  "tazza-doro": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/La_Casa_del_Caffe_Tazza_D%60oro_%E9%87%91%E6%9D%AF%E5%92%96%E5%95%A1%E9%A4%A8_-_panoramio.jpg/330px-La_Casa_del_Caffe_Tazza_D%60oro_%E9%87%91%E6%9D%AF%E5%92%96%E5%95%A1%E9%A4%A8_-_panoramio.jpg",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:La_Casa_del_Caffe_Tazza_D%60oro_%E9%87%91%E6%9D%AF%E5%92%96%E5%95%A1%E9%A4%A8_-_panoramio.jpg",
    imageCredit: "lienyuan lee / CC BY 3.0",
    shortLabel: "타차도로",
    wikiTitle: "La Casa del Caffè Tazza d'Oro",
    highlights: ["판테온 앞 로스터리", "그라니타 디 카페", "원두 쇼핑"],
    reviewSignals: ["여름 그라니타가 핵심", "바 스탠딩 저렴"],
    bestFor: ["커피", "판테온 연계", "더운 날"],
  },
  "via-del-corso": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Via_del_Corso_%2852501354470%29.jpg/330px-Via_del_Corso_%2852501354470%29.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Via_del_Corso",
    shortLabel: "코르소",
    wikiTitle: "Via del Corso",
    highlights: ["포폴로~베네치아 쇼핑 축", "중저가 브랜드 집결", "야간 산책"],
    reviewSignals: ["주말 인파 극심", "소매치기 주의 구간"],
    bestFor: ["쇼핑", "이동 겸 산책"],
  },
  "tiber-island": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Isola_Tiberina%2C_Rome_%2824824736817%29.jpg/330px-Isola_Tiberina%2C_Rome_%2824824736817%29.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Tiber_Island",
    shortLabel: "테베레섬",
    wikiTitle: "Tiber Island",
    highlights: ["세계서 가장 작은 유인섬급", "강변 산책", "유대인지구·트라스테베레 다리"],
    reviewSignals: ["여름밤 강변 행사 시즌", "체류 짧음 — 경유형"],
    bestFor: ["산책", "사진", "동선 연결"],
  },
  "mercato-trionfale": {
    shortLabel: "트리온팔레",
    highlights: ["로마 최대급 로컬 시장", "바티칸 도보권", "관광객 적음"],
    reviewSignals: ["오전이 활기", "식료품 위주 — 식사 부스는 적음"],
    bestFor: ["로컬 체험", "바티칸 연계"],
  },
  "fatamorgana-monti": {
    shortLabel: "파타모르가나",
    highlights: ["천연재료 젤라또 체인", "글루텐프리 전 품목", "몬티 지점 접근성"],
    reviewSignals: ["창작 플레이버 호불호", "클래식도 탄탄"],
    bestFor: ["젤라또", "몬티 산책"],
  },
  "rinascente-rome-rooftop": {
    shortLabel: "리나센테",
    highlights: ["백화점 루프탑 무료 뷰", "지하 고대 수도교 유적", "트레비 도보 3분"],
    reviewSignals: ["루프탑 바 가격대 있음", "뷰만 보고 내려와도 OK"],
    bestFor: ["전망", "쇼핑", "트레비 연계"],
  },
  "largo-argentina": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Curia_of_Pompey.jpg/330px-Curia_of_Pompey.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Largo_di_Torre_Argentina",
    shortLabel: "아르젠티나",
    wikiTitle: "Largo di Torre Argentina",
    highlights: ["카이사르 암살 추정지", "고양이 보호소", "위에서 내려다보는 유적"],
    reviewSignals: ["통행로에서 무료 관람 가능", "고양이는 만지지 않기"],
    bestFor: ["역사", "산책 경유", "고양이"],
  },
  "antico-caffe-greco": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Ludwig_Passini_-_K%C3%BCnstler_im_Cafe_Greco_in_Rom.jpg/330px-Ludwig_Passini_-_K%C3%BCnstler_im_Cafe_Greco_in_Rom.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Antico_Caff%C3%A8_Greco",
    shortLabel: "카페그레코",
    wikiTitle: "Antico Caffè Greco",
    story:
      "1760년 개업한 로마에서 가장 오래된 카페. 괴테, 안데르센, 키츠가 드나들던 살롱으로 벨벳 의자와 그림이 그대로다. 테이블 가격이 비싸니 바 스탠딩으로 분위기만 즐기는 것도 방법.",
    highlights: ["1760년 로마 최고(最古) 카페", "문인들의 살롱", "박물관급 인테리어"],
    reviewSignals: ["테이블 착석은 가격 2-3배", "스페인 계단 쇼핑 동선과 묶기"],
    bestFor: ["클래식 카페", "스페인 계단 연계"],
  },
  "pastificio-guerra": {
    shortLabel: "파스티피초",
    highlights: ["4유로대 생면 파스타", "스페인 계단 옆 가성비", "매일 2종 로테이션"],
    reviewSignals: ["좌석 거의 없음 — 서서/포장", "점심 한정 운영"],
    bestFor: ["가성비 점심", "쇼핑 중 끼니"],
  },
  "fassi-gelato": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Palazzo_del_Freddo_05_01_2020.jpg/330px-Palazzo_del_Freddo_05_01_2020.jpg",
    imageSourceUrl: "https://it.wikipedia.org/wiki/Palazzo_del_Freddo_Giovanni_Fassi",
    shortLabel: "파씨",
    wikiTitle: "Palazzo del Freddo",
    highlights: ["1880년 젤라또 궁전", "리조(쌀) 시그니처", "넓은 실내 좌석"],
    reviewSignals: ["계산 먼저 시스템", "테르미니 이동일과 묶기"],
    bestFor: ["젤라또", "기차 이동일", "더운 날"],
  },
  "old-bridge-gelateria": {
    shortLabel: "올드브릿지",
    highlights: ["바티칸 성벽 앞", "양 많고 저렴", "테이크아웃 전용"],
    reviewSignals: ["바티칸 줄과 동선 겹침", "현금 결제가 빠름"],
    bestFor: ["바티칸 코스", "젤라또"],
  },
  "cul-de-sac": {
    shortLabel: "쿨데삭",
    highlights: ["나보나 옆 와인 바", "소꼬리찜 한국인 인기", "와인 리스트 방대"],
    reviewSignals: ["좁아서 피크 대기", "오픈런 또는 예약"],
    bestFor: ["저녁 와인", "한국인 입맛", "나보나 연계"],
  },
  "la-taverna-dei-fori-imperiali": {
    shortLabel: "라타베르나",
    highlights: ["포로 로마노 입구 골목", "4대 가족 운영", "콜로세움 저녁 1순위"],
    reviewSignals: ["예약 필수", "수요일 휴무 패턴", "클래식 메뉴가 안전"],
    bestFor: ["콜로세움 연계", "전통 트라토리아", "저녁"],
  },

  /* ===== 피렌체 — 맛집·카페·명소 보강 (2026-06 리서치) ===== */
  "trattoria-dall-oste": {
    shortLabel: "달오스테",
    story:
      "한국인 여행자들의 피렌체 티본 스테이크 1순위. 한국어 메뉴판과 한국인 직원 응대 덕에 주문 장벽이 없고, 산타 마리아 노벨라역 앞 지점은 접근성까지 좋다. 키아니나·마레마나 소고기를 무게 단위로 고른다.",
    highlights: ["한국인 티본 1순위", "한국어 메뉴판", "역 앞 접근성"],
    reviewSignals: ["저녁 예약 필수", "1kg 2인 기준이 표준", "굽기는 미디엄레어 고정 전통"],
    bestFor: ["티본 스테이크", "첫 피렌체", "기념 식사"],
  },
  "trattoria-cammillo": {
    shortLabel: "캄밀로",
    highlights: ["1945년 강변 전통집", "버터빈스·송아지 요리", "올트라르노 클래식"],
    reviewSignals: ["예약 권장", "클래식 분위기 — 시끌벅적 아님"],
    bestFor: ["전통 토스카나", "어른 분위기"],
  },
  "la-giostra": {
    shortLabel: "라 조스트라",
    story:
      "합스부르크 가문 후손이 연 레스토랑으로, 전구 조명 가득한 입구와 웰컴 스푸만테가 시그니처. 배 카르파초와 페어 파스타가 유명해 '분위기+맛' 기념일 식당으로 한국 블로그에 자주 오른다.",
    highlights: ["전구 조명 분위기 맛집", "웰컴 스파클링", "배 파스타 시그니처"],
    reviewSignals: ["예약 필수", "가격대 높은 편", "어두운 조명 — 사진은 플래시 없이"],
    bestFor: ["기념일", "분위기", "데이트"],
  },
  "osteria-santo-spirito": {
    shortLabel: "산토스피리토",
    highlights: ["트러플 치즈 뇨키", "광장 테라스석", "올트라르노 활기"],
    reviewSignals: ["뇨키는 양 많고 진함 — 나눠먹기", "광장석은 선착순"],
    bestFor: ["뇨키", "광장 저녁", "올트라르노"],
  },
  "il-santo-bevitore": {
    shortLabel: "산토베비토레",
    highlights: ["모던 토스카나", "와인 셀렉션 강점", "차분한 다이닝"],
    reviewSignals: ["예약 권장", "옆집 와인바(Santino)도 운영"],
    bestFor: ["와인 디너", "모던 미식"],
  },
  "sergio-gozzi": {
    shortLabel: "세르조고치",
    highlights: ["중앙시장 옆 점심 전용", "1915년부터 시장 노동자 식당", "손글씨 일일 메뉴"],
    reviewSignals: ["점심만 영업(–15시)", "현금 위주", "회전 빠름"],
    bestFor: ["점심", "전통 가정식", "시장 연계"],
  },
  "trattoria-ruggero": {
    shortLabel: "루제로",
    highlights: ["포르타 로마나 밖 로컬", "리볼리타 명가", "관광객 드묾"],
    reviewSignals: ["중심부에서 도보 25분", "일·월 휴무 패턴 확인"],
    bestFor: ["로컬 분위기", "토스카나 수프"],
  },
  "buca-lapi": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Piazza_degli_antinori_3%2C_palazzo_antinori%2C_su_via_del_trebbio%2C_portale_della_buca_lapi.jpg/330px-Piazza_degli_antinori_3%2C_palazzo_antinori%2C_su_via_del_trebbio%2C_portale_della_buca_lapi.jpg",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Piazza_degli_antinori_3,_palazzo_antinori,_su_via_del_trebbio,_portale_della_buca_lapi.jpg",
    imageCredit: "Francesco Bini / CC BY-SA 4.0",
    shortLabel: "부카라피",
    wikiTitle: "Buca Lapi",
    story: "1880년 와인 셀러에서 시작한 피렌체 최고참 레스토랑. 천장의 빈티지 여행 포스터 아래에서 티본을 써는 클래식 분위기로, 달오스테보다 '격식파' 선택지다.",
    highlights: ["1880년 셀러 레스토랑", "티본 명가", "클래식 격식 분위기"],
    reviewSignals: ["예약 필수", "가격대 높음", "드레스 살짝 갖추기"],
    bestFor: ["티본 스테이크", "격식 저녁", "기념일"],
  },
  "trattoria-la-casalinga": {
    shortLabel: "카살링가",
    highlights: ["산토 스피리토 가정식", "푸짐+저렴", "가족 운영 반세기"],
    reviewSignals: ["줄서기 흔함(예약 가능)", "메뉴판 손글씨 — 직원에게 물어보기"],
    bestFor: ["가성비", "가정식", "올트라르노"],
  },
  zeb: {
    shortLabel: "제브",
    highlights: ["산 니콜로 카운터 다이닝", "수제 파스타 소수 정예", "미켈란젤로 언덕 아래"],
    reviewSignals: ["좌석 매우 적음 — 예약", "미켈란젤로 광장과 묶기"],
    bestFor: ["미켈란젤로 연계", "조용한 미식"],
  },
  "osteria-cinghiale-bianco": {
    shortLabel: "친기알레",
    highlights: ["멧돼지 파파르델레", "보르고 산 야코포 골목", "토스카나 사냥 요리"],
    reviewSignals: ["예약 권장", "멧돼지는 진한 맛 — 호불호 적은 편"],
    bestFor: ["토스카나 전통", "폰테베키오 연계"],
  },
  "officina-profumo": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Logo_Off._Prof._S._M._Novella.png/330px-Logo_Off._Prof._S._M._Novella.png",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Officina_Profumo-Farmaceutica_di_Santa_Maria_Novella",
    shortLabel: "SMN약국",
    wikiTitle: "Officina Profumo-Farmaceutica di Santa Maria Novella",
    story:
      "1612년 도미니코 수도사들의 약방에서 시작한 세계 최고(最古)급 향수·코스메틱 하우스. 프레스코 천장 아래에서 장미수·포푸리를 고르는 경험 자체가 관광이고, 한국 면세가보다 싼 품목이 많아 선물 쇼핑 1순위로 꼽힌다.",
    highlights: ["1612년 수도원 약국", "프레스코 매장", "선물 쇼핑 1순위"],
    reviewSignals: ["장미수·포푸리가 시그니처", "면세 환급 기준 금액 확인", "박물관 존도 무료"],
    bestFor: ["쇼핑", "선물", "향수"],
  },
  "mercato-sant-ambrogio": {
    shortLabel: "산탐브로조",
    highlights: ["현지인 아침 시장", "중앙시장보다 로컬", "청과·치즈 구경"],
    reviewSignals: ["오전 영업 위주(–14시)", "노점 흥정보다 정찰"],
    bestFor: ["로컬 체험", "아침 산책"],
  },
  nerbone: {
    shortLabel: "네르보네",
    story:
      "1872년부터 중앙시장 1층을 지킨 스탠드. 푹 삶은 소고기 수육 버거(파니노 콘 볼리토)와 곱창 버거(람프레도토)가 5유로대라, 한국 여행자들의 '피렌체 필수 미션'이 됐다. 국물 적신 빵(바냐토)으로 주문하는 게 정석.",
    highlights: ["1872년 시장 스탠드", "람프레도토 성지", "5유로대 한 끼"],
    reviewSignals: ["점심 피크 줄 김", "바냐토(국물 적심) 주문이 정석", "오후 2시 전후 품절"],
    bestFor: ["시장 점심", "스트리트푸드", "가성비"],
  },
  "gelateria-dei-neri": {
    shortLabel: "데이네리",
    highlights: ["산타 크로체 근처 인기 젤라테리아", "리코타+무화과 시그니처", "저렴한 가격대"],
    reviewSignals: ["저녁 줄 김", "컵이 양 조절 쉬움"],
    bestFor: ["젤라또", "산타 크로체 연계"],
  },
  "ditta-artigianale": {
    shortLabel: "디타",
    highlights: ["피렌체 스페셜티 커피 선두", "브런치 운영", "노트북 작업 가능 분위기"],
    reviewSignals: ["에스프레소 외 필터커피 강점", "피크 브런치 대기"],
    bestFor: ["커피", "브런치", "휴식"],
  },
  "rose-garden": {
    shortLabel: "장미정원",
    highlights: ["미켈란젤로 광장 아래 무료 정원", "5-6월 만개", "두오모 배경 사진"],
    reviewSignals: ["6월 방문이면 시즌 적중", "일몰 전 광장과 묶기"],
    bestFor: ["사진", "휴식", "미켈란젤로 연계"],
  },
  "i-due-fratellini": {
    shortLabel: "두프라텔리니",
    highlights: ["1875년 서서 먹는 파니니 창구", "와인 한 잔 같이", "시뇨리아 근처"],
    reviewSignals: ["좌석 없음 — 길에서", "잔은 벽 선반에 반납"],
    bestFor: ["간단 점심", "전통 체험"],
  },
  "la-fettunta": {
    shortLabel: "페투운타",
    highlights: ["갓 구운 빵+올리브오일", "두오모 근처 간식", "포장 간편"],
    reviewSignals: ["회전 빠름", "오일 추가는 무료인지 확인"],
    bestFor: ["간식", "두오모 연계"],
  },
  "caffe-gilli": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Caff%C3%A9_gilli_out.JPG/330px-Caff%C3%A9_gilli_out.JPG",
    imageSourceUrl: "https://it.wikipedia.org/wiki/Caff%C3%A8_Gilli",
    shortLabel: "질리",
    wikiTitle: "Caffè Gilli",
    story: "1733년 개업한 피렌체 최고(最古) 카페. 레푸블리카 광장의 아르누보 인테리어에서 마시는 핫초코와 페이스트리가 시그니처다. 착석은 비싸니 바 이용이 요령.",
    highlights: ["1733년 최고참 카페", "아르누보 인테리어", "레푸블리카 광장"],
    reviewSignals: ["착석 가격 2배 이상", "아침 바 이용이 합리적"],
    bestFor: ["클래식 카페", "디저트", "광장"],
  },
  "basilica-san-lorenzo": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Firenze_Basilica_di_San_Lorenzo_Esterno_Lato_Nord_1.jpg/330px-Firenze_Basilica_di_San_Lorenzo_Esterno_Lato_Nord_1.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Basilica_of_San_Lorenzo%2C_Florence",
    shortLabel: "산로렌초",
    wikiTitle: "San Lorenzo, Florence",
    highlights: ["메디치 가문 교회", "브루넬레스키 설계", "미완성 파사드"],
    reviewSignals: ["메디치 예배당과 별도 입장권", "시장 소음 — 내부는 고요"],
    bestFor: ["역사", "메디치", "중앙시장 연계"],
  },
  "via-tornabuoni": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Via_de_Tornabuoni.JPG/330px-Via_de_Tornabuoni.JPG",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Via_de'_Tornabuoni",
    shortLabel: "토르나부오니",
    wikiTitle: "Via de' Tornabuoni",
    highlights: ["피렌체 명품 1번가", "구찌·페라가모 본진", "르네상스 팔라초 쇼핑"],
    reviewSignals: ["페라가모 박물관도 같은 거리", "아이쇼핑만으로도 가치"],
    bestFor: ["쇼핑", "건축 구경"],
  },
  semel: {
    shortLabel: "세멜",
    highlights: ["산탐브로조 앞 미니 파니니 바", "창작 조합 파니니", "주인장 큐레이션"],
    reviewSignals: ["좌석 없음", "점심 한정 — 이른 방문"],
    bestFor: ["간단 점심", "시장 연계"],
  },
  "gusta-pizza": {
    shortLabel: "구스타피자",
    highlights: ["나폴리식 화덕 피자", "하트 모양 도우 이벤트", "산토 스피리토 근처"],
    reviewSignals: ["피크 줄 김·합석", "포장해서 광장 피크닉도 좋음"],
    bestFor: ["피자", "캐주얼 저녁"],
  },
  "palazzo-medici-riccardi": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Palazzo_Medici_Riccardi-Florence.jpg/330px-Palazzo_Medici_Riccardi-Florence.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Palazzo_Medici_Riccardi",
    shortLabel: "메디치궁",
    wikiTitle: "Palazzo Medici Riccardi",
    highlights: ["메디치 본가 궁전", "고촐리 동방박사 예배당", "르네상스 건축 원형"],
    reviewSignals: ["예배당 인원 제한 — 대기 가능", "두오모 도보 5분"],
    bestFor: ["르네상스", "미술", "비 오는 날"],
  },
  procacci: {
    shortLabel: "프로카치",
    story: "1885년부터 토르나부오니 거리를 지킨 트러플 전문 바. 한 입 크기 트러플 파니니에 프로세코 한 잔이 공식 조합으로, 쇼핑 중 우아한 휴식으로 통한다.",
    highlights: ["트러플 미니 파니니", "1885년 전통", "명품 거리 한복판"],
    reviewSignals: ["파니니는 2-3개가 적당", "좌석 적음"],
    bestFor: ["쇼핑 휴식", "트러플", "와인 한 잔"],
  },
  vivoli: {
    shortLabel: "비볼리",
    story: "1932년 개업한 피렌체 최고(最古) 젤라테리아. 산타 크로체 뒷골목에서 4대째 이어지고, 컵 전용(콘 없음) 원칙과 리조·크레마 같은 클래식 맛으로 유명하다.",
    highlights: ["1932년 4대째", "컵 전용 원칙", "산타 크로체 뒷골목"],
    reviewSignals: ["콘 없음 — 컵만", "아포가토식 카페 조합 추천"],
    bestFor: ["젤라또", "산타 크로체 연계"],
  },
  "palazzo-strozzi": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Florence%2C_Palazzo_Strozzi%2C_North_and_West_facade%2C_Benedetto_da_Maiano%2C_1489-1538.jpg/330px-Florence%2C_Palazzo_Strozzi%2C_North_and_West_facade%2C_Benedetto_da_Maiano%2C_1489-1538.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Palazzo_Strozzi",
    shortLabel: "스트로치",
    wikiTitle: "Palazzo Strozzi",
    highlights: ["대형 기획전 전문", "르네상스 팔라초", "안뜰 무료 개방"],
    reviewSignals: ["전시에 따라 만족도 좌우 — 현재 전시 확인", "안뜰 카페 휴식 좋음"],
    bestFor: ["현대미술", "비 오는 날"],
  },
  "brancacci-chapel": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Izokefalizm.jpg/330px-Izokefalizm.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Brancacci_Chapel",
    shortLabel: "브란카치",
    wikiTitle: "Brancacci Chapel",
    highlights: ["마사초 프레스코 — 원근법 혁명", "르네상스 회화 출발점", "올트라르노 조용한 보석"],
    reviewSignals: ["예약제·시간 제한 관람", "미술 좋아하면 만족도 최상위"],
    bestFor: ["미술", "르네상스", "한적함"],
  },
  sbrino: {
    shortLabel: "스브리노",
    highlights: ["농장 직영 수제 젤라또", "산 프레디아노 동네 가게", "유기농 우유"],
    reviewSignals: ["중심부에서 살짝 멀음", "피스타치오 평 최상"],
    bestFor: ["젤라또", "올트라르노 산책"],
  },
  "rinascente-florence-rooftop": {
    shortLabel: "리나센테",
    highlights: ["레푸블리카 광장 백화점 루프탑", "두오모 클로즈업 뷰", "카페 한 잔 가격으로 전망"],
    reviewSignals: ["좁아서 자리 경쟁", "해질녘 베스트"],
    bestFor: ["전망", "쇼핑 연계"],
  },
  rivoire: {
    shortLabel: "리부아르",
    highlights: ["시뇨리아 광장 1872년 카페", "진한 핫초코 명물", "베키오궁 정면 테라스"],
    reviewSignals: ["테라스 착석 비쌈", "초콜릿 선물 포장 가능"],
    bestFor: ["광장 휴식", "핫초코", "클래식"],
  },
  "scuola-del-cuoio": {
    shortLabel: "가죽학교",
    highlights: ["산타 크로체 뒤 가죽 공방 학교", "장인 작업 견학", "이니셜 각인 서비스"],
    reviewSignals: ["시장 가죽보다 비싸지만 품질 보증", "각인은 구매 시 무료인지 확인"],
    bestFor: ["쇼핑", "공방 견학", "선물"],
  },
  "caffe-scudieri": {
    shortLabel: "스쿠디에리",
    highlights: ["두오모 앞 1939년 파스티체리아", "아침 코르네토", "광장 뷰 좌석"],
    reviewSignals: ["두오모 등반 전 아침으로 좋음", "착석 가격 확인"],
    bestFor: ["아침", "두오모 연계"],
  },
  "museo-galileo": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Museo_Galileo_palazzo.jpg/330px-Museo_Galileo_palazzo.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Museo_Galileo",
    shortLabel: "갈릴레오",
    wikiTitle: "Museo Galileo",
    highlights: ["갈릴레이 망원경 실물", "과학사 박물관", "우피치 옆 한산함"],
    reviewSignals: ["아이·과학 취향이면 만족", "우피치 대기 대체 코스"],
    bestFor: ["과학", "비 오는 날", "우피치 연계"],
  },
  "gelateria-la-carraia": {
    shortLabel: "라카라이아",
    highlights: ["카라이아 다리 옆 인기점", "1유로 미니콘", "강변 산책 조합"],
    reviewSignals: ["저녁 줄 김", "다리 위에서 먹는 뷰가 보너스"],
    bestFor: ["젤라또", "강변 산책", "가성비"],
  },
  /* ===== 2026-06 대량 수집분 (도시별 places 파일로 통합됨) ===== */
  "seu-pizza-illuminati": {
    shortLabel: "세우피자",
    highlights: ["50 Top Pizza 상위 단골", "창작 토핑 피자", "트라스테베레 남쪽"],
    reviewSignals: ["클래식 로마피자와 전혀 다른 결", "디저트 피자 평 좋음"],
    bestFor: ["피자", "모던 미식"],
  },
  "ai-marmi": {
    shortLabel: "아이마르미",
    highlights: ["바삭한 로마식 도우 기준점", "대리석 테이블 노포", "밤늦게까지"],
    reviewSignals: ["회전 빨라 웨이팅 금방 빠짐", "쫄깃한 나폴리식 기대하면 실망"],
    bestFor: ["저녁", "현지 분위기"],
  },
  "pizzeria-da-remo": {
    shortLabel: "다레모",
    highlights: ["테스타치오 로마피자 1순위", "야외 테이블 왁자지껄", "가성비"],
    reviewSignals: ["현금만", "오픈(19시) 직후가 답"],
    bestFor: ["저녁", "가성비", "로컬"],
  },
  "da-cesare-al-casaletto": {
    shortLabel: "다체사레",
    highlights: ["기자들이 꼽는 로마 최고 트라토리아", "튀김 전채 전설", "트램 8 종점"],
    reviewSignals: ["예약 없인 불가 수준", "왕복 1시간 — 동선 밖"],
    bestFor: ["미식 원정", "여유일"],
  },
  "antica-birreria-peroni": {
    shortLabel: "페로니홀",
    highlights: ["1906년 페로니 직영 비어홀", "소시지+생맥주 가성비", "트레비 도보권"],
    reviewSignals: ["합석·시끌벅적", "일요일 휴무"],
    bestFor: ["저녁", "가성비"],
  },
  "pane-e-salame": {
    shortLabel: "파네살라메",
    highlights: ["트레비 3분 파니니 줄집", "5유로대 가성비", "살루미 보드"],
    reviewSignals: ["피크(12-14시) 줄 김", "좌석 적음 — 포장 각오"],
    bestFor: ["점심", "중심부 동선"],
  },
  "la-prosciutteria-trevi": {
    shortLabel: "프로슈테리아",
    highlights: ["수북한 살루미 보드", "하우스 와인 가성비", "토스카나 스타일"],
    reviewSignals: ["보드는 한 단계 작게 주문", "사진은 1층이 잘 나옴"],
    bestFor: ["아페리티보", "간단 저녁"],
  },
  "aroma-rooftop": {
    shortLabel: "아로마",
    story:
      "콜로세움이 정면으로 보이는 미슐랭 1스타 루프탑 레스토랑. 가격은 로마 최상급이지만 일몰 시간대 디너의 뷰는 대체재가 없다. 부담스러우면 런치 코스가 진입장벽이 낮다.",
    highlights: ["미슐랭 1스타 + 콜로세움 뷰", "일몰 디너 명당", "기념일 코스"],
    reviewSignals: ["1인 10만원대 이상", "수주 전 예약 필수", "드레스코드 있음"],
    bestFor: ["기념일", "뷰 디너"],
  },
  "terrazza-borromini": {
    shortLabel: "보로미니",
    highlights: ["나보나 돔 정면 루프탑", "일몰 아페리티보 명소", "칵테일 값으로 로마 지붕"],
    reviewSignals: ["미니멈 차지·시간제 좌석 확인", "식사보다 음료+뷰 목적이 만족"],
    bestFor: ["아페리티보", "일몰", "사진"],
  },
  "ginger-spagna": {
    shortLabel: "진저",
    highlights: ["스파냐 한복판 건강식 브런치", "착즙주스·샐러드", "파스타 피로 리셋"],
    reviewSignals: ["피크 점심 대기", "가격은 중심부 수준"],
    bestFor: ["브런치", "입맛 환기"],
  },
  coromandel: {
    shortLabel: "코로만델",
    highlights: ["'로마에서 가장 예쁜 아침'", "앤티크 살롱 인테리어", "나보나 뒤 골목"],
    reviewSignals: ["주말 브런치 예약 권장", "좌석 간격 좁음"],
    bestFor: ["브런치", "사진", "분위기"],
  },
  "barnum-cafe": {
    shortLabel: "바넘",
    highlights: ["캄포 근처 빈티지 소파 카페", "스페셜티 커피", "저녁엔 칵테일 바"],
    reviewSignals: ["관광 동선 한복판의 휴식처", "피크엔 자리 경쟁"],
    bestFor: ["휴식", "커피"],
  },
  "gelato-san-crispino": {
    shortLabel: "산크리스피노",
    highlights: ["금속 뚜껑 보관 정통파", "꿀·자몽 시그니처", "트레비 2분"],
    reviewSignals: ["콘 없음 — 컵만", "화려한 비주얼은 없음"],
    bestFor: ["젤라또", "트레비 연계"],
  },
  castroni: {
    shortLabel: "카스트로니",
    highlights: ["1932년 식료품 백화점", "원두·초콜릿 선물 한방", "바 에스프레소 수준급"],
    reviewSignals: ["슈퍼보다 약간 비쌈", "포장 퀄리티로 보상"],
    bestFor: ["선물", "쇼핑", "바티칸 연계"],
  },
  "quartiere-coppede": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Quartiere_Copped%C3%A9_09.jpg/330px-Quartiere_Copped%C3%A9_09.jpg",
    imageSourceUrl: "https://it.wikipedia.org/wiki/Quartiere_Copped%C3%A8",
    shortLabel: "코페데",
    wikiTitle: "Quartiere Coppedè",
    story:
      "건축가 지노 코페데가 1910-20년대에 지은 아르누보 단지. 동화책에서 튀어나온 듯한 외관과 개구리 분수가 중심이고, 관광객이 거의 없어 한적한 사진 산책에 최고다.",
    highlights: ["동화풍 아르누보 건축", "개구리 분수 포인트", "관광객 거의 없음"],
    reviewSignals: ["대중교통 필요", "보르게세와 같은 북쪽 동선"],
    bestFor: ["사진", "히든플레이스"],
  },
  "san-luigi-dei-francesi": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/%C3%89glise_San_Luigi_Francesi_-_Rome_%28IT62%29_-_2021-08-28_-_2.jpg/330px-%C3%89glise_San_Luigi_Francesi_-_Rome_%28IT62%29_-_2021-08-28_-_2.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/San_Luigi_dei_Francesi",
    shortLabel: "산루이지",
    wikiTitle: "San Luigi dei Francesi",
    story:
      "카라바조의 '성 마태오 3부작'을 무료로 보는 프랑스인 공동체 성당. 나보나 광장에서 도보 2분이라 경유 비용이 사실상 0인데 보상은 미술관급이다. 1유로 동전을 넣으면 그림에 조명이 켜진다.",
    highlights: ["카라바조 3부작 무료", "나보나 2분 경유", "조명 동전 1유로"],
    reviewSignals: ["점심시간 폐문 주의", "미사 중 관람 불가"],
    bestFor: ["미술", "무료", "중심부 동선"],
  },
  "santa-maria-della-vittoria": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Santa_Maria_della_Vittoria_in_Rome_-_Front.jpg/330px-Santa_Maria_della_Vittoria_in_Rome_-_Front.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Santa_Maria_della_Vittoria%2C_Rome",
    shortLabel: "비토리아",
    wikiTitle: "Santa Maria della Vittoria, Rome",
    story:
      "베르니니의 '성녀 테레사의 환희'가 있는 작은 바로크 성당. 보르게세 미술관을 못 가는 일정이라면 여기서 베르니니 조각의 정수를 무료로 채울 수 있다.",
    highlights: ["베르니니 대표작 무료", "작지만 밀도 높은 바로크", "바르베리니 도보권"],
    reviewSignals: ["개방시간 짧음 — 확인", "규모는 아담"],
    bestFor: ["미술", "무료"],
  },
  "appia-antica": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Paesaggio_dell%27Appia_antica.jpg/330px-Paesaggio_dell%27Appia_antica.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Appian_Way",
    shortLabel: "아피아",
    wikiTitle: "Appian Way",
    story:
      "기원전 312년에 놓인 로마 가도를 자전거로 달리는 반나절 코스. 일요일엔 차량이 통제돼 2300년 된 돌길과 송백나무, 수도교 풍경을 통째로 전세 낸 기분이 든다.",
    highlights: ["2300년 로마 가도", "일요일 차 없는 거리", "자전거 반나절"],
    reviewSignals: ["그늘 적음 — 한여름 오전만", "돌길 — 운동화 필수"],
    bestFor: ["근교", "자전거", "유적"],
  },
  "trattoria-sabatino": {
    shortLabel: "사바티노",
    highlights: ["1956년 멈춘 가격표", "파스타 5-6유로", "옆자리가 다 동네 어르신"],
    reviewSignals: ["현금만", "맛집보다 '경험'으로"],
    bestFor: ["가성비", "로컬 경험"],
  },
  "il-latini": {
    shortLabel: "일라티니",
    story:
      "1911년부터 이어진 토스카나 만찬의 전형. 천장에 프로슈토 다리가 주렁주렁 걸린 홀에서 코스로 맡기면 끝없이 나온다. 합석과 소란 자체가 매력 포인트.",
    highlights: ["프로슈토 천장 명물", "코스로 맡기는 만찬", "1911년 노포"],
    reviewSignals: ["예약 필수", "양 조절 실패 주의", "합석 문화"],
    bestFor: ["전통 만찬", "티본"],
  },
  "regina-bistecca": {
    shortLabel: "레지나",
    story:
      "옛 고서점을 개조한 '스테이크의 여왕'. 달오스테보다 차분하고 격식 있는 분위기에서 숙성 등급별 티본을 고를 수 있다. 두오모 도보 2분.",
    highlights: ["고서점 개조 인테리어", "숙성 등급별 티본", "두오모 2분"],
    reviewSignals: ["저녁 예약 필수", "1kg 단위 과금"],
    bestFor: ["티본", "기념 저녁"],
  },
  "all-antico-ristoro-di-cambi": {
    shortLabel: "디캄비",
    highlights: ["현지인 티본 명가", "중심부보다 한 단계 싼 값", "벽돌 아치 노포"],
    reviewSignals: ["달오스테 대안 1순위", "수요일 휴무 확인"],
    bestFor: ["티본", "로컬"],
  },
  "osteria-dell-enoteca": {
    shortLabel: "델레노테카",
    highlights: ["와인 셀러 낀 모던 다이닝", "드라이에이징 스테이크", "조용한 분위기"],
    reviewSignals: ["전통 트라토리아 소란이 부담스러운 날", "보볼리와 같은 동선"],
    bestFor: ["스테이크", "와인", "조용한 저녁"],
  },
  "simbiosi-pizza": {
    shortLabel: "심비오시",
    highlights: ["유기농 나폴리식 피자", "아카데미아 권역", "수제 맥주"],
    reviewSignals: ["피크 약간 대기", "옆 파스타 지점도 후보"],
    bestFor: ["피자", "캐주얼"],
  },
  "berbere-firenze": {
    shortLabel: "베르베레",
    highlights: ["사워도우 피자 대표주자", "조각 나눠먹는 방식", "산 프레디아노 힙"],
    reviewSignals: ["예약 권장", "반반 토핑 가능"],
    bestFor: ["피자", "힙한 저녁"],
  },
  "cibreo-caffe": {
    shortLabel: "치브레오",
    highlights: ["치브레오 제국의 카페", "원목 클래식 인테리어", "산탐브로조 시장 옆"],
    reviewSignals: ["아침 페이스트리 추천", "식사는 본점 트라토리아로"],
    bestFor: ["카페", "시장 연계"],
  },
  "le-vespe-cafe": {
    shortLabel: "레베스페",
    highlights: ["캐나다식 팬케이크 줄집", "에그 베네딕트", "산타 크로체 도보권"],
    reviewSignals: ["좌석 매우 적음", "주말 오픈런 권장"],
    bestFor: ["브런치", "산타크로체 연계"],
  },
  "melaleuca-bakery": {
    shortLabel: "멜라레우카",
    highlights: ["크루아상 맛집 강변 베이커리", "주말 브런치 인기", "회전 빠름"],
    reviewSignals: ["페이스트리 오전 소진", "강변 좌석이 명당"],
    bestFor: ["브런치", "베이커리"],
  },
  "amble-firenze": {
    shortLabel: "암블레",
    highlights: ["숨은 안뜰 빈티지 카페", "가구까지 전부 판매품", "폰테베키오 뒤"],
    reviewSignals: ["골목 안쪽 — 지도 필수", "저녁엔 아페리티보로 전환"],
    bestFor: ["휴식", "빈티지", "아페리티보"],
  },
  "santarosa-bistrot": {
    shortLabel: "산타로사",
    highlights: ["옛 성벽 아래 정원 비스트로", "파라솔 그늘 점심", "로컬 젊은층 아지트"],
    reviewSignals: ["날씨 좋은 날 진가", "주말 점심 예약 권장"],
    bestFor: ["정원 점심", "아페리티보"],
  },
  "pitti-gola-e-cantina": {
    shortLabel: "피티골라",
    highlights: ["피티 궁전 정면 와인바", "소믈리에 형제의 셀렉션", "소량 생산자 위주"],
    reviewSignals: ["잔당 가격 높은 편", "예산 말하고 맡기는 게 답"],
    bestFor: ["와인", "피티 연계"],
  },
  "le-volpi-e-luva": {
    shortLabel: "볼피에루바",
    highlights: ["폰테베키오 남단 와인바", "내추럴 와인+치즈", "작은 광장 테라스"],
    reviewSignals: ["테라스 선착순", "야경 보기 전 1잔 동선"],
    bestFor: ["아페리티보", "와인", "치즈"],
  },
  "signorvino-firenze": {
    shortLabel: "시뇨르비노",
    highlights: ["베키오 다리 정면 테라스", "와인숍 가격+콜키지 개념", "현실적 가격의 뷰"],
    reviewSignals: ["테라스는 예약 필수급", "식사는 평범하다는 평도"],
    bestFor: ["뷰 저녁", "와인"],
  },
  "gelateria-santa-trinita": {
    shortLabel: "산타트리니타",
    highlights: ["흑임자(세사모 네로) 유명", "다리 일몰 공식 조합", "강변 동선"],
    reviewSignals: ["일몰 30분 전 구매가 공식", "흑임자가 한국인 취향 저격"],
    bestFor: ["젤라또", "일몰", "사진"],
  },
  "my-sugar": {
    shortLabel: "마이슈가",
    highlights: ["부부 소량생산 장인 젤라또", "통 비면 그날 장사 끝", "아카데미아 3분"],
    reviewSignals: ["오후 늦으면 인기맛 소진", "소 사이즈도 충분"],
    bestFor: ["젤라또", "아카데미아 연계"],
  },
  "san-marco-museum": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Firenze%2C_san_marco%2C_facciata_02.jpg/330px-Firenze%2C_san_marco%2C_facciata_02.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/San_Marco%2C_Florence",
    shortLabel: "산마르코",
    wikiTitle: "San Marco, Florence",
    story:
      "프라 안젤리코가 수도사들의 방마다 그린 프레스코가 그대로 남은 수도원 미술관. '수태고지' 원본을 줄 없이 보는, 피렌체에서 가장 조용한 명작 공간이다. 아카데미아에서 도보 3분.",
    highlights: ["프라 안젤리코 수태고지", "줄 없는 명작 미술관", "수도원 방마다 프레스코"],
    reviewSignals: ["월요일 휴관 패턴 확인", "우피치 인파의 해독제"],
    bestFor: ["미술", "한산함", "아카데미아 연계"],
  },
  orsanmichele: {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Torre_di_arnolfo%2C_veduta_orsanmichele_33-edit.jpg/330px-Torre_di_arnolfo%2C_veduta_orsanmichele_33-edit.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Orsanmichele",
    shortLabel: "오르산미켈레",
    wikiTitle: "Orsanmichele",
    story:
      "곡물창고였다가 성당이 된 독특한 건물. 외벽 벽감마다 도나텔로 등 르네상스 거장들이 길드 수호성인을 조각해, 건물 한 바퀴가 야외 조각 교과서다.",
    highlights: ["길드 조각 야외 교과서", "곡물창고 출신 성당", "두오모-시뇨리아 경유 5분"],
    reviewSignals: ["외벽만 봐도 충분", "내부 개방 요일 제한"],
    bestFor: ["경유", "조각", "무료"],
  },
  "santo-spirito-basilica": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Chiesa_Santo_Spirito%2C_Firenze.jpg/330px-Chiesa_Santo_Spirito%2C_Firenze.jpg",
    imageSourceUrl: "https://en.wikipedia.org/wiki/Santo_Spirito%2C_Florence",
    shortLabel: "산토스피리토",
    wikiTitle: "Santo Spirito, Florence",
    story:
      "브루넬레스키 최후의 걸작으로 꼽히는 올트라르노의 성당. 내부엔 17세 미켈란젤로가 조각한 목제 십자가가 있고, 앞 광장은 저녁마다 동네 사랑방이 된다.",
    highlights: ["브루넬레스키 최후작", "미켈란젤로 목제 십자가", "광장 저녁 분위기"],
    reviewSignals: ["무료 입장", "광장 아페리티보와 묶기"],
    bestFor: ["성당", "광장", "올트라르노"],
  },
  "perche-no": {
    shortLabel: "페르케노",
    highlights: ["1939년 시뇨리아 근처", "피스타치오·세사미 강점", "전쟁 중에도 연 가게 스토리"],
    reviewSignals: ["좁은 입구 — 지나치기 쉬움", "클래식 맛이 강점"],
    bestFor: ["젤라또", "중심부 코스"],
  },
};
