import type { Place } from "./data";

// 2026-06 사이트 확장 수집분.
// 인기점수(rank) 기준: 90+ 대표/다중 출처/첫 방문 필수, 84-89 강력 추천, 76-83 동선형 인기,
// 70-75 취향형 후보. 구글 평점은 검증값이 아니므로 넣지 않는다.
export const sitePlaces: Place[] = [
  /* ===== 로마: 명소·전망·동네 ===== */
  {
    id: "maxxi",
    city: "rome",
    name: "MAXXI",
    koName: "막시 국립 21세기 미술관",
    category: "attraction",
    area: "플라미니오",
    lat: 41.9285,
    lng: 12.4663,
    priority: 3,
    rank: 78,
    durationMin: 80,
    reservation: "권장",
    bestTime: "오후",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["현대미술", "건축", "실내", "비오는날"],
    why: "자하 하디드가 설계한 로마 현대미술의 대표 공간. 고대 유적 위주의 일정에 감각적 반전을 준다.",
    tips: ["전시 일정 확인 후 방문", "플라미니오/포폴로 동선과 묶기"],
    koreanTips: ["사진은 외관 곡선과 계단 동선이 제일 잘 나온다."],
    pairWith: ["piazza-del-popolo", "villa-borghese", "pincio-terrace"],
    sourceIds: ["timeout-rome", "cntraveler-rome-things"],
  },
  {
    id: "centrale-montemartini",
    city: "rome",
    name: "Centrale Montemartini",
    koName: "첸트랄레 몬테마르티니",
    category: "attraction",
    area: "오스티엔세",
    lat: 41.8672,
    lng: 12.482,
    priority: 3,
    rank: 77,
    durationMin: 70,
    reservation: "불필요",
    bestTime: "오후",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 2,
    tags: ["고대조각", "산업건축", "실내", "한산"],
    why: "옛 발전소 기계 사이에 고대 조각을 배치한 독특한 박물관. 붐비는 중심부 미술관의 좋은 대안.",
    tips: ["테스타치오/가르바텔라 식당과 묶기", "전시실이 넓어 1시간 이상 잡기"],
    pairWith: ["testaccio-market", "mordi-e-vai", "basilica-san-paolo"],
    sourceIds: ["timeout-rome", "lonely-planet-rome"],
  },
  {
    id: "palazzo-altemps",
    city: "rome",
    name: "Palazzo Altemps",
    koName: "알템프스 궁전",
    category: "attraction",
    area: "나보나",
    lat: 41.9007,
    lng: 12.4735,
    priority: 3,
    rank: 76,
    durationMin: 55,
    reservation: "불필요",
    bestTime: "오전",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["조각", "궁전", "실내", "한산"],
    why: "나보나 광장 바로 뒤의 국립 로마 박물관 분관. 조용한 궁전 안에서 고대 조각을 가까이 본다.",
    tips: ["판테온-나보나 사이 비는 시간에 넣기", "국립 로마 박물관 통합권 여부 확인"],
    pairWith: ["piazza-navona", "pantheon", "da-francesco"],
    sourceIds: ["timeout-rome", "lonely-planet-rome"],
  },
  {
    id: "villa-farnesina",
    city: "rome",
    name: "Villa Farnesina",
    koName: "빌라 파르네시나",
    category: "attraction",
    area: "트라스테베레",
    lat: 41.8942,
    lng: 12.4676,
    priority: 3,
    rank: 78,
    durationMin: 55,
    reservation: "권장",
    bestTime: "오전",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["라파엘로", "프레스코", "실내", "숨은명소"],
    why: "라파엘로 프레스코가 남아 있는 르네상스 별장. 트라스테베레에서 가장 우아한 실내 명소다.",
    tips: ["운영 시간이 짧은 편이라 오전 우선", "트라스테베레 점심 전후로 묶기"],
    pairWith: ["trastevere", "santa-maria-trastevere", "bar-san-calisto"],
    sourceIds: ["cntraveler-rome-things", "timeout-rome"],
  },
  {
    id: "palazzo-spada",
    city: "rome",
    name: "Palazzo Spada",
    koName: "스파다 궁전",
    category: "attraction",
    area: "캄포 데 피오리",
    lat: 41.8946,
    lng: 12.4718,
    priority: 3,
    rank: 74,
    durationMin: 40,
    reservation: "불필요",
    bestTime: "오후",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 2,
    tags: ["보로미니", "착시", "실내", "30분컷"],
    why: "보로미니의 원근법 갤러리로 유명한 작은 궁전. 짧지만 기억에 남는 건축 포인트다.",
    tips: ["캄포 데 피오리와 나보나 사이에 짧게 삽입", "사진은 정면 축에서 찍기"],
    pairWith: ["campo-de-fiori", "piazza-navona", "forno-campo-de-fiori"],
    sourceIds: ["timeout-rome", "lonely-planet-rome"],
  },
  {
    id: "domus-aurea",
    city: "rome",
    name: "Domus Aurea",
    koName: "도무스 아우레아",
    category: "attraction",
    area: "콜로세움",
    lat: 41.8902,
    lng: 12.4955,
    priority: 2,
    rank: 84,
    durationMin: 75,
    reservation: "필수",
    bestTime: "주말/개방 회차",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["네로", "고대유적", "실내", "예약필수"],
    why: "네로 황제의 황금 궁전 유적. 개방 회차가 제한적이라 예약에 성공하면 로마 일정의 강한 한 수가 된다.",
    tips: ["공식 개방 회차 먼저 확인", "콜로세움 날에 넣으면 동선이 좋다"],
    pairWith: ["colosseum-forum", "la-taverna-dei-fori-imperiali"],
    sourceIds: ["timeout-rome", "cntraveler-rome-things"],
  },
  {
    id: "mercati-traiano",
    city: "rome",
    name: "Mercati di Traiano",
    koName: "트라야누스 시장",
    category: "attraction",
    area: "포리 임페리알리",
    lat: 41.8959,
    lng: 12.4858,
    priority: 2,
    rank: 82,
    durationMin: 70,
    reservation: "불필요",
    bestTime: "오전",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 2,
    tags: ["고대유적", "박물관", "실내", "전망"],
    why: "트라야누스 포럼을 위에서 내려다보며 고대 도시 구조를 입체적으로 이해할 수 있는 곳.",
    tips: ["비토리오 에마누엘레 기념관과 함께 보기", "외부 테라스에서 포럼 사진"],
    pairWith: ["altare-patria", "colosseum-forum", "capitoline-museums"],
    sourceIds: ["timeout-rome", "lonely-planet-rome"],
  },
  {
    id: "terme-di-diocleziano",
    city: "rome",
    name: "Terme di Diocleziano",
    koName: "디오클레티아누스 욕장",
    category: "attraction",
    area: "테르미니",
    lat: 41.9025,
    lng: 12.4986,
    priority: 3,
    rank: 75,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "기차 전후",
    price: "중간",
    safety: "주의",
    photo: 2,
    girlsTripFit: 2,
    tags: ["고대유적", "박물관", "실내", "역근처"],
    why: "테르미니 바로 옆 거대한 고대 목욕탕 유적. 이동일에 넣기 좋은 실내 후보.",
    tips: ["짐 맡긴 뒤 1시간 루트로 적합", "역 주변 소지품 주의"],
    pairWith: ["roma-termini", "santa-maria-maggiore", "regoli"],
    sourceIds: ["lonely-planet-rome", "timeout-rome"],
  },
  {
    id: "basilica-san-paolo",
    city: "rome",
    name: "Basilica di San Paolo fuori le Mura",
    koName: "성 바오로 대성당",
    category: "attraction",
    area: "오스티엔세",
    lat: 41.8587,
    lng: 12.477,
    priority: 3,
    rank: 78,
    durationMin: 55,
    reservation: "불필요",
    bestTime: "오전",
    price: "무료",
    safety: "보통",
    photo: 3,
    girlsTripFit: 2,
    tags: ["대성당", "무료", "한산", "실내"],
    why: "로마 4대 대성당 중 하나. 중심부보다 훨씬 한산하고 규모감이 압도적이다.",
    tips: ["지하철 B선으로 접근", "오스티엔세 식당과 함께 묶기"],
    pairWith: ["centrale-montemartini", "mordi-e-vai"],
    sourceIds: ["lonely-planet-rome", "timeout-rome"],
  },
  {
    id: "catacombe-san-callisto",
    city: "rome",
    name: "Catacombe di San Callisto",
    koName: "산 칼리스토 카타콤베",
    category: "attraction",
    area: "아피아 가도",
    lat: 41.8588,
    lng: 12.5104,
    priority: 3,
    rank: 76,
    durationMin: 70,
    reservation: "권장",
    bestTime: "오전",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["카타콤베", "고대기독교", "실내", "가이드"],
    why: "초기 기독교 지하 묘지를 가이드 투어로 보는 아피아 가도 대표 명소.",
    tips: ["아피아 안티카와 반나절 코스", "내부 촬영 제한 확인"],
    pairWith: ["appia-antica", "baths-caracalla"],
    sourceIds: ["lonely-planet-rome", "timeout-rome"],
  },
  {
    id: "teatro-marcello",
    city: "rome",
    name: "Teatro di Marcello",
    koName: "마르첼로 극장",
    category: "attraction",
    area: "유대인 지구",
    lat: 41.8923,
    lng: 12.4792,
    priority: 3,
    rank: 73,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "해질녘",
    price: "무료",
    safety: "보통",
    photo: 3,
    girlsTripFit: 2,
    tags: ["고대극장", "무료", "30분컷", "야경"],
    why: "콜로세움보다 작지만 도시 속에 자연스럽게 섞인 고대 극장. 유대인 지구 산책의 핵심 포인트.",
    tips: ["캄피돌리오에서 내려오며 보기", "저녁 조명 때 사진 좋음"],
    pairWith: ["jewish-ghetto", "fontana-tartarughe", "altare-patria"],
    sourceIds: ["lonely-planet-rome", "timeout-rome"],
  },
  {
    id: "fontana-tartarughe",
    city: "rome",
    name: "Fontana delle Tartarughe",
    koName: "거북이 분수",
    category: "view",
    area: "유대인 지구",
    lat: 41.8938,
    lng: 12.4775,
    priority: 3,
    rank: 72,
    durationMin: 20,
    reservation: "불필요",
    bestTime: "저녁",
    price: "무료",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["분수", "숨은광장", "무료", "30분컷"],
    why: "작은 광장에 숨은 르네상스 분수. 로마의 큰 명소 사이에 넣기 좋은 짧은 사진 포인트.",
    tips: ["유대인 지구 저녁 식사 전후", "광장이 작아 사람 적을 때가 좋음"],
    pairWith: ["jewish-ghetto", "teatro-marcello", "cul-de-sac"],
    sourceIds: ["timeout-rome", "lonely-planet-rome"],
  },
  {
    id: "villa-medici",
    city: "rome",
    name: "Villa Medici",
    koName: "빌라 메디치",
    category: "view",
    area: "스페인 계단",
    lat: 41.908,
    lng: 12.4829,
    priority: 3,
    rank: 74,
    durationMin: 45,
    reservation: "권장",
    bestTime: "해질녘 전",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["정원", "전망", "사진", "예약권장"],
    why: "스페인 계단 위 프랑스 아카데미 정원. 핀초 테라스와 이어지는 조용한 전망 루트다.",
    tips: ["가이드 투어 시간 확인", "스페인 계단 붐빌 때 위쪽으로 빠지기"],
    pairWith: ["spanish-steps", "pincio-terrace", "villa-borghese"],
    sourceIds: ["cntraveler-rome-things", "timeout-rome"],
  },
  {
    id: "palazzo-civilta-italiana",
    city: "rome",
    name: "Palazzo della Civilta Italiana",
    koName: "이탈리아 문명궁",
    category: "attraction",
    area: "EUR",
    lat: 41.8366,
    lng: 12.4656,
    priority: 3,
    rank: 70,
    durationMin: 35,
    reservation: "불필요",
    bestTime: "오후",
    price: "무료",
    safety: "보통",
    photo: 3,
    girlsTripFit: 2,
    tags: ["건축", "사진", "무료", "외곽"],
    why: "일명 사각 콜로세움. 고대와 전혀 다른 로마의 20세기 건축 이미지를 본다.",
    tips: ["EUR까지 일부러 가는 일정에만", "외관 사진 중심"],
    pairWith: ["basilica-san-paolo", "centrale-montemartini"],
    sourceIds: ["cntraveler-rome-things", "timeout-rome"],
  },
  {
    id: "non-catholic-cemetery",
    city: "rome",
    name: "Cimitero Acattolico",
    koName: "비가톨릭 묘지",
    category: "rest",
    area: "테스타치오",
    lat: 41.8762,
    lng: 12.4807,
    priority: 3,
    rank: 71,
    durationMin: 35,
    reservation: "불필요",
    bestTime: "오전",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["조용함", "문학", "테스타치오", "휴식"],
    why: "케츠와 셸리의 묘가 있는 조용한 정원 같은 공간. 피라미드 옆 산책 코스로 좋다.",
    tips: ["테스타치오 점심 전후로 짧게", "묘지라 조용히 이동"],
    pairWith: ["testaccio-market", "mordi-e-vai", "pizzeria-da-remo"],
    sourceIds: ["lonely-planet-rome", "timeout-rome"],
  },
  {
    id: "parco-acquedotti",
    city: "rome",
    name: "Parco degli Acquedotti",
    koName: "수도교 공원",
    category: "view",
    area: "아피아/남동부",
    lat: 41.8468,
    lng: 12.5615,
    priority: 3,
    rank: 72,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "해질녘",
    price: "무료",
    safety: "보통",
    photo: 3,
    girlsTripFit: 2,
    tags: ["공원", "수도교", "일몰", "무료"],
    why: "고대 수도교가 넓은 들판을 가르는 장면을 보는 로컬 산책지. 일몰 사진이 좋다.",
    tips: ["중심부에서 거리가 있어 여유 있는 날만", "밝을 때 이동"],
    pairWith: ["appia-antica", "catacombe-san-callisto"],
    sourceIds: ["timeout-rome", "lonely-planet-rome"],
  },

  /* ===== 로마: 맛집·카페·바 ===== */
  {
    id: "trattoria-pennestri",
    city: "rome",
    name: "Trattoria Pennestri",
    koName: "트라토리아 펜네스트리",
    category: "food",
    area: "오스티엔세",
    lat: 41.8689,
    lng: 12.478,
    priority: 2,
    rank: 86,
    durationMin: 90,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["트라토리아", "모던로마", "예약권장"],
    why: "Eater 로마 최신 리스트에서도 강조되는 현대 로마 트라토리아. 클래식 파스타보다 한 단계 세련된 저녁 후보.",
    tips: ["저녁 예약 권장", "오스티엔세/테스타치오 동선에 넣기"],
    koreanTips: ["분위기가 깔끔해 2인 여행 저녁으로 무난하다."],
    menuHints: ["아마트리치아나", "계절 전채", "내추럴 와인"],
    watchOut: ["중심부에서 약간 떨어짐"],
    pairWith: ["centrale-montemartini", "basilica-san-paolo"],
    sourceIds: ["eater-rome", "cntraveler-rome"],
  },
  {
    id: "elementare-trastevere",
    city: "rome",
    name: "L'Elementare Trastevere",
    koName: "레레멘타레 트라스테베레",
    category: "food",
    area: "트라스테베레",
    lat: 41.8879,
    lng: 12.4678,
    priority: 2,
    rank: 82,
    durationMin: 70,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["피자", "트라스테베레", "캐주얼", "웨이팅"],
    why: "트라스테베레에서 접근 쉬운 현대 피자 후보. 로마식과 나폴리식 사이의 캐주얼한 선택지다.",
    tips: ["저녁 피크 전 예약/오픈런", "수플리와 피자를 나눠 주문"],
    menuHints: ["마르게리타", "수플리", "계절 피자"],
    pairWith: ["trastevere", "santa-maria-trastevere", "freni-e-frizioni"],
    sourceIds: ["eater-rome", "timeout-rome"],
  },
  {
    id: "mostro-rome",
    city: "rome",
    name: "Mostro",
    koName: "모스트로",
    category: "food",
    area: "오스티엔세",
    lat: 41.8649,
    lng: 12.4793,
    priority: 3,
    rank: 79,
    durationMin: 80,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["피자", "맥주", "신규인기"],
    why: "Eater 최신 업데이트에 오른 캐주얼 피자/맥주 후보. 중심부 관광식당을 피하고 싶을 때 좋다.",
    tips: ["오스티엔세 저녁 후보로 저장", "맥주와 피자 조합"],
    menuHints: ["피자", "크래프트 맥주", "튀김 전채"],
    pairWith: ["trattoria-pennestri", "centrale-montemartini"],
    sourceIds: ["eater-rome"],
  },
  {
    id: "mazzo-rome",
    city: "rome",
    name: "Mazzo",
    koName: "마초",
    category: "food",
    area: "첸토첼레",
    lat: 41.8791,
    lng: 12.5664,
    priority: 3,
    rank: 80,
    durationMin: 90,
    reservation: "필수",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["모던", "로컬", "예약필수", "외곽"],
    why: "로마 음식 매체들이 자주 언급하는 모던 로컬 식당. 외곽까지 갈 의지가 있을 때 보상감이 크다.",
    tips: ["예약 먼저, 동선은 별도 저녁으로", "택시 복귀 예산 고려"],
    menuHints: ["계절 메뉴", "파스타", "내추럴 와인"],
    watchOut: ["중심부에서 멀다"],
    pairWith: ["parco-acquedotti"],
    sourceIds: ["eater-rome", "cntraveler-rome"],
  },
  {
    id: "menabo-vino-cucina",
    city: "rome",
    name: "Menabo Vino e Cucina",
    koName: "메나보 비노 에 쿠치나",
    category: "food",
    area: "노멘타나",
    lat: 41.9235,
    lng: 12.5195,
    priority: 3,
    rank: 78,
    durationMin: 85,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["와인", "로컬", "동네식당"],
    why: "중심부 밖 로컬 와인 바 겸 식당 후보. 관광지 가격과 분위기에서 벗어나고 싶을 때 유용하다.",
    tips: ["와인 추천을 맡기기", "시내 일정 빡빡한 날은 제외"],
    menuHints: ["파스타", "치즈", "내추럴 와인"],
    pairWith: ["villa-borghese", "maxxi"],
    sourceIds: ["eater-rome"],
  },
  {
    id: "la-gatta-mangiona",
    city: "rome",
    name: "La Gatta Mangiona",
    koName: "라 가타 만조나",
    category: "food",
    area: "몬테베르데",
    lat: 41.8724,
    lng: 12.4569,
    priority: 3,
    rank: 79,
    durationMin: 80,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["피자", "로컬", "수상경력"],
    why: "오랫동안 로마 피자 애호가들이 추천해 온 외곽 피자집. 클래식보다 완성도 높은 피자에 집중한다.",
    tips: ["트라스테베레에서 택시/버스 이동", "예약 권장"],
    menuHints: ["마르게리타", "창작 피자", "수플리"],
    pairWith: ["da-cesare-al-casaletto", "trastevere"],
    sourceIds: ["eater-rome", "katie-parla-rome"],
  },
  {
    id: "centottanta-grammi",
    city: "rome",
    name: "180g Pizzeria Romana",
    koName: "센토탄타 그람미 피체리아 로마나",
    category: "food",
    area: "첸토첼레",
    lat: 41.8866,
    lng: 12.5602,
    priority: 3,
    rank: 81,
    durationMin: 80,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["피자", "로마식", "외곽", "수상경력"],
    why: "초박형 로마식 피자를 현대적으로 끌어올린 곳. 피자 목적지로 일부러 가는 후보.",
    tips: ["외곽 이동 시간을 감안", "튀김 전채도 함께"],
    menuHints: ["로마식 피자", "수플리", "프리티"],
    pairWith: ["parco-acquedotti"],
    sourceIds: ["eater-rome", "katie-parla-rome"],
  },
  {
    id: "roma-sparita",
    city: "rome",
    name: "Roma Sparita",
    koName: "로마 스파리타",
    category: "food",
    area: "트라스테베레",
    lat: 41.8891,
    lng: 12.4692,
    priority: 2,
    rank: 82,
    durationMin: 85,
    reservation: "권장",
    bestTime: "점심",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["카초에페페", "트라스테베레", "한국인선호"],
    why: "치즈 바구니 카초 에 페페로 유명한 트라스테베레 식당. 여행자에게 설명하기 쉬운 한 접시가 있다.",
    tips: ["점심 예약이 더 편함", "카초 에 페페는 1개 공유"],
    koreanTips: ["간이 강할 수 있어 샐러드/구이와 균형 맞추기"],
    menuHints: ["카초 에 페페", "아티초크", "세콘디"],
    pairWith: ["trastevere", "santa-maria-trastevere"],
    sourceIds: ["cntraveler-rome", "timeout-rome"],
  },
  {
    id: "checco-er-carettiere",
    city: "rome",
    name: "Checco er Carettiere",
    koName: "케코 에르 카레티에레",
    category: "food",
    area: "트라스테베레",
    lat: 41.8894,
    lng: 12.4681,
    priority: 2,
    rank: 81,
    durationMin: 85,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["트라토리아", "클래식", "트라스테베레"],
    why: "트라스테베레의 전통 로마 요리 후보. 분위기는 클래식하고 메뉴는 이해하기 쉽다.",
    tips: ["저녁 예약 권장", "트라스테베레 산책 전후"],
    menuHints: ["카르보나라", "아마트리치아나", "소꼬리찜"],
    pairWith: ["trastevere", "bar-san-calisto"],
    sourceIds: ["cntraveler-rome", "katie-parla-rome"],
  },
  {
    id: "flavio-velavevodetto",
    city: "rome",
    name: "Flavio al Velavevodetto",
    koName: "플라비오 알 벨라베보데토",
    category: "food",
    area: "테스타치오",
    lat: 41.8752,
    lng: 12.4753,
    priority: 2,
    rank: 84,
    durationMin: 85,
    reservation: "권장",
    bestTime: "점심 또는 저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["트라토리아", "테스타치오", "클래식"],
    why: "테스타치오의 대표 로마 트라토리아. 전통 파스타와 내장 요리를 안정적으로 먹기 좋은 곳.",
    tips: ["예약 권장", "테스타치오 시장/피라미드와 묶기"],
    menuHints: ["카르보나라", "아마트리치아나", "티라미수"],
    pairWith: ["testaccio-market", "mordi-e-vai", "non-catholic-cemetery"],
    sourceIds: ["eater-rome", "cntraveler-rome"],
  },
  {
    id: "perilli-testaccio",
    city: "rome",
    name: "Perilli",
    koName: "페릴리",
    category: "food",
    area: "테스타치오",
    lat: 41.8765,
    lng: 12.4767,
    priority: 2,
    rank: 83,
    durationMin: 85,
    reservation: "권장",
    bestTime: "점심",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["카르보나라", "클래식", "테스타치오"],
    why: "카르보나라 고전파로 자주 언급되는 테스타치오 식당. 로마 파스타 기준점을 잡기 좋다.",
    tips: ["점심 예약 추천", "진한 소스라 둘이 파스타+세콘도 공유"],
    menuHints: ["카르보나라", "그리치아", "아티초크"],
    pairWith: ["testaccio-market", "flavio-velavevodetto"],
    sourceIds: ["eater-rome", "katie-parla-rome"],
  },
  {
    id: "mordi-e-vai",
    city: "rome",
    name: "Mordi e Vai",
    koName: "모르디 에 바이",
    category: "food",
    area: "테스타치오 시장",
    lat: 41.8768,
    lng: 12.475,
    priority: 2,
    rank: 84,
    durationMin: 30,
    reservation: "불필요",
    bestTime: "점심",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["시장", "샌드위치", "가성비", "30분컷"],
    why: "테스타치오 시장의 로마식 고기 샌드위치 대표. 빠르고 싸고 현지성이 강하다.",
    tips: ["점심에만 넣기", "소스 있는 메뉴는 서서 먹기 불편할 수 있음"],
    koreanTips: ["파니니보다 든든한 시장 한 끼로 좋다."],
    menuHints: ["알레소 샌드위치", "트리파", "브로콜리"],
    pairWith: ["testaccio-market", "flavio-velavevodetto", "centrale-montemartini"],
    sourceIds: ["eater-rome", "katie-parla-rome"],
  },
  {
    id: "faro-caffe",
    city: "rome",
    name: "Faro Caffe",
    koName: "파로 카페",
    category: "cafe",
    area: "살라리오",
    lat: 41.912,
    lng: 12.5066,
    priority: 3,
    rank: 76,
    durationMin: 35,
    reservation: "불필요",
    bestTime: "오전",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["스페셜티커피", "브런치", "실내"],
    why: "로마에서 스페셜티 커피가 필요할 때 넣기 좋은 카페. 에스프레소 바와 다른 결이다.",
    tips: ["관광 중심부와 떨어져 있어 일부러 갈 때만", "브런치와 커피를 함께"],
    menuHints: ["필터 커피", "카푸치노", "브런치"],
    pairWith: ["villa-borghese", "santa-maria-maggiore"],
    sourceIds: ["eater-rome", "timeout-rome"],
  },
  {
    id: "casa-manfredi",
    city: "rome",
    name: "Casa Manfredi",
    koName: "카사 만프레디",
    category: "cafe",
    area: "아벤티노/테스타치오",
    lat: 41.8812,
    lng: 12.4775,
    priority: 3,
    rank: 75,
    durationMin: 30,
    reservation: "불필요",
    bestTime: "오전",
    price: "낮음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["카페", "페이스트리", "아침"],
    why: "아벤티노와 테스타치오 사이의 페이스트리 카페. 아침 루트에 넣기 좋다.",
    tips: ["오렌지 정원 전후 커피", "크루아상류가 강점"],
    menuHints: ["마리토초", "코르네토", "카푸치노"],
    pairWith: ["orange-garden", "aventine-keyhole", "testaccio-market"],
    sourceIds: ["eater-rome", "katie-parla-rome"],
  },
  {
    id: "linari",
    city: "rome",
    name: "Linari",
    koName: "리나리",
    category: "cafe",
    area: "테스타치오",
    lat: 41.8768,
    lng: 12.4755,
    priority: 3,
    rank: 73,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "아침",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["카페", "빵", "테스타치오", "아침"],
    why: "테스타치오 주민들이 쓰는 베이커리 카페. 시장 전후 간단한 아침으로 현실적이다.",
    tips: ["서서 커피 한 잔이면 빠르다", "점심 전 샌드위치도 가능"],
    menuHints: ["코르네토", "트라메치노", "카푸치노"],
    pairWith: ["testaccio-market", "mordi-e-vai"],
    sourceIds: ["katie-parla-rome", "eater-rome"],
  },
  {
    id: "salotto-42",
    city: "rome",
    name: "Salotto 42",
    koName: "살로토 42",
    category: "cafe",
    area: "판테온",
    lat: 41.8991,
    lng: 12.4788,
    priority: 3,
    rank: 76,
    durationMin: 60,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["칵테일", "분위기", "판테온"],
    why: "하드리아누스 신전 앞 테라스가 인상적인 중심부 칵테일 바. 야간 판테온 동선에 좋다.",
    tips: ["테라스석은 일찍", "식사보다 아페리티보/칵테일 용도"],
    menuHints: ["아페롤 스프리츠", "네그로니", "아페리티보"],
    pairWith: ["pantheon", "sant-eustachio", "piazza-navona"],
    sourceIds: ["cntraveler-rome", "timeout-rome"],
  },
  {
    id: "freni-e-frizioni",
    city: "rome",
    name: "Freni e Frizioni",
    koName: "프레니 에 프리치오니",
    category: "cafe",
    area: "트라스테베레",
    lat: 41.8891,
    lng: 12.4696,
    priority: 3,
    rank: 75,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["아페리티보", "칵테일", "트라스테베레"],
    why: "트라스테베레의 대표 아페리티보 바. 저녁 식사 전 분위기 전환용으로 쓰기 쉽다.",
    tips: ["테라스/광장 자리는 빠르게 찬다", "가볍게 한 잔만"],
    menuHints: ["스프리츠", "네그로니", "아페리티보"],
    pairWith: ["trastevere", "bar-san-calisto", "santa-maria-trastevere"],
    sourceIds: ["timeout-rome", "cntraveler-rome"],
  },
  {
    id: "bar-san-calisto",
    city: "rome",
    name: "Bar San Calisto",
    koName: "바 산 칼리스토",
    category: "cafe",
    area: "트라스테베레",
    lat: 41.8899,
    lng: 12.4703,
    priority: 3,
    rank: 74,
    durationMin: 30,
    reservation: "불필요",
    bestTime: "저녁",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["로컬바", "맥주", "가성비", "트라스테베레"],
    why: "트라스테베레 로컬 바의 상징 같은 곳. 저렴하고 시끌시끌한 분위기를 짧게 체험한다.",
    tips: ["현금 소액 준비", "긴 체류보다 분위기만 맛보기"],
    menuHints: ["맥주", "아마로", "젤라또"],
    pairWith: ["trastevere", "freni-e-frizioni"],
    sourceIds: ["timeout-rome", "katie-parla-rome"],
  },
  {
    id: "pierluigi-rome",
    city: "rome",
    name: "Pierluigi",
    koName: "피에르루이지",
    category: "food",
    area: "캄포 데 피오리",
    lat: 41.8953,
    lng: 12.47,
    priority: 3,
    rank: 79,
    durationMin: 100,
    reservation: "필수",
    bestTime: "저녁",
    price: "높음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["해산물", "고급", "예약필수"],
    why: "로마 중심부에서 해산물 저녁을 고급스럽게 먹는 대표 후보. 파스타 반복에 지쳤을 때 전환점이 된다.",
    tips: ["예산 높은 날만", "야외석은 예약 필수급"],
    menuHints: ["해산물 파스타", "생선구이", "굴"],
    watchOut: ["가격대 높음"],
    pairWith: ["campo-de-fiori", "piazza-navona", "palazzo-spada"],
    sourceIds: ["cntraveler-rome", "timeout-rome"],
  },
  {
    id: "antica-pesa-rome",
    city: "rome",
    name: "Antica Pesa",
    koName: "안티카 페사",
    category: "food",
    area: "트라스테베레",
    lat: 41.8887,
    lng: 12.4669,
    priority: 3,
    rank: 80,
    durationMin: 100,
    reservation: "필수",
    bestTime: "저녁",
    price: "높음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["고급트라토리아", "예약필수", "트라스테베레"],
    why: "오래된 트라토리아를 세련되게 운영하는 트라스테베레 고급 저녁 후보. 특별한 저녁용.",
    tips: ["예약 필수", "캐주얼 맛집보다 예산을 높게 잡기"],
    menuHints: ["카르보나라", "아마트리치아나", "세콘디"],
    watchOut: ["관광객도 많고 가격대 높음"],
    pairWith: ["trastevere", "villa-farnesina"],
    sourceIds: ["cntraveler-rome", "timeout-rome"],
  },

  /* ===== 피렌체: 명소·전망·쇼핑 ===== */
  {
    id: "opera-duomo-museum",
    city: "florence",
    name: "Museo dell'Opera del Duomo",
    koName: "두오모 오페라 박물관",
    category: "attraction",
    area: "두오모",
    lat: 43.7731,
    lng: 11.2562,
    priority: 2,
    rank: 86,
    durationMin: 80,
    reservation: "권장",
    bestTime: "두오모 전후",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["두오모", "미술관", "실내", "미켈란젤로"],
    why: "두오모 외부 조각 원본과 미켈란젤로 피에타를 보는 핵심 실내 명소. 두오모 이해도가 확 올라간다.",
    tips: ["두오모 통합권 동선에 넣기", "실내라 더운 날/비 오는 날 좋음"],
    pairWith: ["duomo-florence", "baptistery-florence", "giottos-campanile"],
    sourceIds: ["duomo-official", "cntraveler-florence-things", "timeout-florence"],
  },
  {
    id: "giottos-campanile",
    city: "florence",
    name: "Giotto's Campanile",
    koName: "조토의 종탑",
    category: "view",
    area: "두오모",
    lat: 43.7734,
    lng: 11.2557,
    priority: 2,
    rank: 84,
    durationMin: 60,
    reservation: "권장",
    bestTime: "오전",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["전망", "계단", "예약권장", "두오모"],
    why: "쿠폴라 대신 두오모 돔을 정면으로 보는 전망 선택지. 사진 목적이면 종탑이 더 직관적이다.",
    tips: ["계단 400개 이상, 물 챙기기", "쿠폴라와 같은 날 둘 다 하면 체력 부담"],
    pairWith: ["duomo-florence", "opera-duomo-museum", "edoardo-gelato"],
    sourceIds: ["duomo-official", "cntraveler-florence-things"],
  },
  {
    id: "baptistery-florence",
    city: "florence",
    name: "Battistero di San Giovanni",
    koName: "산 조반니 세례당",
    category: "attraction",
    area: "두오모",
    lat: 43.7732,
    lng: 11.2556,
    priority: 2,
    rank: 83,
    durationMin: 35,
    reservation: "권장",
    bestTime: "두오모 전후",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["모자이크", "두오모", "실내", "30분컷"],
    why: "황금 모자이크 천장과 '천국의 문'으로 두오모 광장의 의미를 완성하는 장소.",
    tips: ["두오모 통합권 확인", "목을 오래 젖히니 천천히 보기"],
    pairWith: ["duomo-florence", "opera-duomo-museum"],
    sourceIds: ["duomo-official", "cntraveler-florence-things"],
  },
  {
    id: "laurenziana-library",
    city: "florence",
    name: "Biblioteca Medicea Laurenziana",
    koName: "라우렌치아나 도서관",
    category: "attraction",
    area: "산 로렌초",
    lat: 43.7744,
    lng: 11.2539,
    priority: 3,
    rank: 75,
    durationMin: 35,
    reservation: "권장",
    bestTime: "오전",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["미켈란젤로", "건축", "실내", "30분컷"],
    why: "미켈란젤로가 설계한 계단과 열람실을 보는 건축 취향 명소. 산 로렌초권 짧은 보강에 좋다.",
    tips: ["개방 시간이 제한적이라 확인", "메디치 예배당과 묶기"],
    pairWith: ["basilica-san-lorenzo", "medici-chapels", "san-lorenzo-market"],
    sourceIds: ["feelflorence", "timeout-florence"],
  },
  {
    id: "stibbert-museum",
    city: "florence",
    name: "Museo Stibbert",
    koName: "스티버트 박물관",
    category: "attraction",
    area: "북쪽 언덕",
    lat: 43.79,
    lng: 11.2571,
    priority: 3,
    rank: 76,
    durationMin: 90,
    reservation: "권장",
    bestTime: "오후",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 2,
    tags: ["갑옷", "저택", "실내", "숨은명소"],
    why: "갑옷, 무기, 저택 인테리어가 압도적인 피렌체 외곽 박물관. 우피치와 전혀 다른 재미가 있다.",
    tips: ["중심부에서 이동 필요", "가이드 투어/운영 시간 확인"],
    pairWith: ["fiesole", "san-marco-museum"],
    sourceIds: ["cntraveler-florence-things", "timeout-florence"],
  },
  {
    id: "forte-belvedere",
    city: "florence",
    name: "Forte di Belvedere",
    koName: "벨베데레 요새",
    category: "view",
    area: "올트라르노",
    lat: 43.7627,
    lng: 11.2535,
    priority: 3,
    rank: 74,
    durationMin: 45,
    reservation: "확인",
    bestTime: "해질녘 전",
    price: "확인",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["전망", "요새", "사진", "계절개방"],
    why: "미켈란젤로 광장보다 조용한 전망 후보. 시즌 전시와 함께 열리는지 확인하면 좋다.",
    tips: ["운영 여부 먼저 확인", "보볼리/피티와 언덕 동선"],
    pairWith: ["pitti-boboli", "piazzale-michelangelo", "santo-spirito-basilica"],
    sourceIds: ["feelflorence", "timeout-florence"],
  },
  {
    id: "santa-felicita-capponi",
    city: "florence",
    name: "Santa Felicita Capponi Chapel",
    koName: "산타 펠리치타 카포니 예배당",
    category: "attraction",
    area: "폰테베키오",
    lat: 43.7668,
    lng: 11.2534,
    priority: 3,
    rank: 76,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "오전",
    price: "무료",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["폰토르모", "성당", "무료", "30분컷"],
    why: "폰테베키오 바로 건너 숨은 예배당. 폰토르모의 색감 강한 프레스코를 짧게 볼 수 있다.",
    tips: ["예배 시간 피하기", "사진보다 실제 색감 감상"],
    pairWith: ["ponte-vecchio", "pitti-boboli", "buca-dell-orafo"],
    sourceIds: ["livingetc-florence", "feelflorence"],
  },
  {
    id: "loggia-dei-lanzi",
    city: "florence",
    name: "Loggia dei Lanzi",
    koName: "란치의 회랑",
    category: "attraction",
    area: "시뇨리아",
    lat: 43.7697,
    lng: 11.2559,
    priority: 2,
    rank: 82,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "밤 산책",
    price: "무료",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["조각", "무료", "야경", "30분컷"],
    why: "시뇨리아 광장에 열린 야외 조각 갤러리. 우피치 입장 없이도 피렌체 조각의 힘을 느낀다.",
    tips: ["밤 조명 때 사진 좋음", "사람 많은 시간에도 짧게 보기 쉬움"],
    pairWith: ["piazza-signoria", "uffizi", "palazzo-vecchio"],
    sourceIds: ["feelflorence", "cntraveler-florence-things"],
  },
  {
    id: "piazza-repubblica-florence",
    city: "florence",
    name: "Piazza della Repubblica",
    koName: "레푸블리카 광장",
    category: "view",
    area: "중심부",
    lat: 43.7714,
    lng: 11.2539,
    priority: 3,
    rank: 72,
    durationMin: 20,
    reservation: "불필요",
    bestTime: "저녁",
    price: "무료",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["광장", "회전목마", "무료", "30분컷"],
    why: "회전목마와 카페 불빛이 있는 중심부 광장. 두오모-시뇨리아 사이 쉬어가는 지점이다.",
    tips: ["밤 산책 사진", "카페는 자리값 감안"],
    pairWith: ["caffe-gilli", "duomo-florence", "via-tornabuoni"],
    sourceIds: ["timeout-florence", "feelflorence"],
  },
  {
    id: "casa-buonarroti",
    city: "florence",
    name: "Casa Buonarroti",
    koName: "부오나로티의 집",
    category: "attraction",
    area: "산타 크로체",
    lat: 43.7687,
    lng: 11.262,
    priority: 3,
    rank: 72,
    durationMin: 45,
    reservation: "불필요",
    bestTime: "오후",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["미켈란젤로", "실내", "한산"],
    why: "미켈란젤로 가문의 집 박물관. 대형 명소보다 조용하게 미켈란젤로 흔적을 따라간다.",
    tips: ["산타 크로체권 빈 시간에", "아카데미아와 비교하면 소규모"],
    pairWith: ["santa-croce", "teatro-del-sale", "mercato-sant-ambrogio"],
    sourceIds: ["feelflorence", "timeout-florence"],
  },
  {
    id: "museo-novecento",
    city: "florence",
    name: "Museo Novecento",
    koName: "노베첸토 미술관",
    category: "attraction",
    area: "산타 마리아 노벨라",
    lat: 43.7728,
    lng: 11.2495,
    priority: 3,
    rank: 71,
    durationMin: 60,
    reservation: "불필요",
    bestTime: "오후",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["현대미술", "실내", "역근처"],
    why: "르네상스 미술에 지칠 때 넣는 20세기 미술관. SMN 역과 가까워 이동일에도 좋다.",
    tips: ["전시 일정 확인", "오피치와 같은 날이면 무리하지 않기"],
    pairWith: ["santa-maria-novella", "officina-profumo", "santa-maria-novella-basilica"],
    sourceIds: ["feelflorence", "timeout-florence"],
  },
  {
    id: "la-specola",
    city: "florence",
    name: "La Specola",
    koName: "라 스페콜라 자연사 박물관",
    category: "attraction",
    area: "올트라르노",
    lat: 43.7639,
    lng: 11.2489,
    priority: 3,
    rank: 72,
    durationMin: 70,
    reservation: "권장",
    bestTime: "오후",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 1,
    tags: ["자연사", "왁스해부", "실내", "취향"],
    why: "해부학 왁스 컬렉션으로 유명한 특이한 자연사 박물관. 취향이 맞으면 강렬하다.",
    tips: ["민감하면 패스", "피티/보볼리 권역에 추가"],
    watchOut: ["해부학 전시가 불편할 수 있음"],
    pairWith: ["pitti-boboli", "ristorante-il-guscio", "osteria-santo-spirito"],
    sourceIds: ["feelflorence", "timeout-florence"],
  },
  {
    id: "marino-marini-museum",
    city: "florence",
    name: "Museo Marino Marini",
    koName: "마리노 마리니 미술관",
    category: "attraction",
    area: "산타 마리아 노벨라",
    lat: 43.7713,
    lng: 11.2496,
    priority: 3,
    rank: 70,
    durationMin: 50,
    reservation: "불필요",
    bestTime: "오후",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["조각", "현대미술", "실내", "한산"],
    why: "옛 성당 공간에 현대 조각을 배치한 미술관. 붐비는 중심부에서 숨 돌리기 좋다.",
    tips: ["SMN 근처 짧은 실내 후보", "현대 조각 취향이면 추천"],
    pairWith: ["officina-profumo", "santa-maria-novella-basilica"],
    sourceIds: ["feelflorence", "timeout-florence"],
  },
  {
    id: "galleria-romanelli",
    city: "florence",
    name: "Galleria Romanelli",
    koName: "로마넬리 조각 공방",
    category: "shopping",
    area: "올트라르노",
    lat: 43.7651,
    lng: 11.2477,
    priority: 3,
    rank: 73,
    durationMin: 35,
    reservation: "권장",
    bestTime: "오후",
    price: "확인",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["장인", "공방", "디자인", "쇼핑"],
    why: "전통 조각 공방의 분위기를 보는 디자인 취향 장소. 피렌체가 아직 공방 도시라는 감각을 준다.",
    tips: ["방문 가능 시간 확인", "쇼핑보다 구경/사진 목적"],
    pairWith: ["pitti-boboli", "santo-spirito-basilica", "flair-firenze"],
    sourceIds: ["livingetc-florence", "timeout-florence"],
  },
  {
    id: "castorina-1895",
    city: "florence",
    name: "Castorina 1895",
    koName: "카스토리나 1895",
    category: "shopping",
    area: "중심부",
    lat: 43.7716,
    lng: 11.2535,
    priority: 3,
    rank: 71,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "오후",
    price: "확인",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["장인", "목공", "기념품", "쇼핑"],
    why: "오래된 목공/장식 상점. 흔한 가죽 기념품 말고 장인 느낌의 소품을 보고 싶을 때.",
    tips: ["가격대 확인", "작은 소품 위주로 보기"],
    pairWith: ["piazza-repubblica-florence", "via-tornabuoni", "caffe-gilli"],
    sourceIds: ["livingetc-florence"],
  },
  {
    id: "flair-firenze",
    city: "florence",
    name: "Flair",
    koName: "플레어 피렌체",
    category: "shopping",
    area: "아르노 강변",
    lat: 43.77,
    lng: 11.2479,
    priority: 3,
    rank: 72,
    durationMin: 30,
    reservation: "불필요",
    bestTime: "오후",
    price: "높음",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["인테리어", "디자인", "쇼핑", "장인"],
    why: "빈티지와 현대 디자인을 섞은 피렌체 감성 쇼룸. 구경만 해도 눈이 즐겁다.",
    tips: ["강변 산책 중 짧게", "구매보다 영감/사진 목적"],
    pairWith: ["via-tornabuoni", "officina-profumo", "galleria-romanelli"],
    sourceIds: ["livingetc-florence", "timeout-florence"],
  },

  /* ===== 피렌체: 맛집·카페·바 ===== */
  {
    id: "trattoria-da-burde",
    city: "florence",
    name: "Trattoria Da Burde",
    koName: "트라토리아 다 부르데",
    category: "food",
    area: "노볼리/외곽",
    lat: 43.7869,
    lng: 11.206,
    priority: 3,
    rank: 84,
    durationMin: 95,
    reservation: "필수",
    bestTime: "점심",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["전통", "외곽", "예약필수", "로컬"],
    why: "Eater가 전통 피렌체 음식의 외곽 명가로 강하게 추천한 가족 운영 식당. 진짜 로컬 점심용.",
    tips: ["트램/택시 이동 감안", "점심 운영 위주라 시간 확인"],
    menuHints: ["리볼리타", "고기구이", "와인"],
    watchOut: ["중심부 동선과 멀다"],
    pairWith: ["santa-maria-novella", "museo-novecento"],
    sourceIds: ["eater-florence", "cntraveler-florence"],
  },
  {
    id: "pizzeria-giovanni-santarpia",
    city: "florence",
    name: "Pizzeria Giovanni Santarpia",
    koName: "조반니 산타르피아 피체리아",
    category: "food",
    area: "캄포 디 마르테",
    lat: 43.7665,
    lng: 11.287,
    priority: 3,
    rank: 80,
    durationMin: 80,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 2,
    tags: ["피자", "나폴리식", "외곽"],
    why: "피렌체에서 피자가 필요할 때 넣을 만한 강한 후보. 중심부 파스타 반복을 끊어 준다.",
    tips: ["저녁 예약 권장", "두오모권에서 바로 걷기엔 멀다"],
    menuHints: ["마르게리타", "나폴리식 피자", "프리티"],
    pairWith: ["santa-croce", "mercato-sant-ambrogio"],
    sourceIds: ["eater-florence", "cntraveler-florence"],
  },
  {
    id: "cucina-florence",
    city: "florence",
    name: "Cucina",
    koName: "쿠치나",
    category: "food",
    area: "산 로렌초",
    lat: 43.7763,
    lng: 11.2578,
    priority: 3,
    rank: 78,
    durationMin: 80,
    reservation: "권장",
    bestTime: "점심",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["파스타", "모던", "중심부"],
    why: "Eater 리스트에 오른 산 로렌초권 파스타 후보. 중앙시장 주변에서 너무 관광식당스럽지 않은 선택지.",
    tips: ["점심 예약/오픈런", "시장 구경 후 식사"],
    menuHints: ["뇨케티", "계절 파스타", "와인"],
    pairWith: ["mercato-centrale", "basilica-san-lorenzo", "my-sugar"],
    sourceIds: ["eater-florence"],
  },
  {
    id: "la-vecchia-bettola",
    city: "florence",
    name: "La Vecchia Bettola",
    koName: "라 베키아 베톨라",
    category: "food",
    area: "올트라르노",
    lat: 43.7639,
    lng: 11.2439,
    priority: 2,
    rank: 83,
    durationMin: 85,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["보드카파스타", "전통", "올트라르노"],
    why: "토마토 보드카 파스타로 유명한 올트라르노 식당. 피렌체에서 기억에 남는 한 접시 후보.",
    tips: ["피크 예약 권장", "파스타와 고기 메뉴를 나눠 먹기"],
    menuHints: ["보드카 파스타", "비프스테이크", "하우스 와인"],
    pairWith: ["santo-spirito-basilica", "pitti-boboli", "ristorante-il-guscio"],
    sourceIds: ["eater-florence", "curious-appetite"],
  },
  {
    id: "ristorante-il-guscio",
    city: "florence",
    name: "Ristorante Il Guscio",
    koName: "일 구쇼",
    category: "food",
    area: "올트라르노",
    lat: 43.7658,
    lng: 11.244,
    priority: 2,
    rank: 82,
    durationMin: 90,
    reservation: "필수",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["토스카나", "올트라르노", "예약필수"],
    why: "올트라르노의 안정적인 저녁 식당. 전통과 현대 사이에서 2인 저녁으로 균형이 좋다.",
    tips: ["저녁 예약 필수급", "피티/산토 스피리토 날에 넣기"],
    menuHints: ["파스타", "비istecca", "토스카나 와인"],
    pairWith: ["pitti-boboli", "santo-spirito-basilica", "la-specola"],
    sourceIds: ["eater-florence", "cntraveler-florence"],
  },
  {
    id: "casa-ciabattini",
    city: "florence",
    name: "Casa Ciabattini",
    koName: "카사 치아바티니",
    category: "food",
    area: "중심부",
    lat: 43.775,
    lng: 11.2551,
    priority: 3,
    rank: 77,
    durationMin: 70,
    reservation: "권장",
    bestTime: "점심",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["트라토리아", "중심부", "점심"],
    why: "Eater 피렌체 리스트의 중심부 식당 후보. 이동이 쉬운 점심 대안으로 저장할 만하다.",
    tips: ["메뉴/운영 시간 확인", "중앙시장과 산 로렌초 사이에 넣기"],
    menuHints: ["파스타", "토스카나 전채", "고기"],
    pairWith: ["mercato-centrale", "duomo-florence", "san-lorenzo-market"],
    sourceIds: ["eater-florence"],
  },
  {
    id: "burro-acciughe",
    city: "florence",
    name: "Burro & Acciughe",
    koName: "부로 에 아추게",
    category: "food",
    area: "올트라르노",
    lat: 43.768,
    lng: 11.2438,
    priority: 3,
    rank: 78,
    durationMin: 80,
    reservation: "권장",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["해산물", "와인", "올트라르노"],
    why: "피렌체에서 해산물과 와인으로 방향을 바꾸는 후보. 고기/파스타가 이어질 때 좋다.",
    tips: ["저녁 예약 권장", "가벼운 접시 여러 개 공유"],
    menuHints: ["멸치버터", "해산물 파스타", "화이트 와인"],
    pairWith: ["santo-spirito-basilica", "pitti-gola-e-cantina"],
    sourceIds: ["eater-florence", "curious-appetite"],
  },
  {
    id: "il-magazzino",
    city: "florence",
    name: "Il Magazzino",
    koName: "일 마가치노",
    category: "food",
    area: "산토 스피리토",
    lat: 43.7682,
    lng: 11.2505,
    priority: 2,
    rank: 81,
    durationMin: 80,
    reservation: "권장",
    bestTime: "점심",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["내장요리", "토스카나", "광장"],
    why: "산토 스피리토 광장의 토스카나 내장요리 강자. 람프레도토를 식당 버전으로 먹고 싶을 때.",
    tips: ["내장류가 부담되면 파스타/라구로 우회", "광장 산책과 묶기"],
    menuHints: ["람프레도토", "트리파", "라구"],
    pairWith: ["santo-spirito-basilica", "osteria-santo-spirito", "le-volpi-e-luva"],
    sourceIds: ["curious-appetite", "girl-in-florence"],
  },
  {
    id: "trippaio-albergucci-mario",
    city: "florence",
    name: "Trippaio Albergucci Mario",
    koName: "트리파이오 알베르구치 마리오",
    category: "food",
    area: "포르타 로마나",
    lat: 43.762,
    lng: 11.2436,
    priority: 3,
    rank: 77,
    durationMin: 25,
    reservation: "불필요",
    bestTime: "점심",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["람프레도토", "길거리음식", "가성비", "30분컷"],
    why: "Livingetc 로컬 가이드에서도 언급된 람프레도토 가판. 피렌체 길거리 음식의 핵심을 빠르게 경험한다.",
    tips: ["점심 시간대", "매운 소스 여부 확인"],
    menuHints: ["람프레도토 파니노", "살사 베르데", "트리파"],
    pairWith: ["pitti-boboli", "forte-belvedere"],
    sourceIds: ["livingetc-florence", "curious-appetite"],
  },
  {
    id: "buca-dell-orafo",
    city: "florence",
    name: "Buca dell'Orafo",
    koName: "부카 델로라포",
    category: "food",
    area: "폰테베키오",
    lat: 43.7677,
    lng: 11.2542,
    priority: 2,
    rank: 83,
    durationMin: 85,
    reservation: "필수",
    bestTime: "점심 또는 저녁",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 3,
    tags: ["전통", "부카", "폰테베키오", "예약필수"],
    why: "폰테베키오 아래쪽의 작은 전통 식당. Livingetc와 로컬 가이드에서 전통 피렌체 음식 후보로 추천된다.",
    tips: ["좌석 적어 예약 필수", "다리 주변 관광지 식당 중 선별 후보"],
    menuHints: ["완두콩 스파게티", "비istecca", "토스카나 전채"],
    pairWith: ["ponte-vecchio", "santa-felicita-capponi", "uffizi"],
    sourceIds: ["livingetc-florence", "cntraveler-florence"],
  },
  {
    id: "coco-lezzone",
    city: "florence",
    name: "Coco Lezzone",
    koName: "코코 레초네",
    category: "food",
    area: "산타 마리아 노벨라",
    lat: 43.7715,
    lng: 11.2506,
    priority: 3,
    rank: 76,
    durationMin: 75,
    reservation: "권장",
    bestTime: "점심",
    price: "중간",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["전통", "토스카나", "중심부"],
    why: "오래된 피렌체 전통 식당. 중심부에서 클래식한 토스카나 음식을 원할 때 넣기 쉽다.",
    tips: ["운영 시간 확인", "전통적이고 러프한 분위기"],
    menuHints: ["리볼리타", "로스트", "하우스 와인"],
    pairWith: ["officina-profumo", "santa-maria-novella-basilica"],
    sourceIds: ["cntraveler-florence", "girl-in-florence"],
  },
  {
    id: "teatro-del-sale",
    city: "florence",
    name: "Teatro del Sale",
    koName: "테아트로 델 살레",
    category: "food",
    area: "산타 크로체",
    lat: 43.7705,
    lng: 11.2627,
    priority: 3,
    rank: 77,
    durationMin: 100,
    reservation: "필수",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["공연", "뷔페", "경험형", "예약필수"],
    why: "식사와 공연을 결합한 피렌체식 경험형 공간. 평범한 저녁보다 기억에 남는 구성이 필요할 때.",
    tips: ["프로그램 확인 후 예약", "일반 식당보다 경험형으로 기대치 설정"],
    menuHints: ["공연 포함 식사", "토스카나 메뉴", "와인"],
    pairWith: ["santa-croce", "mercato-sant-ambrogio", "casa-buonarroti"],
    sourceIds: ["cntraveler-florence-things", "girl-in-florence"],
  },
  {
    id: "ora-daria",
    city: "florence",
    name: "Ora d'Aria",
    koName: "오라 다리아",
    category: "food",
    area: "우피치",
    lat: 43.7715,
    lng: 11.2575,
    priority: 3,
    rank: 78,
    durationMin: 120,
    reservation: "필수",
    bestTime: "저녁",
    price: "높음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["파인다이닝", "예약필수", "기념일"],
    why: "우피치 근처 파인다이닝 후보. 여행 중 하루를 확실히 특별하게 쓰고 싶을 때만 선택.",
    tips: ["예산과 드레스 코드 감안", "예약 필수"],
    menuHints: ["테이스팅 메뉴", "와인 페어링", "현대 토스카나"],
    watchOut: ["가격대 높고 식사 시간이 길다"],
    pairWith: ["uffizi", "piazza-signoria", "ponte-vecchio"],
    sourceIds: ["cntraveler-florence", "eater-florence"],
  },
  {
    id: "io-osteria-personale",
    city: "florence",
    name: "iO Osteria Personale",
    koName: "이오 오스테리아 페르소날레",
    category: "food",
    area: "산 프레디아노",
    lat: 43.7686,
    lng: 11.2399,
    priority: 3,
    rank: 79,
    durationMin: 100,
    reservation: "필수",
    bestTime: "저녁",
    price: "높음",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["모던", "디저트", "예약필수"],
    why: "Livingetc가 현대적인 선택지로 꼽은 창의적 오스테리아. 전통 토스카나와 다른 저녁을 원할 때.",
    tips: ["디저트가 특이해 하나 이상 주문", "예약과 예산 확인"],
    menuHints: ["창작 메뉴", "로즈마리 젤라또", "와인"],
    watchOut: ["전통 음식 기대와 다를 수 있음"],
    pairWith: ["santo-spirito-basilica", "burro-acciughe"],
    sourceIds: ["livingetc-florence", "curious-appetite"],
  },
  {
    id: "mister-pizza-duomo",
    city: "florence",
    name: "Mister Pizza",
    koName: "미스터 피자 두오모",
    category: "food",
    area: "두오모",
    lat: 43.7732,
    lng: 11.2554,
    priority: 3,
    rank: 70,
    durationMin: 35,
    reservation: "불필요",
    bestTime: "간단한 점심",
    price: "낮음",
    safety: "보통",
    photo: 1,
    girlsTripFit: 2,
    tags: ["피자", "두오모", "빠른식사", "가성비"],
    why: "두오모 바로 옆에서 빠르게 피자로 끼니를 해결하는 실용 후보. 맛집 목적보다 응급 식사용이다.",
    tips: ["뷰/위치값 감안", "시간 없을 때만"],
    menuHints: ["마르게리타", "글루텐프리 피자", "테이크아웃"],
    pairWith: ["duomo-florence", "giottos-campanile", "edoardo-gelato"],
    sourceIds: ["timeout-florence"],
  },
  {
    id: "volume-firenze",
    city: "florence",
    name: "Volume",
    koName: "볼루메",
    category: "cafe",
    area: "산토 스피리토",
    lat: 43.7676,
    lng: 11.2496,
    priority: 3,
    rank: 73,
    durationMin: 55,
    reservation: "불필요",
    bestTime: "저녁",
    price: "중간",
    safety: "보통",
    photo: 2,
    girlsTripFit: 3,
    tags: ["카페", "칵테일", "광장", "아페리티보"],
    why: "산토 스피리토 광장의 캐주얼 카페/바. 올트라르노 저녁 산책 중 쉬어가기 좋다.",
    tips: ["식사보다는 음료/아페리티보", "광장 좌석은 피크에 붐빔"],
    menuHints: ["스프리츠", "칵테일", "간단 안주"],
    pairWith: ["santo-spirito-basilica", "il-magazzino", "le-volpi-e-luva"],
    sourceIds: ["girl-in-florence", "timeout-florence"],
  },
  {
    id: "loggia-rooftop-florence",
    city: "florence",
    name: "Loggia Rooftop Bar",
    koName: "로지아 루프탑 바",
    category: "view",
    area: "미켈란젤로 광장권",
    lat: 43.7653,
    lng: 11.2631,
    priority: 3,
    rank: 74,
    durationMin: 60,
    reservation: "권장",
    bestTime: "해질녘",
    price: "중간",
    safety: "보통",
    photo: 3,
    girlsTripFit: 3,
    tags: ["루프탑", "일몰", "칵테일", "전망"],
    why: "피렌체 전경을 보며 음료를 마시는 전망형 후보. 미켈란젤로 광장 산책과 잘 맞는다.",
    tips: ["해질녘 자리 예약/확인", "식사보다 음료 중심"],
    menuHints: ["스프리츠", "칵테일", "스몰 플레이트"],
    pairWith: ["piazzale-michelangelo", "san-miniato-al-monte", "rose-garden"],
    sourceIds: ["timeout-florence", "cntraveler-florence-things"],
  },
];
