import { tripDays, type TripDay } from "./data";

// 여행 템플릿 4종 — 날짜 골격(로마 5 + 6/24 이동 + 피렌체 4)과 예약 고정 앵커
// (콜로세움·바티칸·우피치·아카데미아·두오모·기차)는 공통, 동선 밀도와 장소 선정만 다르다.
// day id는 달력 날짜라 모든 템플릿이 같은 id를 쓴다 — 적용 시 통째로 교체되는 전제.
export type TripTemplate = {
  id: "classic" | "foodie" | "relaxed" | "photo";
  name: string;
  tagline: string;
  description: string;
  highlights: string[];
  days: TripDay[];
};

const foodieDays: TripDay[] = [
  {
    id: "2026-06-19",
    date: "2026-06-19",
    label: "6/19 금",
    city: "rome",
    title: "도착 + 나보나 먹거리 시동",
    areaFocus: "판테온, 나보나",
    route: [
      { placeId: "rome-hotel", time: "체크인", locked: true },
      { placeId: "pantheon", note: "외관+내부 가볍게 — 본편은 음식" },
      { placeId: "sant-eustachio", note: "그란 카페 — 로마 커피 신고식" },
      { placeId: "da-francesco", time: "저녁", note: "예약 권장 — 전채+피자" },
      { placeId: "frigidarium", note: "식후 젤라또" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["도착 늦으면 숙소 근처 파니니로 축소", "다 프란체스코 만석이면 쿨데삭(와인바)"],
    checklist: ["저녁 예약 확인", "현금 소액 준비", "콜로세움 QR 저장"],
  },
  {
    id: "2026-06-20",
    date: "2026-06-20",
    label: "6/20 토",
    city: "rome",
    title: "콜로세움 + 몬티 미식",
    areaFocus: "콜로세움, 몬티, 트레비",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "colosseum-forum", time: "오전", locked: true },
      { placeId: "la-taverna-dei-fori-imperiali", time: "점심", locked: true, note: "포리 임페리알리 옆 가족 식당 — 예약 필수" },
      { placeId: "monti", note: "빈티지 골목 — 소화 산책" },
      { placeId: "fatamorgana-monti", note: "몬티 대표 젤라또" },
      { placeId: "trevi-fountain", time: "해질녘" },
      { placeId: "antica-birreria-peroni", time: "저녁", note: "1906 비어홀 — 가성비 저녁" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["점심 예약 실패 시 몬티 안쪽 트라토리아", "비어홀 휴무(일)면 트레비 근처 파니니"],
    checklist: ["콜로세움 QR", "점심 예약", "물·선크림"],
  },
  {
    id: "2026-06-21",
    date: "2026-06-21",
    label: "6/21 일",
    city: "rome",
    title: "바티칸 + 본치 + 트라스테베레",
    areaFocus: "바티칸, 프라티, 트라스테베레",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "vatican-museums", time: "예약", locked: true },
      { placeId: "bonci-pizzarium", time: "점심", note: "조각 피자의 전설 — 줄 금방 빠짐" },
      { placeId: "old-bridge-gelateria", note: "바티칸 옆 3대 젤라또" },
      { placeId: "castel-sant-angelo", note: "외부+다리만" },
      { placeId: "da-enzo", time: "저녁", locked: true, note: "오픈런 또는 예약 — 카르보나라" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["다 엔조 실패 시 토나렐로·라 타베르나치아", "체력 떨어지면 산탄젤로 생략"],
    checklist: ["바티칸 예약", "성당 복장", "저녁 플랜B 확인"],
  },
  {
    id: "2026-06-22",
    date: "2026-06-22",
    label: "6/22 월",
    city: "rome",
    title: "시장 + 게토 + 로숄리",
    areaFocus: "캄포 데 피오리, 유대인 게토",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "campo-de-fiori", time: "아침", note: "아침 시장 구경" },
      { placeId: "forno-campo-de-fiori", note: "피자 비앙카 한 조각" },
      { placeId: "jewish-ghetto", note: "카르초피(아티초크) 골목" },
      { placeId: "roscioli", time: "점심", locked: true, note: "카르보나라·부라타 — 예약 필수" },
      { placeId: "supplizio", note: "수플리 명가 — 간식" },
      { placeId: "giolitti", note: "판테온 뒤 젤라또 마무리" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["로숄리 실패 시 그라폴로 도로", "배부르면 오후는 카페 휴식으로 압축"],
    checklist: ["로숄리 예약", "시장 소매치기 주의", "아침 가볍게 — 위 비우기"],
  },
  {
    id: "2026-06-23",
    date: "2026-06-23",
    label: "6/23 화",
    city: "rome",
    title: "테스타치오 — 로마의 부엌",
    areaFocus: "테스타치오, 트라스테베레",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "testaccio-market", time: "오전", note: "스트릿푸드 — 트라피치노 원조 동네" },
      { placeId: "felice-testaccio", time: "점심", locked: true, note: "카치오 에 페페 원조 — 예약 필수" },
      { placeId: "fassi-gelato", note: "1880 젤라또 궁전" },
      { placeId: "trastevere", time: "저녁 전", note: "골목 산책으로 소화" },
      { placeId: "pizzeria-da-remo", time: "저녁", note: "로마식 피자 — 오픈(19시) 직후" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["펠리체 실패 시 피아토 로마노", "저녁 부담되면 아이 마르미로 변경"],
    checklist: ["펠리체 예약", "현금(다 레모 현금만)", "다음날 기차 짐 정리"],
  },
  {
    id: "2026-06-24",
    date: "2026-06-24",
    label: "6/24 수",
    city: "florence",
    title: "이동 + 메르카토 첸트랄레 입성",
    areaFocus: "테르미니, SMN, 산 로렌초",
    route: [
      { placeId: "rome-hotel", time: "체크아웃", locked: true },
      { placeId: "roma-termini", time: "기차", locked: true },
      { placeId: "santa-maria-novella", time: "도착", locked: true },
      { placeId: "florence-hotel", time: "체크인", locked: true },
      { placeId: "mercato-centrale", time: "저녁", note: "2층 푸드코트 — 토스카나 신고식" },
      { placeId: "gelateria-santa-trinita", note: "흑임자 젤라또 + 다리 일몰" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["도착 늦으면 첸트랄레만", "비 오면 젤라또 생략"],
    checklist: ["기차 QR", "플랫폼 확인", "숙소 체크인 시간"],
  },
  {
    id: "2026-06-25",
    date: "2026-06-25",
    label: "6/25 목",
    city: "florence",
    title: "두오모 + 산 로렌초 노포",
    areaFocus: "두오모, 산 로렌초",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "duomo-florence", time: "오전", locked: true },
      { placeId: "accademia", time: "예약", locked: true },
      { placeId: "trattoria-mario", time: "점심", note: "12시 오픈런 — 현금만, 합석" },
      { placeId: "my-sugar", note: "부부가 만드는 수제 젤라또" },
      { placeId: "il-latini", time: "저녁", locked: true, note: "프로슈토 천장 코스 — 예약 필수" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["마리오 줄 과하면 세르조 고치", "일 라티니 실패 시 자자(예약 쉬움)"],
    checklist: ["두오모·아카데미아 예약", "일 라티니 예약", "현금"],
  },
  {
    id: "2026-06-26",
    date: "2026-06-26",
    label: "6/26 금",
    city: "florence",
    title: "우피치 + 티본의 날",
    areaFocus: "시뇨리아, 산타 마리아 노벨라",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "uffizi", time: "예약", locked: true },
      { placeId: "all-antico-vinaio", time: "점심", note: "파니니 줄집 — 회전 빠름" },
      { placeId: "gelateria-dei-neri", note: "리코타 무화과" },
      { placeId: "ponte-vecchio", time: "해질녘" },
      { placeId: "trattoria-dall-oste", time: "저녁", locked: true, note: "티본 — 한국인 1순위, 예약 필수" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["달오스테 실패 시 디 캄비(로컬 티본)", "파니니 줄 길면 이 두에 프라텔리니"],
    checklist: ["우피치 예약", "티본 저녁 예약", "점심 가볍게"],
  },
  {
    id: "2026-06-27",
    date: "2026-06-27",
    label: "6/27 토",
    city: "florence",
    title: "산탐브로조 + 올트라르노 와인",
    areaFocus: "산탐브로조, 산토 스피리토",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "mercato-sant-ambrogio", time: "오전", note: "관광객 적은 로컬 시장" },
      { placeId: "cibreo-caffe", note: "시장 옆 클래식 카페" },
      { placeId: "trattoria-la-casalinga", time: "점심", note: "가정식 — 리볼리타" },
      { placeId: "santo-spirito-basilica", note: "광장 분위기 + 성당" },
      { placeId: "le-volpi-e-luva", note: "아페리티보 — 치즈+내추럴 와인" },
      { placeId: "il-santo-bevitore", time: "저녁", locked: true, note: "모던 토스카나 — 예약 권장" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["카살링가 줄 길면 오스테리아 산토 스피리토", "와인바 만석이면 피티 골라 에 칸티나"],
    checklist: ["저녁 예약", "시장은 현금 편함", "귀가 루트"],
  },
  {
    id: "2026-06-28",
    date: "2026-06-28",
    label: "6/28 일",
    city: "florence",
    title: "마지막 식료품 회수 + 출발",
    areaFocus: "숙소, 산 로렌초, SMN",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "officina-profumo", note: "선물 마지막 회수" },
      { placeId: "mercato-centrale", note: "식료품 선물 + 가벼운 식사" },
      { placeId: "santa-maria-novella", time: "이동", locked: true },
    ],
    fallback: ["시간 빠듯하면 숙소-역만", "짐 무거우면 쇼핑 축소"],
    checklist: ["체크아웃 시간", "짐 보관", "공항 이동 루트"],
  },
];

const relaxedDays: TripDay[] = [
  {
    id: "2026-06-19",
    date: "2026-06-19",
    label: "6/19 금",
    city: "rome",
    title: "도착 — 가볍게 적응만",
    areaFocus: "판테온, 나보나",
    route: [
      { placeId: "rome-hotel", time: "체크인", locked: true },
      { placeId: "pantheon", note: "내부 또는 외부만 — 무리 금지" },
      { placeId: "sant-eustachio", note: "카페 한 잔으로 시차 풀기" },
      { placeId: "piazza-navona", time: "저녁", note: "분수 야경 짧게" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["피곤하면 숙소 근처 저녁만", "판테온은 다른 날 언제든 보충 가능"],
    checklist: ["숙소 위치 등록", "eSIM 확인", "물"],
  },
  {
    id: "2026-06-20",
    date: "2026-06-20",
    label: "6/20 토",
    city: "rome",
    title: "콜로세움 오전 + 아벤티노 일몰",
    areaFocus: "콜로세움, 아벤티노",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "colosseum-forum", time: "오전", locked: true, note: "오전에 끝내고 한낮은 쉰다" },
      { placeId: "caffe-propaganda", note: "회복 카페" },
      { placeId: "rome-hotel", time: "한낮", note: "시에스타 — 제일 더운 시간 피하기" },
      { placeId: "orange-garden", time: "해질녘", note: "오렌지 정원 일몰" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["더위 심하면 일몰만 나가기", "아벤티노 대신 숙소 근처 산책도 OK"],
    checklist: ["콜로세움 QR", "선크림·모자", "낮잠 죄책감 버리기"],
  },
  {
    id: "2026-06-21",
    date: "2026-06-21",
    label: "6/21 일",
    city: "rome",
    title: "바티칸 + 자니콜로 일몰",
    areaFocus: "바티칸, 자니콜로",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "vatican-museums", time: "예약", locked: true },
      { placeId: "st-peters-basilica", note: "쿠폴라 등반은 체력 보고 생략 가능" },
      { placeId: "old-bridge-gelateria", note: "젤라또 당 충전" },
      { placeId: "rome-hotel", time: "한낮", note: "휴식" },
      { placeId: "janiculum-terrace", time: "해질녘", note: "로마 전경 일몰" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["박물관 후 지치면 자니콜로 생략", "일몰은 핀초 테라스로 대체 가능"],
    checklist: ["바티칸 예약", "성당 복장", "보조배터리"],
  },
  {
    id: "2026-06-22",
    date: "2026-06-22",
    label: "6/22 월",
    city: "rome",
    title: "보르게세 공원 산책의 날",
    areaFocus: "보르게세, 스파냐",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "villa-borghese", time: "오전", note: "그늘 산책" },
      { placeId: "pincio-terrace", note: "포폴로 광장 내려다보기" },
      { placeId: "ginger-spagna", time: "점심", note: "샐러드·주스로 입맛 환기" },
      { placeId: "rome-hotel", time: "한낮", note: "휴식" },
      { placeId: "trevi-fountain", time: "밤", note: "밤 10시 이후가 한산" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["더우면 공원 대신 실내 카페", "트레비는 아침 일찍으로 바꿔도 됨"],
    checklist: ["모자", "물", "트레비 동전"],
  },
  {
    id: "2026-06-23",
    date: "2026-06-23",
    label: "6/23 화",
    city: "rome",
    title: "트라스테베레 느긋한 하루",
    areaFocus: "트라스테베레",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "trastevere", time: "오전", note: "인파 몰리기 전 골목 산책" },
      { placeId: "santa-maria-trastevere", note: "황금 모자이크" },
      { placeId: "tonnarello", time: "점심", note: "줄 생기기 전 일찍" },
      { placeId: "rome-hotel", time: "오후", note: "짐 정리 + 휴식" },
      { placeId: "barnum-cafe", note: "저녁 전 커피 한 잔" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["짐 정리 우선이면 오후 일정 생략", "저녁은 숙소 근처에서 간단히"],
    checklist: ["다음날 기차 시간", "짐 정리", "체크아웃 준비"],
  },
  {
    id: "2026-06-24",
    date: "2026-06-24",
    label: "6/24 수",
    city: "florence",
    title: "이동 — 무리 없이",
    areaFocus: "테르미니, SMN",
    route: [
      { placeId: "rome-hotel", time: "체크아웃", locked: true },
      { placeId: "roma-termini", time: "기차", locked: true },
      { placeId: "santa-maria-novella", time: "도착", locked: true },
      { placeId: "florence-hotel", time: "체크인", locked: true },
      { placeId: "ponte-vecchio", time: "해질녘", note: "도착 인사만 — 짧게" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["늦게 도착하면 다리 생략", "저녁은 숙소 근처"],
    checklist: ["기차 QR", "짐", "체크인 시간"],
  },
  {
    id: "2026-06-25",
    date: "2026-06-25",
    label: "6/25 목",
    city: "florence",
    title: "두오모 + 아카데미아 + 낮잠",
    areaFocus: "두오모, 산 로렌초",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "duomo-florence", time: "오전", locked: true, note: "등반은 선택" },
      { placeId: "accademia", time: "예약", locked: true },
      { placeId: "mercato-centrale", time: "점심", note: "푸드코트에서 간단히" },
      { placeId: "florence-hotel", time: "한낮", note: "시에스타" },
      { placeId: "caffe-gilli", note: "광장 카페로 하루 마무리" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["지치면 질리 생략", "등반은 컨디션 좋은 날만"],
    checklist: ["두오모·아카데미아 예약", "성당 복장", "물"],
  },
  {
    id: "2026-06-26",
    date: "2026-06-26",
    label: "6/26 금",
    city: "florence",
    title: "우피치 + 바르디니 정원 일몰",
    areaFocus: "우피치, 올트라르노",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "uffizi", time: "예약", locked: true },
      { placeId: "gelateria-dei-neri", note: "당 충전" },
      { placeId: "florence-hotel", time: "한낮", note: "휴식" },
      { placeId: "bardini-garden", time: "해질녘", note: "두오모 뷰 — 미켈란젤로 광장보다 한산" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["정원 마감 이르면 미켈란젤로 광장으로", "비 오면 실내 카페"],
    checklist: ["우피치 예약", "정원 개장시간 확인", "편한 신발"],
  },
  {
    id: "2026-06-27",
    date: "2026-06-27",
    label: "6/27 토",
    city: "florence",
    title: "보볼리 + 산 미니아토",
    areaFocus: "피티, 올트라르노 언덕",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "pitti-boboli", time: "오전", note: "정원 위주로 느긋하게" },
      { placeId: "santarosa-bistrot", time: "점심", note: "성벽 정원 비스트로" },
      { placeId: "florence-hotel", time: "한낮", note: "휴식" },
      { placeId: "san-miniato-al-monte", time: "해질녘", note: "미켈란젤로 광장보다 한 층 위 — 한산" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["언덕 부담되면 광장까지만", "더우면 보볼리 축소"],
    checklist: ["일몰 시간", "물", "귀가 루트"],
  },
  {
    id: "2026-06-28",
    date: "2026-06-28",
    label: "6/28 일",
    city: "florence",
    title: "버퍼 — 천천히 마무리",
    areaFocus: "숙소, SMN",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "officina-profumo", note: "선물 회수" },
      { placeId: "santa-maria-novella", time: "이동", locked: true },
    ],
    fallback: ["시간 남으면 두오모 외부 한 번 더", "빠듯하면 숙소-역만"],
    checklist: ["체크아웃", "짐 보관", "이동 루트"],
  },
];

const photoDays: TripDay[] = [
  {
    id: "2026-06-19",
    date: "2026-06-19",
    label: "6/19 금",
    city: "rome",
    title: "도착 + 빛 좋은 첫 컷",
    areaFocus: "판테온, 나보나",
    route: [
      { placeId: "rome-hotel", time: "체크인", locked: true },
      { placeId: "pantheon", note: "오쿨루스 빛 — 오후 사선광이 예쁨" },
      { placeId: "piazza-navona", time: "해질녘", note: "분수 + 가로등 점등 타이밍" },
      { placeId: "frigidarium", note: "젤라또 손샷" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["늦으면 나보나 야경만", "흐리면 실내(판테온) 위주"],
    checklist: ["카메라·폰 풀충전", "보조배터리", "메모리 정리"],
  },
  {
    id: "2026-06-20",
    date: "2026-06-20",
    label: "6/20 토",
    city: "rome",
    title: "새벽 트레비 + 콜로세움",
    areaFocus: "트레비, 콜로세움, 몬티",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "trevi-fountain", time: "아침 7시", note: "무인 트레비 — 이 템플릿의 핵심 컷" },
      { placeId: "colosseum-forum", time: "오전", locked: true, note: "아치 프레임 컷" },
      { placeId: "monti", note: "파스텔 골목 스냅" },
      { placeId: "galleria-sciarra", note: "아르누보 천장 — 무료" },
      { placeId: "altare-patria", time: "해질녘", note: "테라스 파노라마" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["새벽 기상 실패 시 밤 10시 이후 트레비", "더우면 몬티 카페로 피난"],
    checklist: ["새벽 알람", "콜로세움 QR", "메모리 카드 여유"],
  },
  {
    id: "2026-06-21",
    date: "2026-06-21",
    label: "6/21 일",
    city: "rome",
    title: "바티칸 + 천사의 다리 일몰",
    areaFocus: "바티칸, 산탄젤로",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "vatican-museums", time: "예약", locked: true, note: "브라만테 나선계단 컷" },
      { placeId: "st-peters-basilica", note: "쿠폴라 등반 — 광장 부감 샷" },
      { placeId: "old-bridge-gelateria", note: "당 충전" },
      { placeId: "castel-sant-angelo", time: "해질녘", note: "천사 조각 + 다리 실루엣" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["쿠폴라 줄 길면 생략", "일몰 흐리면 다리 야경으로 전환"],
    checklist: ["바티칸 예약", "성당 복장", "광각 준비"],
  },
  {
    id: "2026-06-22",
    date: "2026-06-22",
    label: "6/22 월",
    city: "rome",
    title: "스파냐 아침 + 핀초 일몰",
    areaFocus: "스파냐, 포폴로",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "spanish-steps", time: "아침", note: "인파 전 계단 컷" },
      { placeId: "via-margutta", note: "담쟁이 골목 — 로마의 휴일" },
      { placeId: "via-condotti", note: "쇼윈도 스트리트 스냅" },
      { placeId: "coromandel", time: "브런치", note: "로마에서 가장 예쁜 아침상" },
      { placeId: "villa-borghese", note: "그늘 산책" },
      { placeId: "pincio-terrace", time: "해질녘", note: "포폴로 광장 + 성베드로 돔 일몰" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["브런치 만석이면 진저", "더우면 공원 구간 축소"],
    checklist: ["아침 일찍 출발", "촬영용 옷", "예약(브런치) 확인"],
  },
  {
    id: "2026-06-23",
    date: "2026-06-23",
    label: "6/23 화",
    city: "rome",
    title: "아벤티노 + 트라스테베레 골든아워",
    areaFocus: "아벤티노, 트라스테베레",
    route: [
      { placeId: "rome-hotel", locked: true },
      { placeId: "orange-garden", time: "오전", note: "소나무 프레임 전망 컷" },
      { placeId: "aventine-keyhole", note: "열쇠구멍 — 아침이 줄 짧음" },
      { placeId: "bocca-della-verita", note: "진실의 입 — 오픈 직후" },
      { placeId: "trastevere", time: "오후", note: "담쟁이 골목 스냅" },
      { placeId: "santa-maria-trastevere", note: "황금 모자이크" },
      { placeId: "janiculum-terrace", time: "해질녘", note: "로마 스카이라인 일몰" },
      { placeId: "rome-hotel", time: "밤", locked: true },
    ],
    fallback: ["줄 길면 열쇠구멍 패스", "자니콜로는 체력 보고 택시"],
    checklist: ["짐 정리(내일 이동)", "기차 QR", "편한 신발"],
  },
  {
    id: "2026-06-24",
    date: "2026-06-24",
    label: "6/24 수",
    city: "florence",
    title: "이동 + 미켈란젤로 광장 일몰",
    areaFocus: "SMN, 미켈란젤로 광장",
    route: [
      { placeId: "rome-hotel", time: "체크아웃", locked: true },
      { placeId: "roma-termini", time: "기차", locked: true },
      { placeId: "santa-maria-novella", time: "도착", locked: true },
      { placeId: "florence-hotel", time: "체크인", locked: true },
      { placeId: "ponte-vecchio", note: "다리 위 인물컷 — 일몰 전" },
      { placeId: "piazzale-michelangelo", time: "해질녘", note: "피렌체 대표 일몰 — 도착 첫날 바로" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["도착 늦으면 다리만", "흐리면 다른 날 재도전"],
    checklist: ["기차 QR", "짐", "일몰 시간 확인"],
  },
  {
    id: "2026-06-25",
    date: "2026-06-25",
    label: "6/25 목",
    city: "florence",
    title: "두오모 등반 + 루프탑",
    areaFocus: "두오모, 레푸블리카",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "duomo-florence", time: "오전", locked: true, note: "쿠폴라/조토 종탑 — 테라코타 지붕 컷" },
      { placeId: "accademia", time: "예약", locked: true, note: "다비드 측면 컷" },
      { placeId: "caffe-gilli", note: "벨에포크 인테리어" },
      { placeId: "rinascente-florence-rooftop", time: "해질녘", note: "두오모 정면 루프탑" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["쿠폴라 매진 시 조토 종탑", "루프탑 만석이면 레푸블리카 야경"],
    checklist: ["등반 예약", "아카데미아 예약", "렌즈·메모리 정리"],
  },
  {
    id: "2026-06-26",
    date: "2026-06-26",
    label: "6/26 금",
    city: "florence",
    title: "우피치 + 산타 트리니타 일몰",
    areaFocus: "우피치, 강변",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "uffizi", time: "예약", locked: true, note: "복도 창에서 베키오 다리 부감" },
      { placeId: "piazza-signoria", note: "조각 군상 컷" },
      { placeId: "ponte-vecchio", note: "낮 컷" },
      { placeId: "gelateria-santa-trinita", time: "해질녘", note: "젤라또 들고 다리에서 베키오 일몰 정면" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["흐리면 실내 위주로", "일몰 명당은 30분 전 도착"],
    checklist: ["우피치 예약", "일몰 시간", "메모리 여유"],
  },
  {
    id: "2026-06-27",
    date: "2026-06-27",
    label: "6/27 토",
    city: "florence",
    title: "올트라르노 + 더블 일몰",
    areaFocus: "피티, 올트라르노 언덕",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "pitti-boboli", time: "오전", note: "보볼리 정원 부감" },
      { placeId: "santo-spirito-basilica", note: "광장 스냅" },
      { placeId: "bardini-garden", note: "두오모 프레임 정원" },
      { placeId: "san-miniato-al-monte", time: "해질녘", note: "일몰 직전 — 한산" },
      { placeId: "piazzale-michelangelo", time: "밤", note: "야경 보충 컷" },
      { placeId: "florence-hotel", time: "밤", locked: true },
    ],
    fallback: ["체력 따라 언덕 하나만", "비 오면 실내 성당 위주"],
    checklist: ["일몰 시간", "물", "귀가 교통"],
  },
  {
    id: "2026-06-28",
    date: "2026-06-28",
    label: "6/28 일",
    city: "florence",
    title: "새벽 두오모 + 출발",
    areaFocus: "두오모, SMN",
    route: [
      { placeId: "florence-hotel", locked: true },
      { placeId: "duomo-florence", time: "아침", note: "무인 두오모 외관 — 마지막 컷" },
      { placeId: "santa-maria-novella", time: "이동", locked: true },
    ],
    fallback: ["빠듯하면 생략", "시간 남으면 강변 한 바퀴"],
    checklist: ["체크아웃", "짐", "기차 시간"],
  },
];

export const tripTemplates: TripTemplate[] = [
  {
    id: "classic",
    name: "클래식 필수 코스",
    tagline: "처음 가는 로마·피렌체의 정석",
    description: "필수 명소를 균형 있게 배치한 기본 코스. 예약 앵커 + 검증된 맛집 + 무리 없는 동선.",
    highlights: ["필수 명소 균형", "검증 맛집", "무난한 체력"],
    days: tripDays,
  },
  {
    id: "foodie",
    name: "미식 로드",
    tagline: "시장·트라토리아·젤라또 중심의 먹는 여행",
    description:
      "명소는 예약 앵커만 남기고 끼니마다 검증된 식당을 박아 넣은 코스. 점심·저녁 예약 슬롯이 명시돼 있어 예약만 따라가면 된다.",
    highlights: ["끼니마다 맛집", "시장 3곳", "예약 슬롯 명시"],
    days: foodieDays,
  },
  {
    id: "relaxed",
    name: "여유 만끽",
    tagline: "하루 4곳 이하 + 한낮 시에스타",
    description:
      "공원·전망·카페 비중을 높이고 한낮 휴식을 일정에 박아 넣은 저체력 코스. 6월 더위에 가장 현실적인 페이스.",
    highlights: ["하루 4곳 이하", "한낮 휴식 고정", "공원·전망 위주"],
    days: relaxedDays,
  },
  {
    id: "photo",
    name: "인생샷 헌터",
    tagline: "골든아워 동선으로 짠 사진 우선 코스",
    description:
      "새벽 트레비, 해질녘 전망대 등 빛 시간표에 맞춰 동선을 배치. 사진점수 높은 곳 위주로 매일 일출·일몰 슬롯이 있다.",
    highlights: ["새벽·골든아워 동선", "전망대 매일 1곳", "사진점수 3 위주"],
    days: photoDays,
  },
];
